<span style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">An Exception was encountered at '<a href="#papermill-error-cell">In [13]</a>'.</span>

In [1]:
field = 'NW'
max_zoi = 100

In [2]:
# Parameters
field = "F5"

# 6: With the domains, sum the flux within the region boundaries

In [3]:
from dataclasses import replace

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from astropy.io import fits
import os

from m33_pipeline import paths
from m33_pipeline.config import get_photometry_config
from m33_pipeline.io import read_catalog, read_fits_data, read_fits_data_header
from m33_pipeline.photometry import build_field_flux_catalog, load_flux_maps, load_integrated_flux_table, load_region_inputs
from m33_pipeline.validate import validate_field_flux_catalog

In [4]:
# Field-level region photometry now lives in m33_pipeline.photometry.
# This notebook keeps the downstream extinction, BPT, and plotting steps.

In [5]:
photometry_config = replace(get_photometry_config(), max_zoi_pc=max_zoi)
merged_df = build_field_flux_catalog(field, max_zoi, photometry_config)

validation_warnings = validate_field_flux_catalog(merged_df, field)
if validation_warnings:
    print("Validation warnings:")
    for warning in validation_warnings:
        print(f"- {warning}")

# Compatibility variables for downstream notebook cells that still expect the old inline setup.
flux_maps = load_flux_maps(field)
ha_flux_data, ha_flux_err_data = flux_maps["Halpha"]
hb_flux_data, hb_flux_err_data = flux_maps["Hbeta"]
oiii_flux_data, oiii_flux_err_data = flux_maps["[OIII]5007"]
sii6716_flux_data, sii6716_flux_err_data = flux_maps["[SII]6716"]
sii6731_flux_data, sii6731_flux_err_data = flux_maps["[SII]6731"]
nii6584_flux_data, nii6584_flux_err_data = flux_maps["[NII]6583"]
oii3727_flux_data, oii3727_flux_err_data = flux_maps["[OII]3727"]

ha_flux_data, ha_flux_header = read_fits_data_header(paths.calibrated_field_map_dir(field) / f"M33{field}-Haflux.fits")
region_inputs = load_region_inputs(field, max_zoi)
peaks_df = region_inputs["peaks_df"]
zoi_map = region_inputs["zoi_map"]
boundary_map = region_inputs["boundary_map"]
boundary_metric_df = region_inputs["boundary_metrics_df"]
int_flux_df = load_integrated_flux_table(field, len(peaks_df))

print("Built field flux catalog:", merged_df.shape)
merged_df.head()

Validation warnings:
- F5 flux catalog: duplicate values found in region_id
Built field flux catalog: (741, 69)

,region_id,npix_region,npix_edge_ring,F_Halpha_sum,F_Halpha_e_sum,SNR_Halpha_sum,Halpha_b_edge,F_Halpha_bgsub,SNR_Halpha_bgsub,F_Hbeta_sum,...,radius_p16_pc,radius_p50_pc,radius_p84_pc,radius_areaeq_px,radius_areaeq_pc,boundary_method,area_px_after_carve,radius_areaeq_px_after_carve,radius_areaeq_pc_after_carve,id_int
0,1.0,69.0,43.0,9.487527e-16,5.467802e-17,17.351631,1.433092e-17,-4.008062e-17,-0.733030,3.652461e-16,...,2.891870,4.799533,8.399556,4.686511,6.041330,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,69.0,4.686511,6.041330,0
1,2.0,301.0,66.0,1.301978e-14,1.176064e-16,110.706362,4.492848e-17,-5.036972e-16,-4.282906,4.051028e-15,...,3.437571,14.855218,15.846033,9.788323,12.618022,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,301.0,9.788323,12.618022,1
2,3.0,598.0,104.0,5.241132e-14,1.621037e-16,323.319710,6.942703e-17,1.089396e-14,67.203627,1.395986e-14,...,3.437571,20.105258,28.718630,13.796714,17.785195,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,598.0,13.796714,17.785195,2
3,4.0,145.0,50.0,5.923150e-15,8.233364e-17,71.940827,3.727495e-17,5.182825e-16,6.294906,1.686315e-15,...,6.875142,7.734535,10.312714,6.793742,8.757740,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,145.0,6.793742,8.757740,3
4,5.0,247.0,56.0,2.379882e-14,1.020247e-16,233.265332,6.409070e-17,7.968419e-15,78.102856,5.118345e-15,...,7.116357,11.397198,15.101528,8.866935,11.430270,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,247.0,8.866935,11.430270,4

In [6]:
print("Regions with npix_region == 0:", (merged_df["npix_region"] == 0).sum())

for line_name in ["Halpha", "Hbeta", "[OIII]5007", "[SII]6716", "[SII]6731", "[NII]6583", "[OII]3727"]:
    n_nan = merged_df[f"{line_name}_b_edge"].isna().sum()
    print(f"{line_name}: NaN edge backgrounds = {n_nan}")

for col in merged_df.columns:
    print(col)

Regions with npix_region == 0: 0
Halpha: NaN edge backgrounds = 8
Hbeta: NaN edge backgrounds = 8
[OIII]5007: NaN edge backgrounds = 8
[SII]6716: NaN edge backgrounds = 8
[SII]6731: NaN edge backgrounds = 8
[NII]6583: NaN edge backgrounds = 8
[OII]3727: NaN edge backgrounds = 8
region_id
npix_region
npix_edge_ring
F_Halpha_sum
F_Halpha_e_sum
SNR_Halpha_sum
Halpha_b_edge
F_Halpha_bgsub
SNR_Halpha_bgsub
F_Hbeta_sum
F_Hbeta_e_sum
SNR_Hbeta_sum
Hbeta_b_edge
F_Hbeta_bgsub
SNR_Hbeta_bgsub
F_[OIII]5007_sum
F_[OIII]5007_e_sum
SNR_[OIII]5007_sum
[OIII]5007_b_edge
F_[OIII]5007_bgsub
SNR_[OIII]5007_bgsub
F_[SII]6716_sum
F_[SII]6716_e_sum
SNR_[SII]6716_sum
[SII]6716_b_edge
F_[SII]6716_bgsub
SNR_[SII]6716_bgsub
F_[SII]6731_sum
F_[SII]6731_e_sum
SNR_[SII]6731_sum
[SII]6731_b_edge
F_[SII]6731_bgsub
SNR_[SII]6731_bgsub
F_[NII]6583_sum
F_[NII]6583_e_sum
SNR_[NII]6583_sum
[NII]6583_b_edge
F_[NII]6583_bgsub
SNR_[NII]6583_bgsub
F_[OII]3727_sum
F_[OII]3727_e_sum
SNR_[OII]3727_sum
[OII]3727_b_edge
F_[OII]3727_bgsub
SNR_[OII]3727_bgsub
field
y
x
removed_by_saddle
removed_by_edge
kind
center_x_px
center_y_px
zoi_center_label
bg_local
sigma_local
radius_p16_px
radius_p50_px
radius_p84_px
radius_p16_pc
radius_p50_pc
radius_p84_pc
radius_areaeq_px
radius_areaeq_pc
boundary_method
area_px_after_carve
radius_areaeq_px_after_carve
radius_areaeq_pc_after_carve
id_int

In [7]:
# Put your flux and error maps in a dict for looping
maps = {
    "Halpha":      (ha_flux_data, ha_flux_err_data),
    "Hbeta":      (hb_flux_data, hb_flux_err_data),
    "[OIII]5007":(oiii_flux_data, oiii_flux_err_data),
    "[SII]6716": (sii6716_flux_data, sii6716_flux_err_data),
    "[SII]6731": (sii6731_flux_data, sii6731_flux_err_data),
    "[NII]6583": (nii6584_flux_data, nii6584_flux_err_data),
    "[OII]3727": (oii3727_flux_data, oii3727_flux_err_data),
}

# Region labels present in boundary_map (ignore 0, NaNs)
labels = np.unique(boundary_map[np.isfinite(boundary_map)])
labels = labels[labels > 0].astype(int)

print(f"Found {len(labels)} regions (labels > 0). Min={labels.min() if len(labels) else None}, Max={labels.max() if len(labels) else None}")

Found 733 regions (labels > 0). Min=1, Max=741

In [8]:
from tqdm import tqdm
from scipy.ndimage import binary_dilation
def region_edge_ring(region_mask, iterations=1):
    """
    Build an *outer edge ring* just outside the region boundary.

    Exactly:
    - Take region_mask (True inside region)
    - Dilate it by `iterations` pixels
    - Outer ring = dilated_mask & (~region_mask)

    This produces a 1-pixel thick ring outside the region if iterations=1,
    thicker if iterations>1.
    """
    region_mask = np.asarray(region_mask, dtype=bool)
    dil = binary_dilation(region_mask, iterations=iterations)
    ring = dil & (~region_mask)
    return ring

def integrated_flux_and_snr(flux, err, region_mask, ring_mask=None, clip_negative_after_bg=False):
    """
    Compute integrated flux and SNR for a region.

    Definitions used (exact):
    1) Raw integrated flux:
       F_raw = sum_i flux_i  over pixels i inside region_mask

    2) Integrated uncertainty (assuming per-pixel errors are 1-sigma and independent):
       sigma_F = sqrt( sum_i err_i^2 )   over pixels i inside region_mask

    3) Raw SNR:
       SNR_sum = F_raw / sigma_F   (if sigma_F>0 else NaN)

    Background subtraction (if ring_mask provided):
    4) Background level per pixel:
       b = mean_j flux_j over pixels j in ring_mask
       (with NaN-safe mean)

    5) Background-subtracted integrated flux:
       F_bgsub = sum_i (flux_i - b) over region pixels
              = F_raw - b * Npix_region

       Uncertainty remains:
       sigma_F_bgsub = sigma_F
       (i.e., we *do not* add uncertainty from estimating b; if you want that,
        we can include it, but this is the simplest standard approach.)

    6) Background-subtracted SNR:
       SNR_bgsub = F_bgsub / sigma_F  (if sigma_F>0 else NaN)

    Options:
    - clip_negative_after_bg: if True, clip (flux_i - b) at 0 before summing.
      (Default False = physically allows negative after subtraction.)
    """
    flux = np.asarray(flux, dtype=float)
    err  = np.asarray(err, dtype=float)

    inside = region_mask
    f_vals = flux[inside]
    e_vals = err[inside]

    # NaN handling: ignore NaNs in flux; but for error we must also ignore same pixels
    good = np.isfinite(f_vals) & np.isfinite(e_vals)
    f_vals = f_vals[good]
    e_vals = e_vals[good]

    npix = f_vals.size
    if npix == 0:
        return dict(
            npix=0,
            F_raw=np.nan, sigma_F=np.nan, SNR_raw=np.nan,
            b_edge=np.nan, F_bgsub=np.nan, SNR_bgsub=np.nan
        )

    F_raw = np.sum(f_vals)
    sigma_F = np.sqrt(np.sum(e_vals**2))
    SNR_raw = F_raw / sigma_F if sigma_F > 0 else np.nan

    b_edge = np.nan
    F_bgsub = np.nan
    SNR_bgsub = np.nan

    if ring_mask is not None:
        ring_vals = flux[ring_mask]
        ring_vals = ring_vals[np.isfinite(ring_vals)]
        b_edge = np.nanmean(ring_vals) if ring_vals.size > 0 else np.nan

        # background subtract
        if np.isfinite(b_edge):
            if clip_negative_after_bg:
                F_bgsub = np.sum(np.clip(f_vals - b_edge, 0, None))
            else:
                F_bgsub = np.sum(f_vals - b_edge)

            SNR_bgsub = F_bgsub / sigma_F if sigma_F > 0 else np.nan
        else:
            F_bgsub = np.nan
            SNR_bgsub = np.nan

    return dict(
        npix=npix,
        F_raw=F_raw,
        sigma_F=sigma_F,
        SNR_raw=SNR_raw,
        b_edge=b_edge,
        # F_bgsub=F_bgsub,
        # SNR_bgsub=SNR_bgsub
    )

def merge_check_duplicates(left_df, right_df, on, how="left", suffixes=("_x", "_y"), rtol=0, atol=0):
    """
    Merge and resolve duplicate columns:
    - If a column name exists in both (excluding key columns), compare values.
    - If all equal within tolerance -> keep one.
    - If not equal -> keep both with suffixes.

    This expects 'on' to be a list or string key(s).
    """
    if isinstance(on, str):
        on = [on]

    overlap = (set(left_df.columns) & set(right_df.columns)) - set(on)
    merged = left_df.merge(right_df, on=on, how=how, suffixes=suffixes)

    for col in overlap:
        cx = f"{col}{suffixes[0]}"
        cy = f"{col}{suffixes[1]}"
        if cx in merged.columns and cy in merged.columns:
            a = merged[cx].to_numpy()
            b = merged[cy].to_numpy()

            # treat NaNs as equal where both NaN
            both_nan = np.isnan(a) & np.isnan(b) if (np.issubdtype(a.dtype, np.number) and np.issubdtype(b.dtype, np.number)) else np.zeros_like(a, dtype=bool)

            equal = False
            if np.issubdtype(a.dtype, np.number) and np.issubdtype(b.dtype, np.number):
                equal = np.allclose(a[~both_nan], b[~both_nan], rtol=rtol, atol=atol, equal_nan=True)
            else:
                equal = np.all((a == b) | (pd.isna(a) & pd.isna(b)))

            if equal:
                merged[col] = merged[cx]
                merged.drop(columns=[cx, cy], inplace=True)
            else:
                # keep both; do nothing
                pass

    return merged

In [9]:
# Parameters you can tune:
edge_ring_iterations = 1          # thickness of outer ring (pixels)
clip_negative_after_bg = False    # True if you want to force bgsub flux >= 0 per pixel

rows = []

for rid in tqdm(labels, desc="Processing regions"):
    region_mask = (boundary_map == rid)
    ring_mask = region_edge_ring(region_mask, iterations=edge_ring_iterations)

    row = {
        "region_id": rid,
        "npix_region": int(np.sum(region_mask)),
        "npix_edge_ring": int(np.sum(ring_mask)),
    }

    # # optional: store a region-wide average ZoI value (or something else)
    # if 'zoi_map' in globals() and zoi_map is not None:
    #     zvals = zoi_map[region_mask]
    #     zvals = zvals[np.isfinite(zvals)]
    #     row["zoi_mean"] = float(np.nanmean(zvals)) if zvals.size else np.nan
    #     row["zoi_median"] = float(np.nanmedian(zvals)) if zvals.size else np.nan
    # else:
    #     row["zoi_mean"] = np.nan
    #     row["zoi_median"] = np.nan

    for name, (flux, err) in maps.items():
        stats = integrated_flux_and_snr(
            flux=flux,
            err=err,
            region_mask=region_mask,
            ring_mask=ring_mask,
            clip_negative_after_bg=clip_negative_after_bg
        )

        # Write columns in a consistent naming scheme
        row[f"F_{name}_sum"]     = stats["F_raw"]
        row[f"F_{name}_e_sum"]   = stats["sigma_F"]
        row[f"SNR_{name}_sum"]   = stats["SNR_raw"]
        row[f"{name}_b_edge"]    = stats["b_edge"]
        # row[f"{name}_F_bgsub"]   = stats["F_bgsub"]
        # row[f"{name}_SNR_bgsub"] = stats["SNR_bgsub"]

    rows.append(row)

flux_catalog_df = pd.DataFrame(rows).sort_values("region_id").reset_index(drop=True)

flux_catalog_df.head()

Processing regions:   0%|                                                                                                                     | 0/733 [00:00<?, ?it/s]

Processing regions:   0%|▎                                                                                                            | 2/733 [00:00<00:55, 13.12it/s]

Processing regions:   1%|▌                                                                                                            | 4/733 [00:00<00:50, 14.41it/s]

Processing regions:   1%|▉                                                                                                            | 6/733 [00:00<00:47, 15.24it/s]

Processing regions:   1%|█▏                                                                                                           | 8/733 [00:00<00:47, 15.38it/s]

Processing regions:   1%|█▍                                                                                                          | 10/733 [00:00<00:46, 15.55it/s]

Processing regions:   2%|█▊                                                                                                          | 12/733 [00:00<00:46, 15.64it/s]

Processing regions:   2%|██                                                                                                          | 14/733 [00:00<00:45, 15.77it/s]

Processing regions:   2%|██▎                                                                                                         | 16/733 [00:01<00:48, 14.80it/s]

Processing regions:   2%|██▋                                                                                                         | 18/733 [00:01<00:47, 15.06it/s]

Processing regions:   3%|██▉                                                                                                         | 20/733 [00:01<00:46, 15.44it/s]

Processing regions:   3%|███▏                                                                                                        | 22/733 [00:01<00:45, 15.62it/s]

Processing regions:   3%|███▌                                                                                                        | 24/733 [00:01<00:45, 15.73it/s]

Processing regions:   4%|███▊                                                                                                        | 26/733 [00:01<00:44, 15.81it/s]

Processing regions:   4%|████▏                                                                                                       | 28/733 [00:01<00:44, 15.75it/s]

Processing regions:   4%|████▍                                                                                                       | 30/733 [00:01<00:44, 15.80it/s]

Processing regions:   4%|████▋                                                                                                       | 32/733 [00:02<00:44, 15.65it/s]

Processing regions:   5%|█████                                                                                                       | 34/733 [00:02<00:44, 15.69it/s]

Processing regions:   5%|█████▎                                                                                                      | 36/733 [00:02<00:44, 15.79it/s]

Processing regions:   5%|█████▌                                                                                                      | 38/733 [00:02<00:43, 15.89it/s]

Processing regions:   5%|█████▉                                                                                                      | 40/733 [00:02<00:43, 15.91it/s]

Processing regions:   6%|██████▏                                                                                                     | 42/733 [00:02<00:43, 15.94it/s]

Processing regions:   6%|██████▍                                                                                                     | 44/733 [00:02<00:42, 16.05it/s]

Processing regions:   6%|██████▊                                                                                                     | 46/733 [00:02<00:42, 16.00it/s]

Processing regions:   7%|███████                                                                                                     | 48/733 [00:03<00:43, 15.90it/s]

Processing regions:   7%|███████▎                                                                                                    | 50/733 [00:03<00:42, 15.91it/s]

Processing regions:   7%|███████▋                                                                                                    | 52/733 [00:03<00:42, 15.97it/s]

Processing regions:   7%|███████▉                                                                                                    | 54/733 [00:03<00:42, 16.02it/s]

Processing regions:   8%|████████▎                                                                                                   | 56/733 [00:03<00:42, 16.07it/s]

Processing regions:   8%|████████▌                                                                                                   | 58/733 [00:03<00:41, 16.09it/s]

Processing regions:   8%|████████▊                                                                                                   | 60/733 [00:03<00:42, 16.00it/s]

Processing regions:   8%|█████████▏                                                                                                  | 62/733 [00:03<00:42, 15.97it/s]

Processing regions:   9%|█████████▍                                                                                                  | 64/733 [00:04<00:42, 15.83it/s]

Processing regions:   9%|█████████▋                                                                                                  | 66/733 [00:04<00:42, 15.79it/s]

Processing regions:   9%|██████████                                                                                                  | 68/733 [00:04<00:42, 15.82it/s]

Processing regions:  10%|██████████▎                                                                                                 | 70/733 [00:04<00:41, 15.95it/s]

Processing regions:  10%|██████████▌                                                                                                 | 72/733 [00:04<00:41, 15.93it/s]

Processing regions:  10%|██████████▉                                                                                                 | 74/733 [00:04<00:41, 15.92it/s]

Processing regions:  10%|███████████▏                                                                                                | 76/733 [00:04<00:41, 16.00it/s]

Processing regions:  11%|███████████▍                                                                                                | 78/733 [00:04<00:40, 16.05it/s]

Processing regions:  11%|███████████▊                                                                                                | 80/733 [00:05<00:41, 15.92it/s]

Processing regions:  11%|████████████                                                                                                | 82/733 [00:05<00:40, 15.88it/s]

Processing regions:  11%|████████████▍                                                                                               | 84/733 [00:05<00:40, 15.86it/s]

Processing regions:  12%|████████████▋                                                                                               | 86/733 [00:05<00:40, 15.82it/s]

Processing regions:  12%|████████████▉                                                                                               | 88/733 [00:05<00:40, 15.81it/s]

Processing regions:  12%|█████████████▎                                                                                              | 90/733 [00:05<00:40, 15.90it/s]

Processing regions:  13%|█████████████▌                                                                                              | 92/733 [00:05<00:40, 15.90it/s]

Processing regions:  13%|█████████████▊                                                                                              | 94/733 [00:05<00:40, 15.91it/s]

Processing regions:  13%|██████████████▏                                                                                             | 96/733 [00:06<00:40, 15.79it/s]

Processing regions:  13%|██████████████▍                                                                                             | 98/733 [00:06<00:40, 15.81it/s]

Processing regions:  14%|██████████████▌                                                                                            | 100/733 [00:06<00:39, 15.91it/s]

Processing regions:  14%|██████████████▉                                                                                            | 102/733 [00:06<00:39, 15.92it/s]

Processing regions:  14%|███████████████▏                                                                                           | 104/733 [00:06<00:39, 16.01it/s]

Processing regions:  14%|███████████████▍                                                                                           | 106/733 [00:06<00:38, 16.09it/s]

Processing regions:  15%|███████████████▊                                                                                           | 108/733 [00:06<00:38, 16.14it/s]

Processing regions:  15%|████████████████                                                                                           | 110/733 [00:06<00:39, 15.96it/s]

Processing regions:  15%|████████████████▎                                                                                          | 112/733 [00:07<00:39, 15.78it/s]

Processing regions:  16%|████████████████▋                                                                                          | 114/733 [00:07<00:39, 15.68it/s]

Processing regions:  16%|████████████████▉                                                                                          | 116/733 [00:07<00:39, 15.82it/s]

Processing regions:  16%|█████████████████▏                                                                                         | 118/733 [00:07<00:38, 15.84it/s]

Processing regions:  16%|█████████████████▌                                                                                         | 120/733 [00:07<00:38, 15.92it/s]

Processing regions:  17%|█████████████████▊                                                                                         | 122/733 [00:07<00:38, 16.01it/s]

Processing regions:  17%|██████████████████                                                                                         | 124/733 [00:07<00:37, 16.06it/s]

Processing regions:  17%|██████████████████▍                                                                                        | 126/733 [00:07<00:37, 16.00it/s]

Processing regions:  17%|██████████████████▋                                                                                        | 128/733 [00:08<00:38, 15.88it/s]

Processing regions:  18%|██████████████████▉                                                                                        | 130/733 [00:08<00:37, 15.93it/s]

Processing regions:  18%|███████████████████▎                                                                                       | 132/733 [00:08<00:37, 15.98it/s]

Processing regions:  18%|███████████████████▌                                                                                       | 134/733 [00:08<00:37, 16.01it/s]

Processing regions:  19%|███████████████████▊                                                                                       | 136/733 [00:08<00:37, 16.06it/s]

Processing regions:  19%|████████████████████▏                                                                                      | 138/733 [00:08<00:37, 16.03it/s]

Processing regions:  19%|████████████████████▍                                                                                      | 140/733 [00:08<00:36, 16.08it/s]

Processing regions:  19%|████████████████████▋                                                                                      | 142/733 [00:08<00:36, 15.99it/s]

Processing regions:  20%|█████████████████████                                                                                      | 144/733 [00:09<00:37, 15.88it/s]

Processing regions:  20%|█████████████████████▎                                                                                     | 146/733 [00:09<00:37, 15.77it/s]

Processing regions:  20%|█████████████████████▌                                                                                     | 148/733 [00:09<00:36, 15.88it/s]

Processing regions:  20%|█████████████████████▉                                                                                     | 150/733 [00:09<00:36, 16.00it/s]

Processing regions:  21%|██████████████████████▏                                                                                    | 152/733 [00:09<00:36, 16.00it/s]

Processing regions:  21%|██████████████████████▍                                                                                    | 154/733 [00:09<00:36, 16.03it/s]

Processing regions:  21%|██████████████████████▊                                                                                    | 156/733 [00:09<00:35, 16.12it/s]

Processing regions:  22%|███████████████████████                                                                                    | 158/733 [00:09<00:35, 15.98it/s]

Processing regions:  22%|███████████████████████▎                                                                                   | 160/733 [00:10<00:36, 15.90it/s]

Processing regions:  22%|███████████████████████▋                                                                                   | 162/733 [00:10<00:36, 15.82it/s]

Processing regions:  22%|███████████████████████▉                                                                                   | 164/733 [00:10<00:35, 15.88it/s]

Processing regions:  23%|████████████████████████▏                                                                                  | 166/733 [00:10<00:35, 15.89it/s]

Processing regions:  23%|████████████████████████▌                                                                                  | 168/733 [00:10<00:35, 15.91it/s]

Processing regions:  23%|████████████████████████▊                                                                                  | 170/733 [00:10<00:35, 15.88it/s]

Processing regions:  23%|█████████████████████████                                                                                  | 172/733 [00:10<00:35, 15.87it/s]

Processing regions:  24%|█████████████████████████▍                                                                                 | 174/733 [00:10<00:35, 15.86it/s]

Processing regions:  24%|█████████████████████████▋                                                                                 | 176/733 [00:11<00:35, 15.80it/s]

Processing regions:  24%|█████████████████████████▉                                                                                 | 178/733 [00:11<00:35, 15.78it/s]

Processing regions:  25%|██████████████████████████▎                                                                                | 180/733 [00:11<00:34, 15.87it/s]

Processing regions:  25%|██████████████████████████▌                                                                                | 182/733 [00:11<00:34, 15.84it/s]

Processing regions:  25%|██████████████████████████▊                                                                                | 184/733 [00:11<00:34, 15.91it/s]

Processing regions:  25%|███████████████████████████▏                                                                               | 186/733 [00:11<00:34, 15.91it/s]

Processing regions:  26%|███████████████████████████▍                                                                               | 188/733 [00:11<00:34, 15.97it/s]

Processing regions:  26%|███████████████████████████▋                                                                               | 190/733 [00:11<00:33, 15.98it/s]

Processing regions:  26%|████████████████████████████                                                                               | 192/733 [00:12<00:33, 15.92it/s]

Processing regions:  26%|████████████████████████████▎                                                                              | 194/733 [00:12<00:34, 15.73it/s]

Processing regions:  27%|████████████████████████████▌                                                                              | 196/733 [00:12<00:34, 15.70it/s]

Processing regions:  27%|████████████████████████████▉                                                                              | 198/733 [00:12<00:34, 15.65it/s]

Processing regions:  27%|█████████████████████████████▏                                                                             | 200/733 [00:12<00:33, 15.72it/s]

Processing regions:  28%|█████████████████████████████▍                                                                             | 202/733 [00:12<00:33, 15.82it/s]

Processing regions:  28%|█████████████████████████████▊                                                                             | 204/733 [00:12<00:33, 15.79it/s]

Processing regions:  28%|██████████████████████████████                                                                             | 206/733 [00:13<00:33, 15.90it/s]

Processing regions:  28%|██████████████████████████████▎                                                                            | 208/733 [00:13<00:33, 15.80it/s]

Processing regions:  29%|██████████████████████████████▋                                                                            | 210/733 [00:13<00:33, 15.79it/s]

Processing regions:  29%|██████████████████████████████▉                                                                            | 212/733 [00:13<00:32, 15.89it/s]

Processing regions:  29%|███████████████████████████████▏                                                                           | 214/733 [00:13<00:32, 15.92it/s]

Processing regions:  29%|███████████████████████████████▌                                                                           | 216/733 [00:13<00:32, 15.96it/s]

Processing regions:  30%|███████████████████████████████▊                                                                           | 218/733 [00:13<00:32, 16.00it/s]

Processing regions:  30%|████████████████████████████████                                                                           | 220/733 [00:13<00:32, 15.97it/s]

Processing regions:  30%|████████████████████████████████▍                                                                          | 222/733 [00:14<00:32, 15.88it/s]

Processing regions:  31%|████████████████████████████████▋                                                                          | 224/733 [00:14<00:32, 15.61it/s]

Processing regions:  31%|████████████████████████████████▉                                                                          | 226/733 [00:14<00:33, 15.29it/s]

Processing regions:  31%|█████████████████████████████████▎                                                                         | 228/733 [00:14<00:32, 15.40it/s]

Processing regions:  31%|█████████████████████████████████▌                                                                         | 230/733 [00:14<00:32, 15.53it/s]

Processing regions:  32%|█████████████████████████████████▊                                                                         | 232/733 [00:14<00:31, 15.70it/s]

Processing regions:  32%|██████████████████████████████████▏                                                                        | 234/733 [00:14<00:31, 15.79it/s]

Processing regions:  32%|██████████████████████████████████▍                                                                        | 236/733 [00:14<00:31, 15.69it/s]

Processing regions:  32%|██████████████████████████████████▋                                                                        | 238/733 [00:15<00:31, 15.79it/s]

Processing regions:  33%|███████████████████████████████████                                                                        | 240/733 [00:15<00:31, 15.67it/s]

Processing regions:  33%|███████████████████████████████████▎                                                                       | 242/733 [00:15<00:31, 15.72it/s]

Processing regions:  33%|███████████████████████████████████▌                                                                       | 244/733 [00:15<00:30, 15.86it/s]

Processing regions:  34%|███████████████████████████████████▉                                                                       | 246/733 [00:15<00:30, 15.86it/s]

Processing regions:  34%|████████████████████████████████████▏                                                                      | 248/733 [00:15<00:30, 15.94it/s]

Processing regions:  34%|████████████████████████████████████▍                                                                      | 250/733 [00:15<00:30, 16.01it/s]

Processing regions:  34%|████████████████████████████████████▊                                                                      | 252/733 [00:15<00:30, 15.74it/s]

Processing regions:  35%|█████████████████████████████████████                                                                      | 254/733 [00:16<00:30, 15.52it/s]

Processing regions:  35%|█████████████████████████████████████▎                                                                     | 256/733 [00:16<00:31, 15.37it/s]

Processing regions:  35%|█████████████████████████████████████▋                                                                     | 258/733 [00:16<00:30, 15.54it/s]

Processing regions:  35%|█████████████████████████████████████▉                                                                     | 260/733 [00:16<00:30, 15.66it/s]

Processing regions:  36%|██████████████████████████████████████▏                                                                    | 262/733 [00:16<00:29, 15.76it/s]

Processing regions:  36%|██████████████████████████████████████▌                                                                    | 264/733 [00:16<00:29, 15.74it/s]

Processing regions:  36%|██████████████████████████████████████▊                                                                    | 266/733 [00:16<00:29, 15.91it/s]

Processing regions:  37%|███████████████████████████████████████                                                                    | 268/733 [00:16<00:29, 15.85it/s]

Processing regions:  37%|███████████████████████████████████████▍                                                                   | 270/733 [00:17<00:29, 15.94it/s]

Processing regions:  37%|███████████████████████████████████████▋                                                                   | 272/733 [00:17<00:29, 15.81it/s]

Processing regions:  37%|███████████████████████████████████████▉                                                                   | 274/733 [00:17<00:28, 15.87it/s]

Processing regions:  38%|████████████████████████████████████████▎                                                                  | 276/733 [00:17<00:28, 15.87it/s]

Processing regions:  38%|████████████████████████████████████████▌                                                                  | 278/733 [00:17<00:29, 15.68it/s]

Processing regions:  38%|████████████████████████████████████████▊                                                                  | 280/733 [00:17<00:28, 15.67it/s]

Processing regions:  38%|█████████████████████████████████████████▏                                                                 | 282/733 [00:17<00:28, 15.74it/s]

Processing regions:  39%|█████████████████████████████████████████▍                                                                 | 284/733 [00:17<00:28, 15.71it/s]

Processing regions:  39%|█████████████████████████████████████████▋                                                                 | 286/733 [00:18<00:28, 15.88it/s]

Processing regions:  39%|██████████████████████████████████████████                                                                 | 288/733 [00:18<00:28, 15.73it/s]

Processing regions:  40%|██████████████████████████████████████████▎                                                                | 290/733 [00:18<00:28, 15.79it/s]

Processing regions:  40%|██████████████████████████████████████████▌                                                                | 292/733 [00:18<00:27, 15.87it/s]

Processing regions:  40%|██████████████████████████████████████████▉                                                                | 294/733 [00:18<00:27, 15.90it/s]

Processing regions:  40%|███████████████████████████████████████████▏                                                               | 296/733 [00:18<00:27, 15.92it/s]

Processing regions:  41%|███████████████████████████████████████████▌                                                               | 298/733 [00:18<00:27, 15.97it/s]

Processing regions:  41%|███████████████████████████████████████████▊                                                               | 300/733 [00:18<00:27, 15.96it/s]

Processing regions:  41%|████████████████████████████████████████████                                                               | 302/733 [00:19<00:27, 15.95it/s]

Processing regions:  41%|████████████████████████████████████████████▍                                                              | 304/733 [00:19<00:27, 15.85it/s]

Processing regions:  42%|████████████████████████████████████████████▋                                                              | 306/733 [00:19<00:27, 15.64it/s]

Processing regions:  42%|████████████████████████████████████████████▉                                                              | 308/733 [00:19<00:27, 15.41it/s]

Processing regions:  42%|█████████████████████████████████████████████▎                                                             | 310/733 [00:19<00:27, 15.26it/s]

Processing regions:  43%|█████████████████████████████████████████████▌                                                             | 312/733 [00:19<00:27, 15.08it/s]

Processing regions:  43%|█████████████████████████████████████████████▊                                                             | 314/733 [00:19<00:27, 15.02it/s]

Processing regions:  43%|██████████████████████████████████████████████▏                                                            | 316/733 [00:20<00:27, 15.05it/s]

Processing regions:  43%|██████████████████████████████████████████████▍                                                            | 318/733 [00:20<00:27, 14.97it/s]

Processing regions:  44%|██████████████████████████████████████████████▋                                                            | 320/733 [00:20<00:27, 15.15it/s]

Processing regions:  44%|███████████████████████████████████████████████                                                            | 322/733 [00:20<00:26, 15.36it/s]

Processing regions:  44%|███████████████████████████████████████████████▎                                                           | 324/733 [00:20<00:26, 15.58it/s]

Processing regions:  44%|███████████████████████████████████████████████▌                                                           | 326/733 [00:20<00:25, 15.70it/s]

Processing regions:  45%|███████████████████████████████████████████████▉                                                           | 328/733 [00:20<00:25, 15.84it/s]

Processing regions:  45%|████████████████████████████████████████████████▏                                                          | 330/733 [00:20<00:25, 15.80it/s]

Processing regions:  45%|████████████████████████████████████████████████▍                                                          | 332/733 [00:21<00:25, 15.69it/s]

Processing regions:  46%|████████████████████████████████████████████████▊                                                          | 334/733 [00:21<00:25, 15.43it/s]

Processing regions:  46%|█████████████████████████████████████████████████                                                          | 336/733 [00:21<00:25, 15.44it/s]

Processing regions:  46%|█████████████████████████████████████████████████▎                                                         | 338/733 [00:21<00:25, 15.59it/s]

Processing regions:  46%|█████████████████████████████████████████████████▋                                                         | 340/733 [00:21<00:25, 15.63it/s]

Processing regions:  47%|█████████████████████████████████████████████████▉                                                         | 342/733 [00:21<00:24, 15.69it/s]

Processing regions:  47%|██████████████████████████████████████████████████▏                                                        | 344/733 [00:21<00:24, 15.77it/s]

Processing regions:  47%|██████████████████████████████████████████████████▌                                                        | 346/733 [00:21<00:24, 15.84it/s]

Processing regions:  47%|██████████████████████████████████████████████████▊                                                        | 348/733 [00:22<00:24, 15.91it/s]

Processing regions:  48%|███████████████████████████████████████████████████                                                        | 350/733 [00:22<00:24, 15.88it/s]

Processing regions:  48%|███████████████████████████████████████████████████▍                                                       | 352/733 [00:22<00:24, 15.85it/s]

Processing regions:  48%|███████████████████████████████████████████████████▋                                                       | 354/733 [00:22<00:23, 15.87it/s]

Processing regions:  49%|███████████████████████████████████████████████████▉                                                       | 356/733 [00:22<00:23, 15.89it/s]

Processing regions:  49%|████████████████████████████████████████████████████▎                                                      | 358/733 [00:22<00:23, 15.93it/s]

Processing regions:  49%|████████████████████████████████████████████████████▌                                                      | 360/733 [00:22<00:23, 15.71it/s]

Processing regions:  49%|████████████████████████████████████████████████████▊                                                      | 362/733 [00:22<00:24, 15.39it/s]

Processing regions:  50%|█████████████████████████████████████████████████████▏                                                     | 364/733 [00:23<00:23, 15.43it/s]

Processing regions:  50%|█████████████████████████████████████████████████████▍                                                     | 366/733 [00:23<00:23, 15.50it/s]

Processing regions:  50%|█████████████████████████████████████████████████████▋                                                     | 368/733 [00:23<00:23, 15.56it/s]

Processing regions:  50%|██████████████████████████████████████████████████████                                                     | 370/733 [00:23<00:23, 15.68it/s]

Processing regions:  51%|██████████████████████████████████████████████████████▎                                                    | 372/733 [00:23<00:22, 15.76it/s]

Processing regions:  51%|██████████████████████████████████████████████████████▌                                                    | 374/733 [00:23<00:22, 15.81it/s]

Processing regions:  51%|██████████████████████████████████████████████████████▉                                                    | 376/733 [00:23<00:22, 15.94it/s]

Processing regions:  52%|███████████████████████████████████████████████████████▏                                                   | 378/733 [00:23<00:22, 15.95it/s]

Processing regions:  52%|███████████████████████████████████████████████████████▍                                                   | 380/733 [00:24<00:22, 16.01it/s]

Processing regions:  52%|███████████████████████████████████████████████████████▊                                                   | 382/733 [00:24<00:22, 15.81it/s]

Processing regions:  52%|████████████████████████████████████████████████████████                                                   | 384/733 [00:24<00:22, 15.78it/s]

Processing regions:  53%|████████████████████████████████████████████████████████▎                                                  | 386/733 [00:24<00:21, 15.82it/s]

Processing regions:  53%|████████████████████████████████████████████████████████▋                                                  | 388/733 [00:24<00:22, 15.50it/s]

Processing regions:  53%|████████████████████████████████████████████████████████▉                                                  | 390/733 [00:24<00:22, 15.56it/s]

Processing regions:  53%|█████████████████████████████████████████████████████████▏                                                 | 392/733 [00:24<00:21, 15.70it/s]

Processing regions:  54%|█████████████████████████████████████████████████████████▌                                                 | 394/733 [00:24<00:21, 15.73it/s]

Processing regions:  54%|█████████████████████████████████████████████████████████▊                                                 | 396/733 [00:25<00:21, 15.80it/s]

Processing regions:  54%|██████████████████████████████████████████████████████████                                                 | 398/733 [00:25<00:21, 15.71it/s]

Processing regions:  55%|██████████████████████████████████████████████████████████▍                                                | 400/733 [00:25<00:21, 15.76it/s]

Processing regions:  55%|██████████████████████████████████████████████████████████▋                                                | 402/733 [00:25<00:20, 15.78it/s]

Processing regions:  55%|██████████████████████████████████████████████████████████▉                                                | 404/733 [00:25<00:20, 15.85it/s]

Processing regions:  55%|███████████████████████████████████████████████████████████▎                                               | 406/733 [00:25<00:20, 15.95it/s]

Processing regions:  56%|███████████████████████████████████████████████████████████▌                                               | 408/733 [00:25<00:20, 16.03it/s]

Processing regions:  56%|███████████████████████████████████████████████████████████▊                                               | 410/733 [00:25<00:20, 15.91it/s]

Processing regions:  56%|████████████████████████████████████████████████████████████▏                                              | 412/733 [00:26<00:20, 15.88it/s]

Processing regions:  56%|████████████████████████████████████████████████████████████▍                                              | 414/733 [00:26<00:20, 15.89it/s]

Processing regions:  57%|████████████████████████████████████████████████████████████▋                                              | 416/733 [00:26<00:20, 15.79it/s]

Processing regions:  57%|█████████████████████████████████████████████████████████████                                              | 418/733 [00:26<00:19, 15.89it/s]

Processing regions:  57%|█████████████████████████████████████████████████████████████▎                                             | 420/733 [00:26<00:19, 15.89it/s]

Processing regions:  58%|█████████████████████████████████████████████████████████████▌                                             | 422/733 [00:26<00:19, 15.63it/s]

Processing regions:  58%|█████████████████████████████████████████████████████████████▉                                             | 424/733 [00:26<00:20, 15.31it/s]

Processing regions:  58%|██████████████████████████████████████████████████████████████▏                                            | 426/733 [00:27<00:20, 15.21it/s]

Processing regions:  58%|██████████████████████████████████████████████████████████████▍                                            | 428/733 [00:27<00:20, 15.16it/s]

Processing regions:  59%|██████████████████████████████████████████████████████████████▊                                            | 430/733 [00:27<00:20, 15.14it/s]

Processing regions:  59%|███████████████████████████████████████████████████████████████                                            | 432/733 [00:27<00:19, 15.33it/s]

Processing regions:  59%|███████████████████████████████████████████████████████████████▎                                           | 434/733 [00:27<00:19, 15.54it/s]

Processing regions:  59%|███████████████████████████████████████████████████████████████▋                                           | 436/733 [00:27<00:18, 15.74it/s]

Processing regions:  60%|███████████████████████████████████████████████████████████████▉                                           | 438/733 [00:27<00:18, 15.75it/s]

Processing regions:  60%|████████████████████████████████████████████████████████████████▏                                          | 440/733 [00:27<00:18, 15.68it/s]

Processing regions:  60%|████████████████████████████████████████████████████████████████▌                                          | 442/733 [00:28<00:19, 15.20it/s]

Processing regions:  61%|████████████████████████████████████████████████████████████████▊                                          | 444/733 [00:28<00:19, 15.12it/s]

Processing regions:  61%|█████████████████████████████████████████████████████████████████                                          | 446/733 [00:28<00:18, 15.20it/s]

Processing regions:  61%|█████████████████████████████████████████████████████████████████▍                                         | 448/733 [00:28<00:18, 15.49it/s]

Processing regions:  61%|█████████████████████████████████████████████████████████████████▋                                         | 450/733 [00:28<00:18, 15.65it/s]

Processing regions:  62%|█████████████████████████████████████████████████████████████████▉                                         | 452/733 [00:28<00:17, 15.64it/s]

Processing regions:  62%|██████████████████████████████████████████████████████████████████▎                                        | 454/733 [00:28<00:17, 15.72it/s]

Processing regions:  62%|██████████████████████████████████████████████████████████████████▌                                        | 456/733 [00:28<00:17, 15.71it/s]

Processing regions:  62%|██████████████████████████████████████████████████████████████████▊                                        | 458/733 [00:29<00:17, 15.73it/s]

Processing regions:  63%|███████████████████████████████████████████████████████████████████▏                                       | 460/733 [00:29<00:17, 15.88it/s]

Processing regions:  63%|███████████████████████████████████████████████████████████████████▍                                       | 462/733 [00:29<00:17, 15.75it/s]

Processing regions:  63%|███████████████████████████████████████████████████████████████████▋                                       | 464/733 [00:29<00:16, 15.84it/s]

Processing regions:  64%|████████████████████████████████████████████████████████████████████                                       | 466/733 [00:29<00:16, 15.87it/s]

Processing regions:  64%|████████████████████████████████████████████████████████████████████▎                                      | 468/733 [00:29<00:16, 15.78it/s]

Processing regions:  64%|████████████████████████████████████████████████████████████████████▌                                      | 470/733 [00:29<00:16, 15.53it/s]

Processing regions:  64%|████████████████████████████████████████████████████████████████████▉                                      | 472/733 [00:29<00:17, 15.33it/s]

Processing regions:  65%|█████████████████████████████████████████████████████████████████████▏                                     | 474/733 [00:30<00:16, 15.56it/s]

Processing regions:  65%|█████████████████████████████████████████████████████████████████████▍                                     | 476/733 [00:30<00:16, 15.60it/s]

Processing regions:  65%|█████████████████████████████████████████████████████████████████████▊                                     | 478/733 [00:30<00:16, 15.50it/s]

Processing regions:  65%|██████████████████████████████████████████████████████████████████████                                     | 480/733 [00:30<00:16, 15.60it/s]

Processing regions:  66%|██████████████████████████████████████████████████████████████████████▎                                    | 482/733 [00:30<00:15, 15.81it/s]

Processing regions:  66%|██████████████████████████████████████████████████████████████████████▋                                    | 484/733 [00:30<00:15, 15.90it/s]

Processing regions:  66%|██████████████████████████████████████████████████████████████████████▉                                    | 486/733 [00:30<00:15, 15.93it/s]

Processing regions:  67%|███████████████████████████████████████████████████████████████████████▏                                   | 488/733 [00:30<00:15, 15.87it/s]

Processing regions:  67%|███████████████████████████████████████████████████████████████████████▌                                   | 490/733 [00:31<00:15, 15.87it/s]

Processing regions:  67%|███████████████████████████████████████████████████████████████████████▊                                   | 492/733 [00:31<00:15, 16.00it/s]

Processing regions:  67%|████████████████████████████████████████████████████████████████████████                                   | 494/733 [00:31<00:15, 15.75it/s]

Processing regions:  68%|████████████████████████████████████████████████████████████████████████▍                                  | 496/733 [00:31<00:15, 15.75it/s]

Processing regions:  68%|████████████████████████████████████████████████████████████████████████▋                                  | 498/733 [00:31<00:14, 15.80it/s]

Processing regions:  68%|████████████████████████████████████████████████████████████████████████▉                                  | 500/733 [00:31<00:14, 15.68it/s]

Processing regions:  68%|█████████████████████████████████████████████████████████████████████████▎                                 | 502/733 [00:31<00:14, 15.67it/s]

Processing regions:  69%|█████████████████████████████████████████████████████████████████████████▌                                 | 504/733 [00:32<00:14, 15.67it/s]

Processing regions:  69%|█████████████████████████████████████████████████████████████████████████▊                                 | 506/733 [00:32<00:14, 15.78it/s]

Processing regions:  69%|██████████████████████████████████████████████████████████████████████████▏                                | 508/733 [00:32<00:14, 15.74it/s]

Processing regions:  70%|██████████████████████████████████████████████████████████████████████████▍                                | 510/733 [00:32<00:14, 15.64it/s]

Processing regions:  70%|██████████████████████████████████████████████████████████████████████████▋                                | 512/733 [00:32<00:14, 15.58it/s]

Processing regions:  70%|███████████████████████████████████████████████████████████████████████████                                | 514/733 [00:32<00:14, 15.55it/s]

Processing regions:  70%|███████████████████████████████████████████████████████████████████████████▎                               | 516/733 [00:32<00:13, 15.54it/s]

Processing regions:  71%|███████████████████████████████████████████████████████████████████████████▌                               | 518/733 [00:32<00:13, 15.52it/s]

Processing regions:  71%|███████████████████████████████████████████████████████████████████████████▉                               | 520/733 [00:33<00:13, 15.51it/s]

Processing regions:  71%|████████████████████████████████████████████████████████████████████████████▏                              | 522/733 [00:33<00:13, 15.30it/s]

Processing regions:  71%|████████████████████████████████████████████████████████████████████████████▍                              | 524/733 [00:33<00:13, 15.04it/s]

Processing regions:  72%|████████████████████████████████████████████████████████████████████████████▊                              | 526/733 [00:33<00:13, 15.15it/s]

Processing regions:  72%|█████████████████████████████████████████████████████████████████████████████                              | 528/733 [00:33<00:13, 15.42it/s]

Processing regions:  72%|█████████████████████████████████████████████████████████████████████████████▎                             | 530/733 [00:33<00:13, 15.55it/s]

Processing regions:  73%|█████████████████████████████████████████████████████████████████████████████▋                             | 532/733 [00:33<00:12, 15.70it/s]

Processing regions:  73%|█████████████████████████████████████████████████████████████████████████████▉                             | 534/733 [00:33<00:12, 15.76it/s]

Processing regions:  73%|██████████████████████████████████████████████████████████████████████████████▏                            | 536/733 [00:34<00:12, 15.75it/s]

Processing regions:  73%|██████████████████████████████████████████████████████████████████████████████▌                            | 538/733 [00:34<00:12, 15.79it/s]

Processing regions:  74%|██████████████████████████████████████████████████████████████████████████████▊                            | 540/733 [00:34<00:12, 15.78it/s]

Processing regions:  74%|███████████████████████████████████████████████████████████████████████████████                            | 542/733 [00:34<00:12, 15.68it/s]

Processing regions:  74%|███████████████████████████████████████████████████████████████████████████████▍                           | 544/733 [00:34<00:11, 15.78it/s]

Processing regions:  74%|███████████████████████████████████████████████████████████████████████████████▋                           | 546/733 [00:34<00:11, 15.87it/s]

Processing regions:  75%|███████████████████████████████████████████████████████████████████████████████▉                           | 548/733 [00:34<00:11, 15.92it/s]

Processing regions:  75%|████████████████████████████████████████████████████████████████████████████████▎                          | 550/733 [00:34<00:11, 15.53it/s]

Processing regions:  75%|████████████████████████████████████████████████████████████████████████████████▌                          | 552/733 [00:35<00:11, 15.63it/s]

Processing regions:  76%|████████████████████████████████████████████████████████████████████████████████▊                          | 554/733 [00:35<00:11, 15.72it/s]

Processing regions:  76%|█████████████████████████████████████████████████████████████████████████████████▏                         | 556/733 [00:35<00:11, 15.71it/s]

Processing regions:  76%|█████████████████████████████████████████████████████████████████████████████████▍                         | 558/733 [00:35<00:11, 15.63it/s]

Processing regions:  76%|█████████████████████████████████████████████████████████████████████████████████▋                         | 560/733 [00:35<00:11, 15.69it/s]

Processing regions:  77%|██████████████████████████████████████████████████████████████████████████████████                         | 562/733 [00:35<00:10, 15.72it/s]

Processing regions:  77%|██████████████████████████████████████████████████████████████████████████████████▎                        | 564/733 [00:35<00:10, 15.83it/s]

Processing regions:  77%|██████████████████████████████████████████████████████████████████████████████████▌                        | 566/733 [00:35<00:10, 15.43it/s]

Processing regions:  77%|██████████████████████████████████████████████████████████████████████████████████▉                        | 568/733 [00:36<00:10, 15.13it/s]

Processing regions:  78%|███████████████████████████████████████████████████████████████████████████████████▏                       | 570/733 [00:36<00:10, 15.44it/s]

Processing regions:  78%|███████████████████████████████████████████████████████████████████████████████████▍                       | 572/733 [00:36<00:10, 15.52it/s]

Processing regions:  78%|███████████████████████████████████████████████████████████████████████████████████▊                       | 574/733 [00:36<00:10, 15.59it/s]

Processing regions:  79%|████████████████████████████████████████████████████████████████████████████████████                       | 576/733 [00:36<00:10, 15.60it/s]

Processing regions:  79%|████████████████████████████████████████████████████████████████████████████████████▎                      | 578/733 [00:36<00:09, 15.51it/s]

Processing regions:  79%|████████████████████████████████████████████████████████████████████████████████████▋                      | 580/733 [00:36<00:09, 15.47it/s]

Processing regions:  79%|████████████████████████████████████████████████████████████████████████████████████▉                      | 582/733 [00:37<00:09, 15.60it/s]

Processing regions:  80%|█████████████████████████████████████████████████████████████████████████████████████▏                     | 584/733 [00:37<00:09, 15.73it/s]

Processing regions:  80%|█████████████████████████████████████████████████████████████████████████████████████▌                     | 586/733 [00:37<00:09, 15.87it/s]

Processing regions:  80%|█████████████████████████████████████████████████████████████████████████████████████▊                     | 588/733 [00:37<00:09, 15.73it/s]

Processing regions:  80%|██████████████████████████████████████████████████████████████████████████████████████▏                    | 590/733 [00:37<00:09, 15.75it/s]

Processing regions:  81%|██████████████████████████████████████████████████████████████████████████████████████▍                    | 592/733 [00:37<00:08, 15.77it/s]

Processing regions:  81%|██████████████████████████████████████████████████████████████████████████████████████▋                    | 594/733 [00:37<00:08, 15.82it/s]

Processing regions:  81%|███████████████████████████████████████████████████████████████████████████████████████                    | 596/733 [00:37<00:08, 15.81it/s]

Processing regions:  82%|███████████████████████████████████████████████████████████████████████████████████████▎                   | 598/733 [00:38<00:08, 15.91it/s]

Processing regions:  82%|███████████████████████████████████████████████████████████████████████████████████████▌                   | 600/733 [00:38<00:08, 16.04it/s]

Processing regions:  82%|███████████████████████████████████████████████████████████████████████████████████████▉                   | 602/733 [00:38<00:08, 15.96it/s]

Processing regions:  82%|████████████████████████████████████████████████████████████████████████████████████████▏                  | 604/733 [00:38<00:08, 15.77it/s]

Processing regions:  83%|████████████████████████████████████████████████████████████████████████████████████████▍                  | 606/733 [00:38<00:08, 15.78it/s]

Processing regions:  83%|████████████████████████████████████████████████████████████████████████████████████████▊                  | 608/733 [00:38<00:07, 15.89it/s]

Processing regions:  83%|█████████████████████████████████████████████████████████████████████████████████████████                  | 610/733 [00:38<00:07, 15.84it/s]

Processing regions:  83%|█████████████████████████████████████████████████████████████████████████████████████████▎                 | 612/733 [00:38<00:07, 15.84it/s]

Processing regions:  84%|█████████████████████████████████████████████████████████████████████████████████████████▋                 | 614/733 [00:39<00:07, 15.95it/s]

Processing regions:  84%|█████████████████████████████████████████████████████████████████████████████████████████▉                 | 616/733 [00:39<00:07, 16.05it/s]

Processing regions:  84%|██████████████████████████████████████████████████████████████████████████████████████████▏                | 618/733 [00:39<00:07, 16.07it/s]

Processing regions:  85%|██████████████████████████████████████████████████████████████████████████████████████████▌                | 620/733 [00:39<00:07, 15.95it/s]

Processing regions:  85%|██████████████████████████████████████████████████████████████████████████████████████████▊                | 622/733 [00:39<00:06, 15.93it/s]

Processing regions:  85%|███████████████████████████████████████████████████████████████████████████████████████████                | 624/733 [00:39<00:06, 15.94it/s]

Processing regions:  85%|███████████████████████████████████████████████████████████████████████████████████████████▍               | 626/733 [00:39<00:06, 15.93it/s]

Processing regions:  86%|███████████████████████████████████████████████████████████████████████████████████████████▋               | 628/733 [00:39<00:06, 15.80it/s]

Processing regions:  86%|███████████████████████████████████████████████████████████████████████████████████████████▉               | 630/733 [00:40<00:06, 15.74it/s]

Processing regions:  86%|████████████████████████████████████████████████████████████████████████████████████████████▎              | 632/733 [00:40<00:06, 15.81it/s]

Processing regions:  86%|████████████████████████████████████████████████████████████████████████████████████████████▌              | 634/733 [00:40<00:06, 15.86it/s]

Processing regions:  87%|████████████████████████████████████████████████████████████████████████████████████████████▊              | 636/733 [00:40<00:06, 15.76it/s]

Processing regions:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▏             | 638/733 [00:40<00:05, 15.88it/s]

Processing regions:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▍             | 640/733 [00:40<00:05, 15.95it/s]

Processing regions:  88%|█████████████████████████████████████████████████████████████████████████████████████████████▋             | 642/733 [00:40<00:05, 15.91it/s]

Processing regions:  88%|██████████████████████████████████████████████████████████████████████████████████████████████             | 644/733 [00:40<00:05, 15.79it/s]

Processing regions:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▎            | 646/733 [00:41<00:05, 15.77it/s]

Processing regions:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▌            | 648/733 [00:41<00:05, 15.84it/s]

Processing regions:  89%|██████████████████████████████████████████████████████████████████████████████████████████████▉            | 650/733 [00:41<00:05, 15.98it/s]

Processing regions:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▏           | 652/733 [00:41<00:05, 15.78it/s]

Processing regions:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▍           | 654/733 [00:41<00:05, 15.77it/s]

Processing regions:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▊           | 656/733 [00:41<00:04, 15.71it/s]

Processing regions:  90%|████████████████████████████████████████████████████████████████████████████████████████████████           | 658/733 [00:41<00:04, 15.89it/s]

Processing regions:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▎          | 660/733 [00:41<00:04, 15.92it/s]

Processing regions:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▋          | 662/733 [00:42<00:04, 15.91it/s]

Processing regions:  91%|████████████████████████████████████████████████████████████████████████████████████████████████▉          | 664/733 [00:42<00:04, 15.90it/s]

Processing regions:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▏         | 666/733 [00:42<00:04, 15.97it/s]

Processing regions:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▌         | 668/733 [00:42<00:04, 15.81it/s]

Processing regions:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▊         | 670/733 [00:42<00:03, 15.79it/s]

Processing regions:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████         | 672/733 [00:42<00:03, 15.78it/s]

Processing regions:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▍        | 674/733 [00:42<00:03, 15.81it/s]

Processing regions:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▋        | 676/733 [00:42<00:03, 15.87it/s]

Processing regions:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▉        | 678/733 [00:43<00:03, 15.91it/s]

Processing regions:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▎       | 680/733 [00:43<00:03, 15.92it/s]

Processing regions:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▌       | 682/733 [00:43<00:03, 15.84it/s]

Processing regions:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▊       | 684/733 [00:43<00:03, 15.65it/s]

Processing regions:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 686/733 [00:43<00:03, 15.38it/s]

Processing regions:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 688/733 [00:43<00:02, 15.11it/s]

Processing regions:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 690/733 [00:43<00:02, 15.10it/s]

Processing regions:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████      | 692/733 [00:43<00:02, 15.31it/s]

Processing regions:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 694/733 [00:44<00:02, 15.45it/s]

Processing regions:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 696/733 [00:44<00:02, 15.59it/s]

Processing regions:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 698/733 [00:44<00:02, 15.65it/s]

Processing regions:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 700/733 [00:44<00:02, 15.48it/s]

Processing regions:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 702/733 [00:44<00:01, 15.62it/s]

Processing regions:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 704/733 [00:44<00:01, 15.70it/s]

Processing regions:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████    | 706/733 [00:44<00:01, 15.85it/s]

Processing regions:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 708/733 [00:44<00:01, 15.76it/s]

Processing regions:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 710/733 [00:45<00:01, 15.83it/s]

Processing regions:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 712/733 [00:45<00:01, 15.92it/s]

Processing regions:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 714/733 [00:45<00:01, 15.85it/s]

Processing regions:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 716/733 [00:45<00:01, 15.64it/s]

Processing regions:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 718/733 [00:45<00:00, 15.75it/s]

Processing regions:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████  | 720/733 [00:45<00:00, 15.81it/s]

Processing regions:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 722/733 [00:45<00:00, 15.79it/s]

Processing regions:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 724/733 [00:45<00:00, 15.75it/s]

Processing regions:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 726/733 [00:46<00:00, 15.81it/s]

Processing regions:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 728/733 [00:46<00:00, 15.92it/s]

Processing regions: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 730/733 [00:46<00:00, 15.90it/s]

Processing regions: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 732/733 [00:46<00:00, 15.71it/s]

Processing regions: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 733/733 [00:46<00:00, 15.74it/s]

,region_id,npix_region,npix_edge_ring,F_Halpha_sum,F_Halpha_e_sum,SNR_Halpha_sum,Halpha_b_edge,F_Hbeta_sum,F_Hbeta_e_sum,SNR_Hbeta_sum,...,SNR_[SII]6731_sum,[SII]6731_b_edge,F_[NII]6583_sum,F_[NII]6583_e_sum,SNR_[NII]6583_sum,[NII]6583_b_edge,F_[OII]3727_sum,F_[OII]3727_e_sum,SNR_[OII]3727_sum,[OII]3727_b_edge
0,1,69,43,9.487527e-16,5.467802e-17,17.351631,1.433092e-17,3.652461e-16,4.446916e-17,8.213469,...,2.287411,9.474347e-19,2.686533e-16,4.047625e-17,6.637306,4.058979e-18,7.986386e-16,4.310828e-17,18.526340,1.265083e-17
1,2,301,66,1.301978e-14,1.176064e-16,110.706362,4.492848e-17,4.051028e-15,9.650859e-17,41.975825,...,27.644117,8.090437e-18,2.932653e-15,7.883125e-17,37.201663,1.043259e-17,9.549779e-15,9.067182e-17,105.322455,3.157054e-17
2,3,598,104,5.241132e-14,1.621037e-16,323.319710,6.942703e-17,1.395986e-14,1.437770e-16,97.093840,...,64.214535,1.139595e-17,1.212800e-14,1.109718e-16,109.289063,1.648080e-17,4.253990e-14,1.410250e-16,301.647824,5.949831e-17
3,4,145,50,5.923150e-15,8.233364e-17,71.940827,3.727495e-17,1.686315e-15,7.091012e-17,23.781017,...,17.471425,6.718761e-18,1.450545e-15,5.522511e-17,26.266042,9.448268e-18,3.603165e-15,6.641304e-17,54.253879,2.420688e-17
4,5,247,56,2.379882e-14,1.020247e-16,233.265332,6.409070e-17,5.118345e-15,9.029885e-17,56.682289,...,41.729927,8.791292e-18,5.165732e-15,6.853113e-17,75.377883,1.432051e-17,1.063654e-14,8.625711e-17,123.311988,3.194309e-17

In [10]:
# Any regions with empty masks?
print("Regions with npix_region == 0:", (flux_catalog_df["npix_region"] == 0).sum())

# Any maps with NaN b_edge because the ring had no valid pixels?
for name in maps:
    n_nan = flux_catalog_df[f"{name}_b_edge"].isna().sum()
    print(f"{name}: NaN edge backgrounds = {n_nan}")

# # Show some SNR stats
# for name in maps:
#     print(name, "SNR_bgsub median:", np.nanmedian(flux_catalog_df[f"{name}_SNR_bgsub"]))

Regions with npix_region == 0: 0
Halpha: NaN edge backgrounds = 0
Hbeta: NaN edge backgrounds = 0
[OIII]5007: NaN edge backgrounds = 0
[SII]6716: NaN edge backgrounds = 0
[SII]6731: NaN edge backgrounds = 0
[NII]6583: NaN edge backgrounds = 0
[OII]3727: NaN edge backgrounds = 0

In [11]:
# Reset indices to guarantee alignment by row order
flux_df  = flux_catalog_df.reset_index(drop=True)
peaks_df2 = peaks_df.reset_index(drop=True)
boundary_df2 = boundary_metric_df.reset_index(drop=True)

# Concatenate column-wise
merged_df = pd.concat([flux_df, peaks_df2, boundary_df2, int_flux_df], axis=1)

# Remove duplicate column names (keep first occurrence)
merged_df = merged_df.loc[:, ~merged_df.columns.duplicated()]

merged_df.head()

,region_id,npix_region,npix_edge_ring,F_Halpha_sum,F_Halpha_e_sum,SNR_Halpha_sum,Halpha_b_edge,F_Hbeta_sum,F_Hbeta_e_sum,SNR_Hbeta_sum,...,radius_p16_pc,radius_p50_pc,radius_p84_pc,radius_areaeq_px,radius_areaeq_pc,boundary_method,area_px_after_carve,radius_areaeq_px_after_carve,radius_areaeq_pc_after_carve,id_int
0,1.0,69.0,43.0,9.487527e-16,5.467802e-17,17.351631,1.433092e-17,3.652461e-16,4.446916e-17,8.213469,...,2.891870,4.799533,8.399556,4.686511,6.041330,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,69.0,4.686511,6.041330,0
1,2.0,301.0,66.0,1.301978e-14,1.176064e-16,110.706362,4.492848e-17,4.051028e-15,9.650859e-17,41.975825,...,3.437571,14.855218,15.846033,9.788323,12.618022,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,301.0,9.788323,12.618022,1
2,3.0,598.0,104.0,5.241132e-14,1.621037e-16,323.319710,6.942703e-17,1.395986e-14,1.437770e-16,97.093840,...,3.437571,20.105258,28.718630,13.796714,17.785195,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,598.0,13.796714,17.785195,2
3,4.0,145.0,50.0,5.923150e-15,8.233364e-17,71.940827,3.727495e-17,1.686315e-15,7.091012e-17,23.781017,...,6.875142,7.734535,10.312714,6.793742,8.757740,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,145.0,6.793742,8.757740,3
4,5.0,247.0,56.0,2.379882e-14,1.020247e-16,233.265332,6.409070e-17,5.118345e-15,9.029885e-17,56.682289,...,7.116357,11.397198,15.101528,8.866935,11.430270,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,247.0,8.866935,11.430270,4

In [12]:
for col in merged_df.columns:
    print(col)

region_id
npix_region
npix_edge_ring
F_Halpha_sum
F_Halpha_e_sum
SNR_Halpha_sum
Halpha_b_edge
F_Hbeta_sum
F_Hbeta_e_sum
SNR_Hbeta_sum
Hbeta_b_edge
F_[OIII]5007_sum
F_[OIII]5007_e_sum
SNR_[OIII]5007_sum
[OIII]5007_b_edge
F_[SII]6716_sum
F_[SII]6716_e_sum
SNR_[SII]6716_sum
[SII]6716_b_edge
F_[SII]6731_sum
F_[SII]6731_e_sum
SNR_[SII]6731_sum
[SII]6731_b_edge
F_[NII]6583_sum
F_[NII]6583_e_sum
SNR_[NII]6583_sum
[NII]6583_b_edge
F_[OII]3727_sum
F_[OII]3727_e_sum
SNR_[OII]3727_sum
[OII]3727_b_edge
field
y
x
removed_by_saddle
removed_by_edge
kind
center_x_px
center_y_px
zoi_center_label
bg_local
sigma_local
radius_p16_px
radius_p50_px
radius_p84_px
radius_p16_pc
radius_p50_pc
radius_p84_pc
radius_areaeq_px
radius_areaeq_pc
boundary_method
area_px_after_carve
radius_areaeq_px_after_carve
radius_areaeq_pc_after_carve
id_int

<span id="papermill-error-cell" style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">Execution using papermill encountered an exception here and stopped:</span>

In [13]:
# === Extinction (E(B-V), A_V) + dereddening for BOTH raw and bgsub fluxes, plus RA/Dec, R_gal, and BPT classes ===

import numpy as np
import pandas as pd

from astropy.wcs import WCS
from astropy.coordinates import SkyCoord, SkyOffsetFrame
import astropy.units as u

# -----------------------------
# 0) User-tunable parameters
# -----------------------------
INTRINSIC_HA_HB = 2.86
R_V = 3.1

# M33 geometry (EDIT if you use different values)
M33_CENTER = SkyCoord("01h33m50.9s", "+30d39m36.8s", frame="icrs")
M33_INCL = np.deg2rad(56.0)   # radians
M33_PA   = np.deg2rad(23.0)   # radians (E of N)
M33_D_KPC = 840.0             # distance in kpc

ASSUME_1_BASED_PIXELS = False  # set True if peaks x/y are 1-based (DS9 style)

# Integrated error column suffix
ERR_SUFFIX = "_e"

# Lines and wavelengths (Angstrom)
LINE_WAVES = {
    "Hbeta":       4861.0,
    "[OIII]5007": 5007.0,
    "Halpha":       6563.0,
    "[NII]6583":  6584.0,
    "[SII]6716":  6716.0,
    "[SII]6731":  6731.0,
    "[OII]3727":  3727.0,
}

# -----------------------------
# 1) CCM89 extinction curve: k(lambda) = A(lambda) / E(B-V)
# -----------------------------
def ccm89_k_lambda(wave_angstrom, R_V=3.1):
    wave_micron = wave_angstrom * 1e-4  # Å -> μm
    x = 1.0 / wave_micron               # inverse microns

    # Optical/NIR: 1.1 <= x <= 3.3
    y = x - 1.82
    a = (1
         + 0.17699 * y
         - 0.50447 * y**2
         - 0.02427 * y**3
         + 0.72085 * y**4
         + 0.01979 * y**5
         - 0.77530 * y**6
         + 0.32999 * y**7)
    b = (1.41338 * y
         + 2.28305 * y**2
         + 1.07233 * y**3
         - 5.38434 * y**4
         - 0.62251 * y**5
         + 5.30260 * y**6
         - 2.09002 * y**7)
    return a * R_V + b

k_Ha = ccm89_k_lambda(6563.0, R_V=R_V)
k_Hb = ccm89_k_lambda(4861.0, R_V=R_V)
delta_k = k_Hb - k_Ha
ln10 = np.log(10.0)

# -----------------------------
# 2) Helper: compute EBV/AV + deredden for a given flux suffix
#    This runs twice: once for _F_raw and once for _F_bgsub
# -----------------------------
def add_extinction_and_deredden(df, flux_suffix, prefix):
    """
    Computes E(B-V), A_V from Ha/Hb using:
      Ha = df[f"Halpha{flux_suffix}"], Hb = df[f"Hbeta{flux_suffix}"]
    Uses integrated uncertainties:
      eHa = df[f"Halpha{ERR_SUFFIX}"], eHb = df[f"Hbeta{ERR_SUFFIX}"]

    Outputs (examples for prefix='raw'):
      raw_Ha_Hb_obs, raw_E_BV, raw_A_V, raw_Halpha_F_dered, raw_Halpha_sigma_F_dered, ...
      raw_log_NII_Ha, raw_log_OIII_Hb, raw_BPT_class
    """
    # --- Balmer decrement ---
    Ha  = df[f"F_Halpha{flux_suffix}"].to_numpy(dtype=float)
    Hb  = df[f"F_Hbeta{flux_suffix}"].to_numpy(dtype=float)
    eHa = df[f"F_Halpha{ERR_SUFFIX}{flux_suffix}"].to_numpy(dtype=float)
    eHb = df[f"F_Hbeta{ERR_SUFFIX}{flux_suffix}"].to_numpy(dtype=float)

    good = np.isfinite(Ha) & np.isfinite(Hb) & np.isfinite(eHa) & np.isfinite(eHb) & (Ha > 0) & (Hb > 0) & (eHa >= 0) & (eHb >= 0)

    ratio = np.full(len(df), np.nan, dtype=float)
    ratio_err = np.full(len(df), np.nan, dtype=float)

    ratio[good] = Ha[good] / Hb[good]
    ratio_err[good] = ratio[good] * np.sqrt((eHa[good]/Ha[good])**2 + (eHb[good]/Hb[good])**2)

    with np.errstate(divide="ignore", invalid="ignore"):
        ebv = (2.5 / delta_k) * np.log10(ratio / INTRINSIC_HA_HB)

    # Clip negative extinction to 0 (common practical choice)
    ebv = np.where(np.isfinite(ebv), ebv, np.nan)
    ebv = np.clip(ebv, 0, None)

    # Uncertainty propagation: dE/dR = (2.5/delta_k)/(ln10 * R)
    A = (2.5 / delta_k)
    with np.errstate(divide="ignore", invalid="ignore"):
        dE_dR = A / (ln10 * ratio)
        ebv_err = np.abs(dE_dR) * ratio_err

    Av = R_V * ebv
    Av_err = R_V * ebv_err

    df[f"{prefix}_Ha_Hb_obs"] = ratio
    df[f"{prefix}_Ha_Hb_obs_err"] = ratio_err
    df[f"{prefix}_E_BV"] = ebv
    df[f"{prefix}_E_BV_err"] = ebv_err
    df[f"{prefix}_A_V"] = Av
    df[f"{prefix}_A_V_err"] = Av_err

    # --- Deredden all lines ---
    E = ebv
    eE = ebv_err

    for line, wave in LINE_WAVES.items():
        
        Fcol = f"F_{line}{flux_suffix}"
        ecol = f"F_{line}{ERR_SUFFIX}{flux_suffix}"
        if (Fcol not in df.columns) or (ecol not in df.columns):
            continue

        F = df[Fcol].to_numpy(dtype=float)
        eF = df[ecol].to_numpy(dtype=float)

        k = ccm89_k_lambda(wave, R_V=R_V)
        C = 10.0 ** (0.4 * E * k)
        F_dered = F * C

        # sigma(F_dered)^2 = (C*sigma_F)^2 + (F * dC/dE * sigma_E)^2
        dC_dE = C * (0.4 * ln10 * k)
        eF_dered = np.sqrt((C * eF)**2 + (F * dC_dE * eE)**2)

        df[f"F_{line}_{prefix}_dered"] = F_dered
        df[f"F_{line}_e_{prefix}_dered"] = eF_dered

    # --- BPT classification using DEREDDENED fluxes for this prefix ---
    nii  = df.get(f"F_[NII]6583_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    nii_err = df.get(f"F_[NII]6583_e_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    ha0  = df.get(f"F_Halpha_{prefix}_dered",      pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    ha0_err = df.get(f"F_Halpha_e_{prefix}_dered",      pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    oiii = df.get(f"F_[OIII]5007_{prefix}_dered",pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    oiii_err = df.get(f"F_[OIII]5007_e_{prefix}_dered",pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    hb0  = df.get(f"F_Hbeta_{prefix}_dered",      pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    hb_err = df.get(f"F_Hbeta_e_{prefix}_dered",      pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    sii = df.get(f"F_[SII]6716_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float) + \
          df.get(f"F_[SII]6731_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    sii_err = np.sqrt(df.get(f"F_[SII]6716_e_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)**2 +
                      df.get(f"F_[SII]6731_e_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)**2)
    good_bpt = np.isfinite(nii) & np.isfinite(ha0) & np.isfinite(oiii) & np.isfinite(hb0) & (nii > 0) & (ha0 > 0) & (oiii > 0) & (hb0 > 0)
    print(f"{prefix}: {np.sum(good_bpt)} valid points for BPT classification")
    
    log_NII_Ha = np.full(len(df), np.nan, dtype=float)
    log_OIII_Hb = np.full(len(df), np.nan, dtype=float)
    log_SII_Ha = np.full(len(df), np.nan, dtype=float)
    log_NII_Ha[good_bpt] = np.log10(nii[good_bpt] / ha0[good_bpt])
    log_OIII_Hb[good_bpt] = np.log10(oiii[good_bpt] / hb0[good_bpt])
    log_SII_Ha[good_bpt] = np.log10(sii[good_bpt] / ha0[good_bpt])
    
    # #also add error in ratios for plotting
    log_NII_Ha_err = np.full(len(df), np.nan, dtype=float)
    log_OIII_Hb_err = np.full(len(df), np.nan, dtype=float)
    log_SII_Ha_err = np.full(len(df), np.nan, dtype=float)
    log_NII_Ha_err[good_bpt] = np.sqrt((nii_err[good_bpt] / nii[good_bpt])**2 + (ha0_err[good_bpt] / ha0[good_bpt])**2) / np.log(10)
    log_OIII_Hb_err[good_bpt] = np.sqrt((oiii_err[good_bpt] / oiii[good_bpt])**2 + (hb_err[good_bpt] / hb0[good_bpt])**2) / np.log(10)
    log_SII_Ha_err[good_bpt] = np.sqrt((sii_err[good_bpt] / sii[good_bpt])**2 + (ha0_err[good_bpt] / ha0[good_bpt])**2) / np.log(10)

    xB = log_NII_Ha
    yB = log_OIII_Hb

    kewley_y = 0.61 / (xB - 0.47) + 1.19
    kauff_y  = 0.61 / (xB - 0.05) + 1.30

    bpt_class = np.full(len(df), "Unclassified", dtype=object)
    finite = np.isfinite(xB) & np.isfinite(yB)
    bpt_class[finite & (yB < kauff_y)] = "Star-forming"
    bpt_class[finite & (yB >= kauff_y) & (yB < kewley_y)] = "Composite"
    bpt_class[finite & (yB >= kewley_y)] = "AGN/Shock"

    df[f"log_NII_Ha_{prefix}_dered"] = log_NII_Ha
    df[f"log_NII_Ha_err_{prefix}_dered"] = log_NII_Ha_err
    df[f"log_OIII_Hb_{prefix}_dered"] = log_OIII_Hb
    df[f"log_OIII_Hb_err_{prefix}_dered"] = log_OIII_Hb_err
    df[f"log_SII_Ha_{prefix}_dered"] = log_SII_Ha
    df[f"log_SII_Ha_err_{prefix}_dered"] = log_SII_Ha_err
    df[f"BPT_class_{prefix}_dered"] = bpt_class

    return df

# -----------------------------
# 3) Run on BOTH raw and integrated fluxes
# -----------------------------
df = merged_df  # work on your merged catalog
df = add_extinction_and_deredden(df, flux_suffix="_sum",   prefix="sum")
df = add_extinction_and_deredden(df, flux_suffix="_int", prefix="int")

# -----------------------------
# 4) Add RA/Dec from WCS using peaks_df x,y (row-aligned)
# -----------------------------
w = WCS(ha_flux_header)

x = peaks_df["x"].to_numpy(dtype=float)
y = peaks_df["y"].to_numpy(dtype=float)
if ASSUME_1_BASED_PIXELS:
    x = x - 1.0
    y = y - 1.0

ra_deg, dec_deg = w.pixel_to_world_values(x, y)
df["RA_deg"] = ra_deg
df["Dec_deg"] = dec_deg

# -----------------------------
# 5) Galactocentric radius (deprojected) in kpc
# -----------------------------
coords = SkyCoord(ra=df["RA_deg"].to_numpy() * u.deg,
                  dec=df["Dec_deg"].to_numpy() * u.deg,
                  frame="icrs")

offset_frame = SkyOffsetFrame(origin=M33_CENTER)
off = coords.transform_to(offset_frame)

x_east_kpc  = off.lon.to(u.radian).value * M33_D_KPC
y_north_kpc = off.lat.to(u.radian).value * M33_D_KPC

sinPA, cosPA = np.sin(M33_PA), np.cos(M33_PA)
x_major = x_east_kpc * sinPA + y_north_kpc * cosPA
y_minor = x_east_kpc * cosPA - y_north_kpc * sinPA

y_minor_deproj = y_minor / np.cos(M33_INCL)
df["R_gal_kpc"] = np.sqrt(x_major**2 + y_minor_deproj**2)

# Write back
merged_df = df

#print all the new column names:
for col in merged_df.columns:
    print(col)

/var/folders/90/nb83zn5j00bc53x6bcv0jcwm0000gn/T/ipykernel_83367/1160896080.py:167: RuntimeWarning: invalid value encountered in log10
  log_SII_Ha[good_bpt] = np.log10(sii[good_bpt] / ha0[good_bpt])

sum: 653 valid points for BPT classification

KeyError: 'F_Halpha_int'

In [ ]:
DIST_MPC = 0.84  # M33 distance in Mpc (commonly ~0.84–0.85)

# ---- Flux -> luminosity conversion ----
# L = 4*pi*D^2*F, with D in cm if F is erg/s/cm^2
PC_CM = 3.085677581e18
D_cm = DIST_MPC * 1e6 * PC_CM
four_pi_D2 = 4.0 * np.pi * (D_cm**2)

# ---- Halpha flux columns that already exist in your catalog ----
# observed:
F_ha_raw   = merged_df["F_Halpha_sum"].to_numpy(dtype=float)
F_ha_int = merged_df["F_Halpha_int"].to_numpy(dtype=float)

# dereddened (created by the earlier cell):
F_ha_raw_dered   = merged_df["F_Halpha_sum_dered"].to_numpy(dtype=float)
F_ha_int_dered = merged_df["F_Halpha_int_dered"].to_numpy(dtype=float)

# ---- Add luminosity columns (erg/s if flux is erg/s/cm^2) ----
merged_df["L_Ha_sum"] = four_pi_D2 * F_ha_raw
merged_df["L_Ha_int"] = four_pi_D2 * F_ha_int
merged_df["L_Ha_sum_dered"] = four_pi_D2 * F_ha_raw_dered
merged_df["L_Ha_int_dered"] = four_pi_D2 * F_ha_int_dered

#add a column for log luminosity as well:
merged_df["log_L_Ha_sum"] = np.log10(merged_df["L_Ha_sum"])
merged_df["log_L_Ha_int"] = np.log10(merged_df["L_Ha_int"])
merged_df["log_L_Ha_sum_dered"] = np.log10(merged_df["L_Ha_sum_dered"])
merged_df["log_L_Ha_int_dered"] = np.log10(merged_df["L_Ha_int_dered"])

print("Added:", ["L_Ha_sum", "L_Ha_sum_dered"])

In [ ]:
outdir = "CATALOGS/flux_catalogs/"
os.makedirs(outdir, exist_ok=True)

outfile = os.path.join(outdir, f"flux_catalog_{field}.csv")
merged_df.to_csv(outfile, index=False)

print("Saved:", outfile)
print("Rows:", len(merged_df), "Cols:", len(merged_df.columns))

In [ ]:
#make a folder to save plots
figure_dir = "plots/individual_field_flux_plots"
os.makedirs(figure_dir, exist_ok=True)

In [ ]:
# Compute BPT points

prefix = 'int'
x_raw, y_raw = merged_df[f'log_NII_Ha_{prefix}_dered'].to_numpy(dtype=float), merged_df[f'log_OIII_Hb_{prefix}_dered'].to_numpy(dtype=float)
# x_bg,  y_bg  = bpt_xy(merged_df, use_bgsub=True)

# Demarcation curves (classic BPT)
x_curve = np.linspace(-2.0, 0.6, 600)
kewley = 0.61 / (x_curve - 0.47) + 1.19      # Kewley+2001
kauff  = 0.61 / (x_curve - 0.05) + 1.30      # Kauffmann+2003

# ---- Plot: overlay raw vs corrected in one figure ----
plt.figure(figsize=(7.5, 6.5))

classes = ["Star-forming", "Composite", "AGN/Shock", "Unclassified"]
colors = ['blue', 'green', 'red', 'grey']
for cls in classes:
    mask = (merged_df[f'BPT_class_{prefix}_dered'] == cls)
    plt.scatter(x_raw[mask], y_raw[mask], s=18, alpha=0.5, label=cls, color=colors[classes.index(cls)])
# #color by BPT class
# plt.scatter(x_raw[merged_df['raw_BPT_class'] == 'star-forming'], 
#             y_raw[merged_df['raw_BPT_class'] == 'star-forming'], s=18, alpha=0.5, label="Star-forming")
# # plt.scatter(x_bg,  y_bg,  s=18, alpha=0.5, label="Background-subtracted (edge threshold)")

plt.plot(x_curve, kewley, linestyle="--", label="Kewley+01", color = 'k')
plt.plot(x_curve, kauff,  linestyle="-.", label="Kauffmann+03", color = 'k')

plt.xlabel(r'$\log_{10}([NII]6583 / H\alpha)$')
plt.ylabel(r'$\log_{10}([OIII]5007 / H\beta)$')
plt.title(f"{field}, {prefix} \nStar-forming:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Star-forming'])}  Composite:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Composite'])}  AGN/Shock:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'AGN/Shock'])}  Unclassified:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Unclassified'])}")

plt.xlim(-2, 0.4)
plt.ylim(-2.5, 2)
plt.grid(alpha=0.3)
plt.legend(frameon=True)
plt.tight_layout()
plt.savefig(os.path.join(figure_dir, f"BPT_{field}_{prefix}.png"), dpi=150)
plt.show()

In [ ]:
# Compute BPT points

prefix = 'sum'
x_raw, y_raw = merged_df[f'log_NII_Ha_{prefix}_dered'].to_numpy(dtype=float), merged_df[f'log_OIII_Hb_{prefix}_dered'].to_numpy(dtype=float)
# x_bg,  y_bg  = bpt_xy(merged_df, use_bgsub=True)

# Demarcation curves (classic BPT)
x_curve = np.linspace(-2.0, 0.6, 600)
kewley = 0.61 / (x_curve - 0.47) + 1.19      # Kewley+2001
kauff  = 0.61 / (x_curve - 0.05) + 1.30      # Kauffmann+2003

# ---- Plot: overlay raw vs corrected in one figure ----
plt.figure(figsize=(7.5, 6.5))

classes = ["Star-forming", "Composite", "AGN/Shock", "Unclassified"]
colors = ['blue', 'green', 'red', 'grey']
for cls in classes:
    mask = (merged_df[f'BPT_class_{prefix}_dered'] == cls)
    plt.scatter(x_raw[mask], y_raw[mask], s=18, alpha=0.5, label=cls, color=colors[classes.index(cls)])
# #color by BPT class
# plt.scatter(x_raw[merged_df['raw_BPT_class'] == 'star-forming'], 
#             y_raw[merged_df['raw_BPT_class'] == 'star-forming'], s=18, alpha=0.5, label="Star-forming")
# # plt.scatter(x_bg,  y_bg,  s=18, alpha=0.5, label="Background-subtracted (edge threshold)")

plt.plot(x_curve, kewley, linestyle="--", label="Kewley+01", color = 'k')
plt.plot(x_curve, kauff,  linestyle="-.", label="Kauffmann+03", color = 'k')

plt.xlabel(r'$\log_{10}([NII]6583 / H\alpha)$')
plt.ylabel(r'$\log_{10}([OIII]5007 / H\beta)$')
plt.title(f"{field}, {prefix} \nStar-forming:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Star-forming'])}  Composite:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Composite'])}  AGN/Shock:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'AGN/Shock'])}  Unclassified:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Unclassified'])}")

plt.xlim(-2, 0.4)
plt.ylim(-2.5, 2)
plt.grid(alpha=0.3)
plt.legend(frameon=True)
plt.tight_layout()
plt.savefig(os.path.join(figure_dir, f"BPT_{field}_{prefix}.png"), dpi=150)
plt.show()

In [ ]:
def plot_field_overlay_halpha_peaks_zoi_boundaries(
    catalog_df,
    ha_fits_path,
    zoi_label_map,
    boundary_label_map,
    field_name=None,
    x_col="x",
    y_col="y",
    region_label_col="zoi_center_label",
    region_id_col="region_id",
    xlim=None,
    ylim=None,
    show_peaks=True,
    show_zoi=True,
    show_boundaries=True,
    peaks_kwargs=None,
    zoi_color="cyan",
    boundary_color="magenta",
    zoi_lw=0.8,
    boundary_lw=1.1,
    alpha_zoi=0.65,
    alpha_boundary=0.9,
    # NEW: LogNorm controls
    ha_percentiles=(5, 99),         # global vmin/vmax percentiles (positive pixels only)
    use_local_lognorm=False,        # if True and xlim/ylim provided -> compute per-view norm
    local_percentiles=(3.0, 99.7),  # per-view percentiles (positive pixels only)
    min_pos_pixels=20,              # minimum positive pixels required to trust local percentiles
    eps_pos=None,                   # epsilon floor for vmin (defaults to nextafter(0,1))
    savepath=None,
    line = 'Halpha'
):
    """
    Overplot peaks + ZOI outlines + boundary outlines on the Halpha map, using LogNorm scaling.

    Parameters
    ----------
    catalog_df : pandas.DataFrame
        Must include x_col/y_col; should include region_label_col (integer ZOI label at center).
    ha_fits_path : str
        Path to Halpha FITS.
    zoi_label_map : 2D array
        Integer-labeled ZOI map (0 outside).
    boundary_label_map : 2D array
        Integer-labeled boundary map (0 outside).
    field_name : str
        Optional display name.
    xlim, ylim : (min,max) or None
        Plot limits in pixel coordinates.
    ha_percentiles : (lo, hi)
        Percentiles used for global LogNorm vmin/vmax (positive finite pixels only).
    use_local_lognorm : bool
        If True and xlim/ylim are given, compute per-view LogNorm using local_percentiles,
        falling back to global if too few positive pixels.
    """

    import numpy as np
    import matplotlib.pyplot as plt
    from astropy.io import fits
    from matplotlib.colors import LogNorm

    # Lazy import so this cell works even if skimage isn't installed elsewhere
    try:
        from skimage.segmentation import find_boundaries  # noqa: F401  (kept as in your original)
    except Exception as e:
        raise ImportError(
            "This plotting function requires scikit-image. "
            "Install with: pip install scikit-image"
        ) from e

    if eps_pos is None:
        eps_pos = np.nextafter(0, 1)

    # --- Field name ---
    if field_name is None:
        field_name = (
            str(catalog_df.get("field", ["Field"]).iloc[0])
            if hasattr(catalog_df, "iloc")
            else "Field"
        )

    # --- Load Halpha map ---
    ha = fits.getdata(ha_fits_path)
    ha = np.where(np.isfinite(ha), ha, np.nan)

    # --- Compute GLOBAL LogNorm vmin/vmax from positive finite pixels ---
    valid_pos = ha[np.isfinite(ha) & (ha > 0)]
    if valid_pos.size == 0:
        raise ValueError("Hα map has no positive finite values for LogNorm.")

    vmin_global = np.nanpercentile(valid_pos, ha_percentiles[0])
    vmax_global = np.nanpercentile(valid_pos, ha_percentiles[1])

    # Fallback if percentiles are degenerate
    if (not np.isfinite(vmin_global)) or (not np.isfinite(vmax_global)) or (vmax_global <= vmin_global):
        vmin_global, vmax_global = np.nanmin(valid_pos), np.nanmax(valid_pos)
        if (not np.isfinite(vmin_global)) or (not np.isfinite(vmax_global)) or (vmax_global <= vmin_global):
            raise ValueError("Failed to compute valid global vmin/vmax for Hα.")

    vmin_global = max(vmin_global, eps_pos)

    def _local_lognorm(arr2d):
        """Compute a per-view LogNorm using positive finite pixels, fallback to global."""
        pos = arr2d[np.isfinite(arr2d) & (arr2d > 0)]
        vmin_loc, vmax_loc = vmin_global, vmax_global

        if pos.size >= min_pos_pixels:
            lo = np.nanpercentile(pos, local_percentiles[0])
            hi = np.nanpercentile(pos, local_percentiles[1])
            if np.isfinite(lo) and np.isfinite(hi) and hi > lo:
                vmin_loc, vmax_loc = lo, hi

        vmin_loc = max(vmin_loc, eps_pos)
        if (not np.isfinite(vmax_loc)) or (vmax_loc <= vmin_loc):
            vmax_loc = vmin_loc * 1.01
        return LogNorm(vmin=vmin_loc, vmax=vmax_loc)

    # Decide norm: global or local-per-view
    norm = LogNorm(vmin=vmin_global, vmax=vmax_global)
    if use_local_lognorm and (xlim is not None) and (ylim is not None):
        # Clip indices safely and compute norm on that view
        x0, x1 = sorted([int(np.floor(xlim[0])), int(np.ceil(xlim[1]))])
        y0, y1 = sorted([int(np.floor(ylim[0])), int(np.ceil(ylim[1]))])
        x0 = max(0, x0); y0 = max(0, y0)
        x1 = min(ha.shape[1], x1); y1 = min(ha.shape[0], y1)
        view = ha[y0:y1, x0:x1]
        if view.size > 0:
            norm = _local_lognorm(view)

    # --- Ensure integer maps ---
    zoi_int = np.rint(np.nan_to_num(zoi_label_map, nan=0)).astype(np.int32)
    bnd_int = np.rint(np.nan_to_num(boundary_label_map, nan=0)).astype(np.int32)

    # --- Figure ---
    fig, ax = plt.subplots(figsize=(10, 10 * ha.shape[0] / ha.shape[1]))

    # Make NaNs white
    cmap_gray = plt.get_cmap("gray").copy()
    cmap_gray.set_bad(color="white")

    # IMPORTANT CHANGE: show ha (linear) with LogNorm (not log10(ha))
    im = ax.imshow(ha, origin="lower", cmap=cmap_gray, norm=norm)

    # --- Overlay outlines ---
    labels_from_catalog = None
    if hasattr(catalog_df, "columns") and (region_label_col in catalog_df.columns):
        labels_from_catalog = sorted({
            int(v) for v in catalog_df[region_label_col].values
            if np.isfinite(v) and int(v) > 0
        })

    if labels_from_catalog and len(labels_from_catalog) > 0:
        labels = labels_from_catalog
    else:
        labels = sorted([int(v) for v in np.unique(bnd_int) if v > 0])

    # NOTE: your original code contours the entire label maps at 0.5, which is fine.
    if show_zoi and np.isfinite(zoi_int).any():
        edge = np.nan_to_num(zoi_int, nan=0.0)
        ax.contour(edge, levels=[0.5], colors=[zoi_color], linewidths=zoi_lw,
                   origin="lower", zorder=1, alpha=alpha_zoi)
    if show_boundaries and np.isfinite(bnd_int).any():
        edge = np.nan_to_num(bnd_int, nan=0.0)
        ax.contour(edge, levels=[0.5], colors=[boundary_color], linewidths=boundary_lw,
                   origin="lower", zorder=1, alpha=alpha_boundary)

    # --- Plot peak centers ---
    if show_peaks:
        if peaks_kwargs is None:
            peaks_kwargs = dict(marker="+", s=18, linewidths=0.8, alpha=0.85)
        xs = catalog_df[x_col].astype(float).values
        ys = catalog_df[y_col].astype(float).values
        ax.scatter(xs, ys, color="k", **peaks_kwargs, label="Peaks")

    # --- Colorbar ---
    cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label(r"Flux (LogNorm)")

    # --- Aesthetics ---
    ax.set_title(f"{line} with Peaks, ZOI (cyan), Boundaries (magenta)")
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_facecolor("white")
    fig.patch.set_facecolor("white")

    # Limits
    if xlim is not None:
        ax.set_xlim(*xlim)
    if ylim is not None:
        ax.set_ylim(*ylim)

    if show_peaks:
        ax.legend(loc="upper right", frameon=True)

    plt.tight_layout()

    if savepath:
        plt.savefig(savepath, bbox_inches="tight", dpi=300, facecolor="white")
        print(f"[done] Saved overlay plot: {savepath}")

    plt.show()
    plt.close(fig)
    return fig, ax

In [ ]:
"""
Runs the full-field overlay plot using the variables created earlier in the notebook.
"""
# Example usage (matches your earlier variables):
# - combined: your peak catalog dataframe
# - halpha_fits: Halpha FITS path
# - zoi_label: ZOI label map (2D)
# - boundary_label: final boundary label map (2D)

# Optional: zoom limits (set to None to show full frame)
xlim = (50, 2000)
ylim = (50, 2000)

contzoi_fits = f"ZOI_maps/ZOI_map_{max_zoi}pc/ContZoI_map_{field}.fits"
contzoi_label = fits.getdata(contzoi_fits)
cont_map_fits = f"Boundary_maps/Boundary_map_100pc/ContDomain_map_{field}.fits"
cont_map = fits.getdata(cont_map_fits)

plot_maps_dir = f"plots/individual_field_flux_plots/{field}"
os.makedirs(plot_maps_dir, exist_ok=True)
folder = f"../M33-Maps-Calibrated/M33-{field}/"
for line in ["ha", "hb", "oiii5007", "sii6716", "sii6731", "nii6584", "oii3727"]:
    line_fits = f"{folder}M33{field}-{line}flux.fits"
    line_data = fits.getdata(line_fits)
    line_data = np.where(np.isfinite(line_data), line_data, np.nan)
    plot_overlay_path = f"{plot_maps_dir}/M33_{field}_{line}_overlay.png"
    print(f"Creating overlay plot for {line} with peaks, ZOI, and boundaries; saving to: {plot_overlay_path}")
    plot_field_overlay_halpha_peaks_zoi_boundaries(
        catalog_df=merged_df,
        ha_fits_path=line_fits,
        zoi_label_map=contzoi_label,
        boundary_label_map=cont_map,
        field_name=f"M33 {field}",
        x_col="x",
        y_col="y",
        region_label_col="zoi_center_label",
        xlim=xlim,
        ylim=ylim,
        show_peaks=True,
        show_zoi=True,
        show_boundaries=True,
        savepath=plot_overlay_path,
        line = line
    )