<span style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">An Exception was encountered at '<a href="#papermill-error-cell">In [13]</a>'.</span>

In [1]:
field = 'NW'
max_zoi = 100

In [2]:
# Parameters
field = "F7"

# 6: With the domains, sum the flux within the region boundaries

In [3]:
from dataclasses import replace

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from astropy.io import fits
import os

from m33_pipeline import paths
from m33_pipeline.config import get_photometry_config
from m33_pipeline.io import read_catalog, read_fits_data, read_fits_data_header
from m33_pipeline.photometry import build_field_flux_catalog, load_flux_maps, load_integrated_flux_table, load_region_inputs
from m33_pipeline.validate import validate_field_flux_catalog

In [4]:
# Field-level region photometry now lives in m33_pipeline.photometry.
# This notebook keeps the downstream extinction, BPT, and plotting steps.

In [5]:
photometry_config = replace(get_photometry_config(), max_zoi_pc=max_zoi)
merged_df = build_field_flux_catalog(field, max_zoi, photometry_config)

validation_warnings = validate_field_flux_catalog(merged_df, field)
if validation_warnings:
    print("Validation warnings:")
    for warning in validation_warnings:
        print(f"- {warning}")

# Compatibility variables for downstream notebook cells that still expect the old inline setup.
flux_maps = load_flux_maps(field)
ha_flux_data, ha_flux_err_data = flux_maps["Halpha"]
hb_flux_data, hb_flux_err_data = flux_maps["Hbeta"]
oiii_flux_data, oiii_flux_err_data = flux_maps["[OIII]5007"]
sii6716_flux_data, sii6716_flux_err_data = flux_maps["[SII]6716"]
sii6731_flux_data, sii6731_flux_err_data = flux_maps["[SII]6731"]
nii6584_flux_data, nii6584_flux_err_data = flux_maps["[NII]6583"]
oii3727_flux_data, oii3727_flux_err_data = flux_maps["[OII]3727"]

ha_flux_data, ha_flux_header = read_fits_data_header(paths.calibrated_field_map_dir(field) / f"M33{field}-Haflux.fits")
region_inputs = load_region_inputs(field, max_zoi)
peaks_df = region_inputs["peaks_df"]
zoi_map = region_inputs["zoi_map"]
boundary_map = region_inputs["boundary_map"]
boundary_metric_df = region_inputs["boundary_metrics_df"]
int_flux_df = load_integrated_flux_table(field, len(peaks_df))

print("Built field flux catalog:", merged_df.shape)
merged_df.head()

Built field flux catalog: (952, 69)

,region_id,npix_region,npix_edge_ring,F_Halpha_sum,F_Halpha_e_sum,SNR_Halpha_sum,Halpha_b_edge,F_Halpha_bgsub,SNR_Halpha_bgsub,F_Hbeta_sum,...,radius_p16_pc,radius_p50_pc,radius_p84_pc,radius_areaeq_px,radius_areaeq_pc,boundary_method,area_px_after_carve,radius_areaeq_px_after_carve,radius_areaeq_pc_after_carve,id_int
0,1.0,179.0,55.0,3.858374e-15,7.468326e-17,51.663175,1.659721e-17,8.874746e-16,11.883179,1.558797e-15,...,5.111735,8.437418,14.151279,7.548342,9.947589,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,179.0,7.548342,9.947589,0
1,2.0,78.0,35.0,3.262498e-15,4.487835e-17,72.696481,3.805376e-17,2.943052e-16,6.557843,1.012764e-15,...,4.012951,6.001676,8.671066,4.982787,6.566571,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,78.0,4.982787,6.566571,1
2,3.0,121.0,43.0,4.524758e-15,5.662034e-17,79.914003,3.372933e-17,4.435095e-16,7.833042,1.261133e-15,...,6.305603,7.907105,10.542807,6.206085,8.178695,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,121.0,6.206085,8.178695,2
3,4.0,1234.0,134.0,1.086479e-13,2.382547e-16,456.015862,3.520497e-17,6.520501e-14,273.677702,3.460606e-14,...,7.907105,28.020087,35.596000,19.819041,26.118541,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,1234.0,19.819041,26.118541,3
4,5.0,102.0,38.0,2.373380e-15,4.305881e-17,55.119508,2.015897e-17,3.171649e-16,7.365855,7.151262e-16,...,5.271403,7.907105,9.448363,5.698035,7.509161,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,102.0,5.698035,7.509161,4

In [6]:
print("Regions with npix_region == 0:", (merged_df["npix_region"] == 0).sum())

for line_name in ["Halpha", "Hbeta", "[OIII]5007", "[SII]6716", "[SII]6731", "[NII]6583", "[OII]3727"]:
    n_nan = merged_df[f"{line_name}_b_edge"].isna().sum()
    print(f"{line_name}: NaN edge backgrounds = {n_nan}")

for col in merged_df.columns:
    print(col)

Regions with npix_region == 0: 0
Halpha: NaN edge backgrounds = 1
Hbeta: NaN edge backgrounds = 1
[OIII]5007: NaN edge backgrounds = 1
[SII]6716: NaN edge backgrounds = 1
[SII]6731: NaN edge backgrounds = 1
[NII]6583: NaN edge backgrounds = 1
[OII]3727: NaN edge backgrounds = 1
region_id
npix_region
npix_edge_ring
F_Halpha_sum
F_Halpha_e_sum
SNR_Halpha_sum
Halpha_b_edge
F_Halpha_bgsub
SNR_Halpha_bgsub
F_Hbeta_sum
F_Hbeta_e_sum
SNR_Hbeta_sum
Hbeta_b_edge
F_Hbeta_bgsub
SNR_Hbeta_bgsub
F_[OIII]5007_sum
F_[OIII]5007_e_sum
SNR_[OIII]5007_sum
[OIII]5007_b_edge
F_[OIII]5007_bgsub
SNR_[OIII]5007_bgsub
F_[SII]6716_sum
F_[SII]6716_e_sum
SNR_[SII]6716_sum
[SII]6716_b_edge
F_[SII]6716_bgsub
SNR_[SII]6716_bgsub
F_[SII]6731_sum
F_[SII]6731_e_sum
SNR_[SII]6731_sum
[SII]6731_b_edge
F_[SII]6731_bgsub
SNR_[SII]6731_bgsub
F_[NII]6583_sum
F_[NII]6583_e_sum
SNR_[NII]6583_sum
[NII]6583_b_edge
F_[NII]6583_bgsub
SNR_[NII]6583_bgsub
F_[OII]3727_sum
F_[OII]3727_e_sum
SNR_[OII]3727_sum
[OII]3727_b_edge
F_[OII]3727_bgsub
SNR_[OII]3727_bgsub
field
y
x
removed_by_saddle
removed_by_edge
kind
center_x_px
center_y_px
zoi_center_label
bg_local
sigma_local
radius_p16_px
radius_p50_px
radius_p84_px
radius_p16_pc
radius_p50_pc
radius_p84_pc
radius_areaeq_px
radius_areaeq_pc
boundary_method
area_px_after_carve
radius_areaeq_px_after_carve
radius_areaeq_pc_after_carve
id_int

In [7]:
# Put your flux and error maps in a dict for looping
maps = {
    "Halpha":      (ha_flux_data, ha_flux_err_data),
    "Hbeta":      (hb_flux_data, hb_flux_err_data),
    "[OIII]5007":(oiii_flux_data, oiii_flux_err_data),
    "[SII]6716": (sii6716_flux_data, sii6716_flux_err_data),
    "[SII]6731": (sii6731_flux_data, sii6731_flux_err_data),
    "[NII]6583": (nii6584_flux_data, nii6584_flux_err_data),
    "[OII]3727": (oii3727_flux_data, oii3727_flux_err_data),
}

# Region labels present in boundary_map (ignore 0, NaNs)
labels = np.unique(boundary_map[np.isfinite(boundary_map)])
labels = labels[labels > 0].astype(int)

print(f"Found {len(labels)} regions (labels > 0). Min={labels.min() if len(labels) else None}, Max={labels.max() if len(labels) else None}")

Found 951 regions (labels > 0). Min=1, Max=952

In [8]:
from tqdm import tqdm
from scipy.ndimage import binary_dilation
def region_edge_ring(region_mask, iterations=1):
    """
    Build an *outer edge ring* just outside the region boundary.

    Exactly:
    - Take region_mask (True inside region)
    - Dilate it by `iterations` pixels
    - Outer ring = dilated_mask & (~region_mask)

    This produces a 1-pixel thick ring outside the region if iterations=1,
    thicker if iterations>1.
    """
    region_mask = np.asarray(region_mask, dtype=bool)
    dil = binary_dilation(region_mask, iterations=iterations)
    ring = dil & (~region_mask)
    return ring

def integrated_flux_and_snr(flux, err, region_mask, ring_mask=None, clip_negative_after_bg=False):
    """
    Compute integrated flux and SNR for a region.

    Definitions used (exact):
    1) Raw integrated flux:
       F_raw = sum_i flux_i  over pixels i inside region_mask

    2) Integrated uncertainty (assuming per-pixel errors are 1-sigma and independent):
       sigma_F = sqrt( sum_i err_i^2 )   over pixels i inside region_mask

    3) Raw SNR:
       SNR_sum = F_raw / sigma_F   (if sigma_F>0 else NaN)

    Background subtraction (if ring_mask provided):
    4) Background level per pixel:
       b = mean_j flux_j over pixels j in ring_mask
       (with NaN-safe mean)

    5) Background-subtracted integrated flux:
       F_bgsub = sum_i (flux_i - b) over region pixels
              = F_raw - b * Npix_region

       Uncertainty remains:
       sigma_F_bgsub = sigma_F
       (i.e., we *do not* add uncertainty from estimating b; if you want that,
        we can include it, but this is the simplest standard approach.)

    6) Background-subtracted SNR:
       SNR_bgsub = F_bgsub / sigma_F  (if sigma_F>0 else NaN)

    Options:
    - clip_negative_after_bg: if True, clip (flux_i - b) at 0 before summing.
      (Default False = physically allows negative after subtraction.)
    """
    flux = np.asarray(flux, dtype=float)
    err  = np.asarray(err, dtype=float)

    inside = region_mask
    f_vals = flux[inside]
    e_vals = err[inside]

    # NaN handling: ignore NaNs in flux; but for error we must also ignore same pixels
    good = np.isfinite(f_vals) & np.isfinite(e_vals)
    f_vals = f_vals[good]
    e_vals = e_vals[good]

    npix = f_vals.size
    if npix == 0:
        return dict(
            npix=0,
            F_raw=np.nan, sigma_F=np.nan, SNR_raw=np.nan,
            b_edge=np.nan, F_bgsub=np.nan, SNR_bgsub=np.nan
        )

    F_raw = np.sum(f_vals)
    sigma_F = np.sqrt(np.sum(e_vals**2))
    SNR_raw = F_raw / sigma_F if sigma_F > 0 else np.nan

    b_edge = np.nan
    F_bgsub = np.nan
    SNR_bgsub = np.nan

    if ring_mask is not None:
        ring_vals = flux[ring_mask]
        ring_vals = ring_vals[np.isfinite(ring_vals)]
        b_edge = np.nanmean(ring_vals) if ring_vals.size > 0 else np.nan

        # background subtract
        if np.isfinite(b_edge):
            if clip_negative_after_bg:
                F_bgsub = np.sum(np.clip(f_vals - b_edge, 0, None))
            else:
                F_bgsub = np.sum(f_vals - b_edge)

            SNR_bgsub = F_bgsub / sigma_F if sigma_F > 0 else np.nan
        else:
            F_bgsub = np.nan
            SNR_bgsub = np.nan

    return dict(
        npix=npix,
        F_raw=F_raw,
        sigma_F=sigma_F,
        SNR_raw=SNR_raw,
        b_edge=b_edge,
        # F_bgsub=F_bgsub,
        # SNR_bgsub=SNR_bgsub
    )

def merge_check_duplicates(left_df, right_df, on, how="left", suffixes=("_x", "_y"), rtol=0, atol=0):
    """
    Merge and resolve duplicate columns:
    - If a column name exists in both (excluding key columns), compare values.
    - If all equal within tolerance -> keep one.
    - If not equal -> keep both with suffixes.

    This expects 'on' to be a list or string key(s).
    """
    if isinstance(on, str):
        on = [on]

    overlap = (set(left_df.columns) & set(right_df.columns)) - set(on)
    merged = left_df.merge(right_df, on=on, how=how, suffixes=suffixes)

    for col in overlap:
        cx = f"{col}{suffixes[0]}"
        cy = f"{col}{suffixes[1]}"
        if cx in merged.columns and cy in merged.columns:
            a = merged[cx].to_numpy()
            b = merged[cy].to_numpy()

            # treat NaNs as equal where both NaN
            both_nan = np.isnan(a) & np.isnan(b) if (np.issubdtype(a.dtype, np.number) and np.issubdtype(b.dtype, np.number)) else np.zeros_like(a, dtype=bool)

            equal = False
            if np.issubdtype(a.dtype, np.number) and np.issubdtype(b.dtype, np.number):
                equal = np.allclose(a[~both_nan], b[~both_nan], rtol=rtol, atol=atol, equal_nan=True)
            else:
                equal = np.all((a == b) | (pd.isna(a) & pd.isna(b)))

            if equal:
                merged[col] = merged[cx]
                merged.drop(columns=[cx, cy], inplace=True)
            else:
                # keep both; do nothing
                pass

    return merged

In [9]:
# Parameters you can tune:
edge_ring_iterations = 1          # thickness of outer ring (pixels)
clip_negative_after_bg = False    # True if you want to force bgsub flux >= 0 per pixel

rows = []

for rid in tqdm(labels, desc="Processing regions"):
    region_mask = (boundary_map == rid)
    ring_mask = region_edge_ring(region_mask, iterations=edge_ring_iterations)

    row = {
        "region_id": rid,
        "npix_region": int(np.sum(region_mask)),
        "npix_edge_ring": int(np.sum(ring_mask)),
    }

    # # optional: store a region-wide average ZoI value (or something else)
    # if 'zoi_map' in globals() and zoi_map is not None:
    #     zvals = zoi_map[region_mask]
    #     zvals = zvals[np.isfinite(zvals)]
    #     row["zoi_mean"] = float(np.nanmean(zvals)) if zvals.size else np.nan
    #     row["zoi_median"] = float(np.nanmedian(zvals)) if zvals.size else np.nan
    # else:
    #     row["zoi_mean"] = np.nan
    #     row["zoi_median"] = np.nan

    for name, (flux, err) in maps.items():
        stats = integrated_flux_and_snr(
            flux=flux,
            err=err,
            region_mask=region_mask,
            ring_mask=ring_mask,
            clip_negative_after_bg=clip_negative_after_bg
        )

        # Write columns in a consistent naming scheme
        row[f"F_{name}_sum"]     = stats["F_raw"]
        row[f"F_{name}_e_sum"]   = stats["sigma_F"]
        row[f"SNR_{name}_sum"]   = stats["SNR_raw"]
        row[f"{name}_b_edge"]    = stats["b_edge"]
        # row[f"{name}_F_bgsub"]   = stats["F_bgsub"]
        # row[f"{name}_SNR_bgsub"] = stats["SNR_bgsub"]

    rows.append(row)

flux_catalog_df = pd.DataFrame(rows).sort_values("region_id").reset_index(drop=True)

flux_catalog_df.head()

Processing regions:   0%|                                                                                                                     | 0/951 [00:00<?, ?it/s]

Processing regions:   0%|▏                                                                                                            | 2/951 [00:00<01:10, 13.38it/s]

Processing regions:   0%|▍                                                                                                            | 4/951 [00:00<01:04, 14.72it/s]

Processing regions:   1%|▋                                                                                                            | 6/951 [00:00<01:02, 15.23it/s]

Processing regions:   1%|▉                                                                                                            | 8/951 [00:00<01:01, 15.43it/s]

Processing regions:   1%|█▏                                                                                                          | 10/951 [00:00<00:59, 15.70it/s]

Processing regions:   1%|█▎                                                                                                          | 12/951 [00:00<00:59, 15.78it/s]

Processing regions:   1%|█▌                                                                                                          | 14/951 [00:00<00:58, 15.91it/s]

Processing regions:   2%|█▊                                                                                                          | 16/951 [00:01<00:59, 15.71it/s]

Processing regions:   2%|██                                                                                                          | 18/951 [00:01<00:59, 15.73it/s]

Processing regions:   2%|██▎                                                                                                         | 20/951 [00:01<00:58, 15.84it/s]

Processing regions:   2%|██▍                                                                                                         | 22/951 [00:01<00:58, 15.92it/s]

Processing regions:   3%|██▋                                                                                                         | 24/951 [00:01<00:57, 15.99it/s]

Processing regions:   3%|██▉                                                                                                         | 26/951 [00:01<00:58, 15.92it/s]

Processing regions:   3%|███▏                                                                                                        | 28/951 [00:01<00:57, 15.94it/s]

Processing regions:   3%|███▍                                                                                                        | 30/951 [00:01<00:57, 16.02it/s]

Processing regions:   3%|███▋                                                                                                        | 32/951 [00:02<00:57, 15.90it/s]

Processing regions:   4%|███▊                                                                                                        | 34/951 [00:02<00:57, 15.97it/s]

Processing regions:   4%|████                                                                                                        | 36/951 [00:02<00:57, 15.96it/s]

Processing regions:   4%|████▎                                                                                                       | 38/951 [00:02<00:56, 16.03it/s]

Processing regions:   4%|████▌                                                                                                       | 40/951 [00:02<00:56, 16.09it/s]

Processing regions:   4%|████▊                                                                                                       | 42/951 [00:02<00:56, 16.13it/s]

Processing regions:   5%|████▉                                                                                                       | 44/951 [00:02<00:56, 16.08it/s]

Processing regions:   5%|█████▏                                                                                                      | 46/951 [00:02<00:56, 16.10it/s]

Processing regions:   5%|█████▍                                                                                                      | 48/951 [00:03<00:56, 15.95it/s]

Processing regions:   5%|█████▋                                                                                                      | 50/951 [00:03<00:56, 15.94it/s]

Processing regions:   5%|█████▉                                                                                                      | 52/951 [00:03<00:56, 15.86it/s]

Processing regions:   6%|██████▏                                                                                                     | 54/951 [00:03<00:57, 15.70it/s]

Processing regions:   6%|██████▎                                                                                                     | 56/951 [00:03<00:56, 15.82it/s]

Processing regions:   6%|██████▌                                                                                                     | 58/951 [00:03<00:56, 15.90it/s]

Processing regions:   6%|██████▊                                                                                                     | 60/951 [00:03<00:55, 15.96it/s]

Processing regions:   7%|███████                                                                                                     | 62/951 [00:03<00:55, 16.07it/s]

Processing regions:   7%|███████▎                                                                                                    | 64/951 [00:04<00:55, 16.02it/s]

Processing regions:   7%|███████▍                                                                                                    | 66/951 [00:04<00:55, 15.99it/s]

Processing regions:   7%|███████▋                                                                                                    | 68/951 [00:04<00:55, 15.97it/s]

Processing regions:   7%|███████▉                                                                                                    | 70/951 [00:04<00:55, 15.87it/s]

Processing regions:   8%|████████▏                                                                                                   | 72/951 [00:04<00:55, 15.97it/s]

Processing regions:   8%|████████▍                                                                                                   | 74/951 [00:04<00:54, 16.00it/s]

Processing regions:   8%|████████▋                                                                                                   | 76/951 [00:04<00:54, 16.01it/s]

Processing regions:   8%|████████▊                                                                                                   | 78/951 [00:04<00:54, 16.13it/s]

Processing regions:   8%|█████████                                                                                                   | 80/951 [00:05<00:54, 15.87it/s]

Processing regions:   9%|█████████▎                                                                                                  | 82/951 [00:05<00:55, 15.63it/s]

Processing regions:   9%|█████████▌                                                                                                  | 84/951 [00:05<00:56, 15.42it/s]

Processing regions:   9%|█████████▊                                                                                                  | 86/951 [00:05<00:56, 15.33it/s]

Processing regions:   9%|█████████▉                                                                                                  | 88/951 [00:05<00:55, 15.42it/s]

Processing regions:   9%|██████████▏                                                                                                 | 90/951 [00:05<00:55, 15.54it/s]

Processing regions:  10%|██████████▍                                                                                                 | 92/951 [00:05<00:54, 15.69it/s]

Processing regions:  10%|██████████▋                                                                                                 | 94/951 [00:05<00:54, 15.85it/s]

Processing regions:  10%|██████████▉                                                                                                 | 96/951 [00:06<00:54, 15.68it/s]

Processing regions:  10%|███████████▏                                                                                                | 98/951 [00:06<00:54, 15.66it/s]

Processing regions:  11%|███████████▎                                                                                               | 100/951 [00:06<00:54, 15.68it/s]

Processing regions:  11%|███████████▍                                                                                               | 102/951 [00:06<00:53, 15.79it/s]

Processing regions:  11%|███████████▋                                                                                               | 104/951 [00:06<00:53, 15.91it/s]

Processing regions:  11%|███████████▉                                                                                               | 106/951 [00:06<00:52, 15.98it/s]

Processing regions:  11%|████████████▏                                                                                              | 108/951 [00:06<00:53, 15.80it/s]

Processing regions:  12%|████████████▍                                                                                              | 110/951 [00:06<00:54, 15.51it/s]

Processing regions:  12%|████████████▌                                                                                              | 112/951 [00:07<00:54, 15.41it/s]

Processing regions:  12%|████████████▊                                                                                              | 114/951 [00:07<00:53, 15.61it/s]

Processing regions:  12%|█████████████                                                                                              | 116/951 [00:07<00:53, 15.73it/s]

Processing regions:  12%|█████████████▎                                                                                             | 118/951 [00:07<00:52, 15.76it/s]

Processing regions:  13%|█████████████▌                                                                                             | 120/951 [00:07<00:52, 15.91it/s]

Processing regions:  13%|█████████████▋                                                                                             | 122/951 [00:07<00:51, 16.05it/s]

Processing regions:  13%|█████████████▉                                                                                             | 124/951 [00:07<00:51, 16.00it/s]

Processing regions:  13%|██████████████▏                                                                                            | 126/951 [00:07<00:51, 16.09it/s]

Processing regions:  13%|██████████████▍                                                                                            | 128/951 [00:08<00:51, 15.97it/s]

Processing regions:  14%|██████████████▋                                                                                            | 130/951 [00:08<00:51, 15.98it/s]

Processing regions:  14%|██████████████▊                                                                                            | 132/951 [00:08<00:51, 15.96it/s]

Processing regions:  14%|███████████████                                                                                            | 134/951 [00:08<00:51, 16.00it/s]

Processing regions:  14%|███████████████▎                                                                                           | 136/951 [00:08<00:51, 15.80it/s]

Processing regions:  15%|███████████████▌                                                                                           | 138/951 [00:08<00:51, 15.86it/s]

Processing regions:  15%|███████████████▊                                                                                           | 140/951 [00:08<00:50, 15.90it/s]

Processing regions:  15%|███████████████▉                                                                                           | 142/951 [00:08<00:50, 15.99it/s]

Processing regions:  15%|████████████████▏                                                                                          | 144/951 [00:09<00:51, 15.81it/s]

Processing regions:  15%|████████████████▍                                                                                          | 146/951 [00:09<00:50, 15.91it/s]

Processing regions:  16%|████████████████▋                                                                                          | 148/951 [00:09<00:50, 16.02it/s]

Processing regions:  16%|████████████████▉                                                                                          | 150/951 [00:09<00:49, 16.03it/s]

Processing regions:  16%|█████████████████                                                                                          | 152/951 [00:09<00:50, 15.95it/s]

Processing regions:  16%|█████████████████▎                                                                                         | 154/951 [00:09<00:49, 16.03it/s]

Processing regions:  16%|█████████████████▌                                                                                         | 156/951 [00:09<00:49, 16.08it/s]

Processing regions:  17%|█████████████████▊                                                                                         | 158/951 [00:09<00:49, 16.00it/s]

Processing regions:  17%|██████████████████                                                                                         | 160/951 [00:10<00:50, 15.77it/s]

Processing regions:  17%|██████████████████▏                                                                                        | 162/951 [00:10<00:50, 15.77it/s]

Processing regions:  17%|██████████████████▍                                                                                        | 164/951 [00:10<00:50, 15.61it/s]

Processing regions:  17%|██████████████████▋                                                                                        | 166/951 [00:10<00:51, 15.29it/s]

Processing regions:  18%|██████████████████▉                                                                                        | 168/951 [00:10<00:51, 15.26it/s]

Processing regions:  18%|███████████████████▏                                                                                       | 170/951 [00:10<00:51, 15.17it/s]

Processing regions:  18%|███████████████████▎                                                                                       | 172/951 [00:10<00:50, 15.46it/s]

Processing regions:  18%|███████████████████▌                                                                                       | 174/951 [00:11<00:50, 15.46it/s]

Processing regions:  19%|███████████████████▊                                                                                       | 176/951 [00:11<00:50, 15.46it/s]

Processing regions:  19%|████████████████████                                                                                       | 178/951 [00:11<00:49, 15.62it/s]

Processing regions:  19%|████████████████████▎                                                                                      | 180/951 [00:11<00:49, 15.70it/s]

Processing regions:  19%|████████████████████▍                                                                                      | 182/951 [00:11<00:48, 15.77it/s]

Processing regions:  19%|████████████████████▋                                                                                      | 184/951 [00:11<00:48, 15.81it/s]

Processing regions:  20%|████████████████████▉                                                                                      | 186/951 [00:11<00:48, 15.87it/s]

Processing regions:  20%|█████████████████████▏                                                                                     | 188/951 [00:11<00:48, 15.88it/s]

Processing regions:  20%|█████████████████████▍                                                                                     | 190/951 [00:12<00:48, 15.73it/s]

Processing regions:  20%|█████████████████████▌                                                                                     | 192/951 [00:12<00:48, 15.74it/s]

Processing regions:  20%|█████████████████████▊                                                                                     | 194/951 [00:12<00:47, 15.84it/s]

Processing regions:  21%|██████████████████████                                                                                     | 196/951 [00:12<00:47, 15.90it/s]

Processing regions:  21%|██████████████████████▎                                                                                    | 198/951 [00:12<00:47, 15.94it/s]

Processing regions:  21%|██████████████████████▌                                                                                    | 200/951 [00:12<00:46, 16.06it/s]

Processing regions:  21%|██████████████████████▋                                                                                    | 202/951 [00:12<00:46, 16.05it/s]

Processing regions:  21%|██████████████████████▉                                                                                    | 204/951 [00:12<00:46, 16.07it/s]

Processing regions:  22%|███████████████████████▏                                                                                   | 206/951 [00:13<00:46, 16.10it/s]

Processing regions:  22%|███████████████████████▍                                                                                   | 208/951 [00:13<00:47, 15.71it/s]

Processing regions:  22%|███████████████████████▋                                                                                   | 210/951 [00:13<00:46, 15.83it/s]

Processing regions:  22%|███████████████████████▊                                                                                   | 212/951 [00:13<00:46, 15.91it/s]

Processing regions:  23%|████████████████████████                                                                                   | 214/951 [00:13<00:46, 15.94it/s]

Processing regions:  23%|████████████████████████▎                                                                                  | 216/951 [00:13<00:45, 16.04it/s]

Processing regions:  23%|████████████████████████▌                                                                                  | 218/951 [00:13<00:47, 15.50it/s]

Processing regions:  23%|████████████████████████▊                                                                                  | 220/951 [00:13<00:47, 15.41it/s]

Processing regions:  23%|████████████████████████▉                                                                                  | 222/951 [00:14<00:47, 15.36it/s]

Processing regions:  24%|█████████████████████████▏                                                                                 | 224/951 [00:14<00:46, 15.49it/s]

Processing regions:  24%|█████████████████████████▍                                                                                 | 226/951 [00:14<00:46, 15.62it/s]

Processing regions:  24%|█████████████████████████▋                                                                                 | 228/951 [00:14<00:46, 15.66it/s]

Processing regions:  24%|█████████████████████████▉                                                                                 | 230/951 [00:14<00:45, 15.84it/s]

Processing regions:  24%|██████████████████████████                                                                                 | 232/951 [00:14<00:45, 15.93it/s]

Processing regions:  25%|██████████████████████████▎                                                                                | 234/951 [00:14<00:45, 15.91it/s]

Processing regions:  25%|██████████████████████████▌                                                                                | 236/951 [00:14<00:44, 15.96it/s]

Processing regions:  25%|██████████████████████████▊                                                                                | 238/951 [00:15<00:44, 15.89it/s]

Processing regions:  25%|███████████████████████████                                                                                | 240/951 [00:15<00:44, 15.85it/s]

Processing regions:  25%|███████████████████████████▏                                                                               | 242/951 [00:15<00:44, 15.90it/s]

Processing regions:  26%|███████████████████████████▍                                                                               | 244/951 [00:15<00:44, 15.81it/s]

Processing regions:  26%|███████████████████████████▋                                                                               | 246/951 [00:15<00:44, 15.91it/s]

Processing regions:  26%|███████████████████████████▉                                                                               | 248/951 [00:15<00:44, 15.94it/s]

Processing regions:  26%|████████████████████████████▏                                                                              | 250/951 [00:15<00:43, 15.96it/s]

Processing regions:  26%|████████████████████████████▎                                                                              | 252/951 [00:15<00:43, 16.01it/s]

Processing regions:  27%|████████████████████████████▌                                                                              | 254/951 [00:16<00:43, 15.92it/s]

Processing regions:  27%|████████████████████████████▊                                                                              | 256/951 [00:16<00:44, 15.79it/s]

Processing regions:  27%|█████████████████████████████                                                                              | 258/951 [00:16<00:43, 15.98it/s]

Processing regions:  27%|█████████████████████████████▎                                                                             | 260/951 [00:16<00:42, 16.11it/s]

Processing regions:  28%|█████████████████████████████▍                                                                             | 262/951 [00:16<00:42, 16.08it/s]

Processing regions:  28%|█████████████████████████████▋                                                                             | 264/951 [00:16<00:42, 16.13it/s]

Processing regions:  28%|█████████████████████████████▉                                                                             | 266/951 [00:16<00:42, 16.10it/s]

Processing regions:  28%|██████████████████████████████▏                                                                            | 268/951 [00:16<00:42, 16.07it/s]

Processing regions:  28%|██████████████████████████████▍                                                                            | 270/951 [00:17<00:44, 15.37it/s]

Processing regions:  29%|██████████████████████████████▌                                                                            | 272/951 [00:17<00:44, 15.31it/s]

Processing regions:  29%|██████████████████████████████▊                                                                            | 274/951 [00:17<00:43, 15.56it/s]

Processing regions:  29%|███████████████████████████████                                                                            | 276/951 [00:17<00:43, 15.69it/s]

Processing regions:  29%|███████████████████████████████▎                                                                           | 278/951 [00:17<00:42, 15.79it/s]

Processing regions:  29%|███████████████████████████████▌                                                                           | 280/951 [00:17<00:42, 15.86it/s]

Processing regions:  30%|███████████████████████████████▋                                                                           | 282/951 [00:17<00:42, 15.88it/s]

Processing regions:  30%|███████████████████████████████▉                                                                           | 284/951 [00:17<00:41, 15.97it/s]

Processing regions:  30%|████████████████████████████████▏                                                                          | 286/951 [00:18<00:41, 15.86it/s]

Processing regions:  30%|████████████████████████████████▍                                                                          | 288/951 [00:18<00:42, 15.75it/s]

Processing regions:  30%|████████████████████████████████▋                                                                          | 290/951 [00:18<00:41, 15.85it/s]

Processing regions:  31%|████████████████████████████████▊                                                                          | 292/951 [00:18<00:41, 15.91it/s]

Processing regions:  31%|█████████████████████████████████                                                                          | 294/951 [00:18<00:41, 15.98it/s]

Processing regions:  31%|█████████████████████████████████▎                                                                         | 296/951 [00:18<00:41, 15.96it/s]

Processing regions:  31%|█████████████████████████████████▌                                                                         | 298/951 [00:18<00:40, 15.99it/s]

Processing regions:  32%|█████████████████████████████████▊                                                                         | 300/951 [00:18<00:40, 15.92it/s]

Processing regions:  32%|█████████████████████████████████▉                                                                         | 302/951 [00:19<00:41, 15.78it/s]

Processing regions:  32%|██████████████████████████████████▏                                                                        | 304/951 [00:19<00:41, 15.61it/s]

Processing regions:  32%|██████████████████████████████████▍                                                                        | 306/951 [00:19<00:41, 15.53it/s]

Processing regions:  32%|██████████████████████████████████▋                                                                        | 308/951 [00:19<00:41, 15.31it/s]

Processing regions:  33%|██████████████████████████████████▉                                                                        | 310/951 [00:19<00:42, 15.21it/s]

Processing regions:  33%|███████████████████████████████████                                                                        | 312/951 [00:19<00:41, 15.28it/s]

Processing regions:  33%|███████████████████████████████████▎                                                                       | 314/951 [00:19<00:40, 15.58it/s]

Processing regions:  33%|███████████████████████████████████▌                                                                       | 316/951 [00:20<00:40, 15.69it/s]

Processing regions:  33%|███████████████████████████████████▊                                                                       | 318/951 [00:20<00:40, 15.70it/s]

Processing regions:  34%|████████████████████████████████████                                                                       | 320/951 [00:20<00:40, 15.73it/s]

Processing regions:  34%|████████████████████████████████████▏                                                                      | 322/951 [00:20<00:39, 15.80it/s]

Processing regions:  34%|████████████████████████████████████▍                                                                      | 324/951 [00:20<00:39, 15.86it/s]

Processing regions:  34%|████████████████████████████████████▋                                                                      | 326/951 [00:20<00:39, 15.77it/s]

Processing regions:  34%|████████████████████████████████████▉                                                                      | 328/951 [00:20<00:40, 15.46it/s]

Processing regions:  35%|█████████████████████████████████████▏                                                                     | 330/951 [00:20<00:39, 15.61it/s]

Processing regions:  35%|█████████████████████████████████████▎                                                                     | 332/951 [00:21<00:39, 15.72it/s]

Processing regions:  35%|█████████████████████████████████████▌                                                                     | 334/951 [00:21<00:39, 15.64it/s]

Processing regions:  35%|█████████████████████████████████████▊                                                                     | 336/951 [00:21<00:39, 15.64it/s]

Processing regions:  36%|██████████████████████████████████████                                                                     | 338/951 [00:21<00:38, 15.77it/s]

Processing regions:  36%|██████████████████████████████████████▎                                                                    | 340/951 [00:21<00:38, 15.82it/s]

Processing regions:  36%|██████████████████████████████████████▍                                                                    | 342/951 [00:21<00:38, 15.86it/s]

Processing regions:  36%|██████████████████████████████████████▋                                                                    | 344/951 [00:21<00:38, 15.87it/s]

Processing regions:  36%|██████████████████████████████████████▉                                                                    | 346/951 [00:21<00:37, 15.99it/s]

Processing regions:  37%|███████████████████████████████████████▏                                                                   | 348/951 [00:22<00:38, 15.84it/s]

Processing regions:  37%|███████████████████████████████████████▍                                                                   | 350/951 [00:22<00:38, 15.78it/s]

Processing regions:  37%|███████████████████████████████████████▌                                                                   | 352/951 [00:22<00:38, 15.76it/s]

Processing regions:  37%|███████████████████████████████████████▊                                                                   | 354/951 [00:22<00:37, 15.78it/s]

Processing regions:  37%|████████████████████████████████████████                                                                   | 356/951 [00:22<00:37, 15.84it/s]

Processing regions:  38%|████████████████████████████████████████▎                                                                  | 358/951 [00:22<00:37, 15.90it/s]

Processing regions:  38%|████████████████████████████████████████▌                                                                  | 360/951 [00:22<00:37, 15.92it/s]

Processing regions:  38%|████████████████████████████████████████▋                                                                  | 362/951 [00:22<00:37, 15.91it/s]

Processing regions:  38%|████████████████████████████████████████▉                                                                  | 364/951 [00:23<00:36, 15.92it/s]

Processing regions:  38%|█████████████████████████████████████████▏                                                                 | 366/951 [00:23<00:37, 15.80it/s]

Processing regions:  39%|█████████████████████████████████████████▍                                                                 | 368/951 [00:23<00:36, 15.82it/s]

Processing regions:  39%|█████████████████████████████████████████▋                                                                 | 370/951 [00:23<00:36, 15.88it/s]

Processing regions:  39%|█████████████████████████████████████████▊                                                                 | 372/951 [00:23<00:36, 15.84it/s]

Processing regions:  39%|██████████████████████████████████████████                                                                 | 374/951 [00:23<00:36, 15.88it/s]

Processing regions:  40%|██████████████████████████████████████████▎                                                                | 376/951 [00:23<00:36, 15.90it/s]

Processing regions:  40%|██████████████████████████████████████████▌                                                                | 378/951 [00:23<00:35, 15.93it/s]

Processing regions:  40%|██████████████████████████████████████████▊                                                                | 380/951 [00:24<00:35, 15.91it/s]

Processing regions:  40%|██████████████████████████████████████████▉                                                                | 382/951 [00:24<00:36, 15.75it/s]

Processing regions:  40%|███████████████████████████████████████████▏                                                               | 384/951 [00:24<00:36, 15.69it/s]

Processing regions:  41%|███████████████████████████████████████████▍                                                               | 386/951 [00:24<00:36, 15.69it/s]

Processing regions:  41%|███████████████████████████████████████████▋                                                               | 388/951 [00:24<00:35, 15.74it/s]

Processing regions:  41%|███████████████████████████████████████████▉                                                               | 390/951 [00:24<00:35, 15.83it/s]

Processing regions:  41%|████████████████████████████████████████████                                                               | 392/951 [00:24<00:35, 15.81it/s]

Processing regions:  41%|████████████████████████████████████████████▎                                                              | 394/951 [00:24<00:35, 15.90it/s]

Processing regions:  42%|████████████████████████████████████████████▌                                                              | 396/951 [00:25<00:35, 15.75it/s]

Processing regions:  42%|████████████████████████████████████████████▊                                                              | 398/951 [00:25<00:35, 15.67it/s]

Processing regions:  42%|█████████████████████████████████████████████                                                              | 400/951 [00:25<00:35, 15.63it/s]

Processing regions:  42%|█████████████████████████████████████████████▏                                                             | 402/951 [00:25<00:34, 15.75it/s]

Processing regions:  42%|█████████████████████████████████████████████▍                                                             | 404/951 [00:25<00:34, 15.84it/s]

Processing regions:  43%|█████████████████████████████████████████████▋                                                             | 406/951 [00:25<00:34, 15.81it/s]

Processing regions:  43%|█████████████████████████████████████████████▉                                                             | 408/951 [00:25<00:34, 15.79it/s]

Processing regions:  43%|██████████████████████████████████████████████▏                                                            | 410/951 [00:25<00:34, 15.49it/s]

Processing regions:  43%|██████████████████████████████████████████████▎                                                            | 412/951 [00:26<00:34, 15.59it/s]

Processing regions:  44%|██████████████████████████████████████████████▌                                                            | 414/951 [00:26<00:34, 15.58it/s]

Processing regions:  44%|██████████████████████████████████████████████▊                                                            | 416/951 [00:26<00:34, 15.63it/s]

Processing regions:  44%|███████████████████████████████████████████████                                                            | 418/951 [00:26<00:33, 15.74it/s]

Processing regions:  44%|███████████████████████████████████████████████▎                                                           | 420/951 [00:26<00:33, 15.84it/s]

Processing regions:  44%|███████████████████████████████████████████████▍                                                           | 422/951 [00:26<00:33, 15.90it/s]

Processing regions:  45%|███████████████████████████████████████████████▋                                                           | 424/951 [00:26<00:33, 15.96it/s]

Processing regions:  45%|███████████████████████████████████████████████▉                                                           | 426/951 [00:26<00:32, 16.03it/s]

Processing regions:  45%|████████████████████████████████████████████████▏                                                          | 428/951 [00:27<00:32, 15.92it/s]

Processing regions:  45%|████████████████████████████████████████████████▍                                                          | 430/951 [00:27<00:32, 15.80it/s]

Processing regions:  45%|████████████████████████████████████████████████▌                                                          | 432/951 [00:27<00:32, 15.80it/s]

Processing regions:  46%|████████████████████████████████████████████████▊                                                          | 434/951 [00:27<00:32, 15.84it/s]

Processing regions:  46%|█████████████████████████████████████████████████                                                          | 436/951 [00:27<00:32, 15.69it/s]

Processing regions:  46%|█████████████████████████████████████████████████▎                                                         | 438/951 [00:27<00:33, 15.46it/s]

Processing regions:  46%|█████████████████████████████████████████████████▌                                                         | 440/951 [00:27<00:32, 15.54it/s]

Processing regions:  46%|█████████████████████████████████████████████████▋                                                         | 442/951 [00:27<00:32, 15.65it/s]

Processing regions:  47%|█████████████████████████████████████████████████▉                                                         | 444/951 [00:28<00:32, 15.78it/s]

Processing regions:  47%|██████████████████████████████████████████████████▏                                                        | 446/951 [00:28<00:32, 15.70it/s]

Processing regions:  47%|██████████████████████████████████████████████████▍                                                        | 448/951 [00:28<00:31, 15.76it/s]

Processing regions:  47%|██████████████████████████████████████████████████▋                                                        | 450/951 [00:28<00:31, 15.83it/s]

Processing regions:  48%|██████████████████████████████████████████████████▊                                                        | 452/951 [00:28<00:31, 15.84it/s]

Processing regions:  48%|███████████████████████████████████████████████████                                                        | 454/951 [00:28<00:31, 15.84it/s]

Processing regions:  48%|███████████████████████████████████████████████████▎                                                       | 456/951 [00:28<00:31, 15.89it/s]

Processing regions:  48%|███████████████████████████████████████████████████▌                                                       | 458/951 [00:28<00:30, 15.93it/s]

Processing regions:  48%|███████████████████████████████████████████████████▊                                                       | 460/951 [00:29<00:30, 15.93it/s]

Processing regions:  49%|███████████████████████████████████████████████████▉                                                       | 462/951 [00:29<00:30, 15.78it/s]

Processing regions:  49%|████████████████████████████████████████████████████▏                                                      | 464/951 [00:29<00:31, 15.49it/s]

Processing regions:  49%|████████████████████████████████████████████████████▍                                                      | 466/951 [00:29<00:31, 15.56it/s]

Processing regions:  49%|████████████████████████████████████████████████████▋                                                      | 468/951 [00:29<00:30, 15.67it/s]

Processing regions:  49%|████████████████████████████████████████████████████▉                                                      | 470/951 [00:29<00:30, 15.69it/s]

Processing regions:  50%|█████████████████████████████████████████████████████                                                      | 472/951 [00:29<00:30, 15.71it/s]

Processing regions:  50%|█████████████████████████████████████████████████████▎                                                     | 474/951 [00:30<00:30, 15.86it/s]

Processing regions:  50%|█████████████████████████████████████████████████████▌                                                     | 476/951 [00:30<00:29, 15.88it/s]

Processing regions:  50%|█████████████████████████████████████████████████████▊                                                     | 478/951 [00:30<00:29, 15.83it/s]

Processing regions:  50%|██████████████████████████████████████████████████████                                                     | 480/951 [00:30<00:29, 15.88it/s]

Processing regions:  51%|██████████████████████████████████████████████████████▏                                                    | 482/951 [00:30<00:29, 15.92it/s]

Processing regions:  51%|██████████████████████████████████████████████████████▍                                                    | 484/951 [00:30<00:29, 15.83it/s]

Processing regions:  51%|██████████████████████████████████████████████████████▋                                                    | 486/951 [00:30<00:29, 15.92it/s]

Processing regions:  51%|██████████████████████████████████████████████████████▉                                                    | 488/951 [00:30<00:28, 16.06it/s]

Processing regions:  52%|███████████████████████████████████████████████████████▏                                                   | 490/951 [00:31<00:28, 16.03it/s]

Processing regions:  52%|███████████████████████████████████████████████████████▎                                                   | 492/951 [00:31<00:28, 16.00it/s]

Processing regions:  52%|███████████████████████████████████████████████████████▌                                                   | 494/951 [00:31<00:28, 15.89it/s]

Processing regions:  52%|███████████████████████████████████████████████████████▊                                                   | 496/951 [00:31<00:28, 15.85it/s]

Processing regions:  52%|████████████████████████████████████████████████████████                                                   | 498/951 [00:31<00:28, 15.96it/s]

Processing regions:  53%|████████████████████████████████████████████████████████▎                                                  | 500/951 [00:31<00:28, 15.95it/s]

Processing regions:  53%|████████████████████████████████████████████████████████▍                                                  | 502/951 [00:31<00:28, 16.01it/s]

Processing regions:  53%|████████████████████████████████████████████████████████▋                                                  | 504/951 [00:31<00:27, 16.03it/s]

Processing regions:  53%|████████████████████████████████████████████████████████▉                                                  | 506/951 [00:32<00:27, 16.00it/s]

Processing regions:  53%|█████████████████████████████████████████████████████████▏                                                 | 508/951 [00:32<00:27, 15.96it/s]

Processing regions:  54%|█████████████████████████████████████████████████████████▍                                                 | 510/951 [00:32<00:27, 15.81it/s]

Processing regions:  54%|█████████████████████████████████████████████████████████▌                                                 | 512/951 [00:32<00:27, 15.88it/s]

Processing regions:  54%|█████████████████████████████████████████████████████████▊                                                 | 514/951 [00:32<00:27, 15.96it/s]

Processing regions:  54%|██████████████████████████████████████████████████████████                                                 | 516/951 [00:32<00:27, 16.06it/s]

Processing regions:  54%|██████████████████████████████████████████████████████████▎                                                | 518/951 [00:32<00:27, 15.95it/s]

Processing regions:  55%|██████████████████████████████████████████████████████████▌                                                | 520/951 [00:32<00:26, 15.97it/s]

Processing regions:  55%|██████████████████████████████████████████████████████████▋                                                | 522/951 [00:33<00:26, 15.97it/s]

Processing regions:  55%|██████████████████████████████████████████████████████████▉                                                | 524/951 [00:33<00:26, 15.98it/s]

Processing regions:  55%|███████████████████████████████████████████████████████████▏                                               | 526/951 [00:33<00:26, 15.85it/s]

Processing regions:  56%|███████████████████████████████████████████████████████████▍                                               | 528/951 [00:33<00:26, 15.88it/s]

Processing regions:  56%|███████████████████████████████████████████████████████████▋                                               | 530/951 [00:33<00:26, 15.89it/s]

Processing regions:  56%|███████████████████████████████████████████████████████████▊                                               | 532/951 [00:33<00:26, 15.91it/s]

Processing regions:  56%|████████████████████████████████████████████████████████████                                               | 534/951 [00:33<00:26, 15.91it/s]

Processing regions:  56%|████████████████████████████████████████████████████████████▎                                              | 536/951 [00:33<00:25, 16.04it/s]

Processing regions:  57%|████████████████████████████████████████████████████████████▌                                              | 538/951 [00:34<00:25, 16.08it/s]

Processing regions:  57%|████████████████████████████████████████████████████████████▊                                              | 540/951 [00:34<00:25, 15.97it/s]

Processing regions:  57%|████████████████████████████████████████████████████████████▉                                              | 542/951 [00:34<00:25, 15.89it/s]

Processing regions:  57%|█████████████████████████████████████████████████████████████▏                                             | 544/951 [00:34<00:25, 15.85it/s]

Processing regions:  57%|█████████████████████████████████████████████████████████████▍                                             | 546/951 [00:34<00:25, 15.82it/s]

Processing regions:  58%|█████████████████████████████████████████████████████████████▋                                             | 548/951 [00:34<00:25, 15.85it/s]

Processing regions:  58%|█████████████████████████████████████████████████████████████▉                                             | 550/951 [00:34<00:25, 15.88it/s]

Processing regions:  58%|██████████████████████████████████████████████████████████████                                             | 552/951 [00:34<00:25, 15.77it/s]

Processing regions:  58%|██████████████████████████████████████████████████████████████▎                                            | 554/951 [00:35<00:25, 15.70it/s]

Processing regions:  58%|██████████████████████████████████████████████████████████████▌                                            | 556/951 [00:35<00:25, 15.75it/s]

Processing regions:  59%|██████████████████████████████████████████████████████████████▊                                            | 558/951 [00:35<00:24, 15.72it/s]

Processing regions:  59%|███████████████████████████████████████████████████████████████                                            | 560/951 [00:35<00:24, 15.87it/s]

Processing regions:  59%|███████████████████████████████████████████████████████████████▏                                           | 562/951 [00:35<00:24, 15.91it/s]

Processing regions:  59%|███████████████████████████████████████████████████████████████▍                                           | 564/951 [00:35<00:24, 15.91it/s]

Processing regions:  60%|███████████████████████████████████████████████████████████████▋                                           | 566/951 [00:35<00:24, 15.94it/s]

Processing regions:  60%|███████████████████████████████████████████████████████████████▉                                           | 568/951 [00:35<00:24, 15.95it/s]

Processing regions:  60%|████████████████████████████████████████████████████████████████▏                                          | 570/951 [00:36<00:24, 15.80it/s]

Processing regions:  60%|████████████████████████████████████████████████████████████████▎                                          | 572/951 [00:36<00:23, 15.84it/s]

Processing regions:  60%|████████████████████████████████████████████████████████████████▌                                          | 574/951 [00:36<00:24, 15.56it/s]

Processing regions:  61%|████████████████████████████████████████████████████████████████▊                                          | 576/951 [00:36<00:23, 15.65it/s]

Processing regions:  61%|█████████████████████████████████████████████████████████████████                                          | 578/951 [00:36<00:23, 15.77it/s]

Processing regions:  61%|█████████████████████████████████████████████████████████████████▎                                         | 580/951 [00:36<00:23, 15.83it/s]

Processing regions:  61%|█████████████████████████████████████████████████████████████████▍                                         | 582/951 [00:36<00:23, 15.80it/s]

Processing regions:  61%|█████████████████████████████████████████████████████████████████▋                                         | 584/951 [00:36<00:23, 15.85it/s]

Processing regions:  62%|█████████████████████████████████████████████████████████████████▉                                         | 586/951 [00:37<00:23, 15.79it/s]

Processing regions:  62%|██████████████████████████████████████████████████████████████████▏                                        | 588/951 [00:37<00:22, 15.84it/s]

Processing regions:  62%|██████████████████████████████████████████████████████████████████▍                                        | 590/951 [00:37<00:22, 15.73it/s]

Processing regions:  62%|██████████████████████████████████████████████████████████████████▌                                        | 592/951 [00:37<00:22, 15.68it/s]

Processing regions:  62%|██████████████████████████████████████████████████████████████████▊                                        | 594/951 [00:37<00:22, 15.75it/s]

Processing regions:  63%|███████████████████████████████████████████████████████████████████                                        | 596/951 [00:37<00:22, 15.81it/s]

Processing regions:  63%|███████████████████████████████████████████████████████████████████▎                                       | 598/951 [00:37<00:22, 15.88it/s]

Processing regions:  63%|███████████████████████████████████████████████████████████████████▌                                       | 600/951 [00:37<00:22, 15.78it/s]

Processing regions:  63%|███████████████████████████████████████████████████████████████████▋                                       | 602/951 [00:38<00:22, 15.77it/s]

Processing regions:  64%|███████████████████████████████████████████████████████████████████▉                                       | 604/951 [00:38<00:21, 15.79it/s]

Processing regions:  64%|████████████████████████████████████████████████████████████████████▏                                      | 606/951 [00:38<00:21, 15.79it/s]

Processing regions:  64%|████████████████████████████████████████████████████████████████████▍                                      | 608/951 [00:38<00:21, 15.77it/s]

Processing regions:  64%|████████████████████████████████████████████████████████████████████▋                                      | 610/951 [00:38<00:21, 15.77it/s]

Processing regions:  64%|████████████████████████████████████████████████████████████████████▊                                      | 612/951 [00:38<00:21, 15.89it/s]

Processing regions:  65%|█████████████████████████████████████████████████████████████████████                                      | 614/951 [00:38<00:21, 15.89it/s]

Processing regions:  65%|█████████████████████████████████████████████████████████████████████▎                                     | 616/951 [00:38<00:21, 15.91it/s]

Processing regions:  65%|█████████████████████████████████████████████████████████████████████▌                                     | 618/951 [00:39<00:20, 15.94it/s]

Processing regions:  65%|█████████████████████████████████████████████████████████████████████▊                                     | 620/951 [00:39<00:20, 16.01it/s]

Processing regions:  65%|█████████████████████████████████████████████████████████████████████▉                                     | 622/951 [00:39<00:20, 15.85it/s]

Processing regions:  66%|██████████████████████████████████████████████████████████████████████▏                                    | 624/951 [00:39<00:20, 15.77it/s]

Processing regions:  66%|██████████████████████████████████████████████████████████████████████▍                                    | 626/951 [00:39<00:20, 15.76it/s]

Processing regions:  66%|██████████████████████████████████████████████████████████████████████▋                                    | 628/951 [00:39<00:20, 15.67it/s]

Processing regions:  66%|██████████████████████████████████████████████████████████████████████▉                                    | 630/951 [00:39<00:20, 15.78it/s]

Processing regions:  66%|███████████████████████████████████████████████████████████████████████                                    | 632/951 [00:39<00:20, 15.70it/s]

Processing regions:  67%|███████████████████████████████████████████████████████████████████████▎                                   | 634/951 [00:40<00:20, 15.59it/s]

Processing regions:  67%|███████████████████████████████████████████████████████████████████████▌                                   | 636/951 [00:40<00:20, 15.70it/s]

Processing regions:  67%|███████████████████████████████████████████████████████████████████████▊                                   | 638/951 [00:40<00:20, 15.61it/s]

Processing regions:  67%|████████████████████████████████████████████████████████████████████████                                   | 640/951 [00:40<00:19, 15.70it/s]

Processing regions:  68%|████████████████████████████████████████████████████████████████████████▏                                  | 642/951 [00:40<00:19, 15.78it/s]

Processing regions:  68%|████████████████████████████████████████████████████████████████████████▍                                  | 644/951 [00:40<00:19, 15.84it/s]

Processing regions:  68%|████████████████████████████████████████████████████████████████████████▋                                  | 646/951 [00:40<00:19, 15.84it/s]

Processing regions:  68%|████████████████████████████████████████████████████████████████████████▉                                  | 648/951 [00:40<00:19, 15.84it/s]

Processing regions:  68%|█████████████████████████████████████████████████████████████████████████▏                                 | 650/951 [00:41<00:18, 15.88it/s]

Processing regions:  69%|█████████████████████████████████████████████████████████████████████████▎                                 | 652/951 [00:41<00:18, 15.83it/s]

Processing regions:  69%|█████████████████████████████████████████████████████████████████████████▌                                 | 654/951 [00:41<00:18, 15.78it/s]

Processing regions:  69%|█████████████████████████████████████████████████████████████████████████▊                                 | 656/951 [00:41<00:19, 15.51it/s]

Processing regions:  69%|██████████████████████████████████████████████████████████████████████████                                 | 658/951 [00:41<00:19, 15.37it/s]

Processing regions:  69%|██████████████████████████████████████████████████████████████████████████▎                                | 660/951 [00:41<00:18, 15.53it/s]

Processing regions:  70%|██████████████████████████████████████████████████████████████████████████▍                                | 662/951 [00:41<00:18, 15.71it/s]

Processing regions:  70%|██████████████████████████████████████████████████████████████████████████▋                                | 664/951 [00:42<00:18, 15.77it/s]

Processing regions:  70%|██████████████████████████████████████████████████████████████████████████▉                                | 666/951 [00:42<00:18, 15.75it/s]

Processing regions:  70%|███████████████████████████████████████████████████████████████████████████▏                               | 668/951 [00:42<00:17, 15.86it/s]

Processing regions:  70%|███████████████████████████████████████████████████████████████████████████▍                               | 670/951 [00:42<00:17, 15.73it/s]

Processing regions:  71%|███████████████████████████████████████████████████████████████████████████▌                               | 672/951 [00:42<00:17, 15.78it/s]

Processing regions:  71%|███████████████████████████████████████████████████████████████████████████▊                               | 674/951 [00:42<00:17, 15.87it/s]

Processing regions:  71%|████████████████████████████████████████████████████████████████████████████                               | 676/951 [00:42<00:17, 15.82it/s]

Processing regions:  71%|████████████████████████████████████████████████████████████████████████████▎                              | 678/951 [00:42<00:17, 15.83it/s]

Processing regions:  72%|████████████████████████████████████████████████████████████████████████████▌                              | 680/951 [00:43<00:17, 15.86it/s]

Processing regions:  72%|████████████████████████████████████████████████████████████████████████████▋                              | 682/951 [00:43<00:17, 15.79it/s]

Processing regions:  72%|████████████████████████████████████████████████████████████████████████████▉                              | 684/951 [00:43<00:16, 15.86it/s]

Processing regions:  72%|█████████████████████████████████████████████████████████████████████████████▏                             | 686/951 [00:43<00:16, 15.64it/s]

Processing regions:  72%|█████████████████████████████████████████████████████████████████████████████▍                             | 688/951 [00:43<00:16, 15.72it/s]

Processing regions:  73%|█████████████████████████████████████████████████████████████████████████████▋                             | 690/951 [00:43<00:16, 15.76it/s]

Processing regions:  73%|█████████████████████████████████████████████████████████████████████████████▊                             | 692/951 [00:43<00:16, 15.76it/s]

Processing regions:  73%|██████████████████████████████████████████████████████████████████████████████                             | 694/951 [00:43<00:16, 15.83it/s]

Processing regions:  73%|██████████████████████████████████████████████████████████████████████████████▎                            | 696/951 [00:44<00:16, 15.83it/s]

Processing regions:  73%|██████████████████████████████████████████████████████████████████████████████▌                            | 698/951 [00:44<00:15, 15.87it/s]

Processing regions:  74%|██████████████████████████████████████████████████████████████████████████████▊                            | 700/951 [00:44<00:15, 15.89it/s]

Processing regions:  74%|██████████████████████████████████████████████████████████████████████████████▉                            | 702/951 [00:44<00:15, 15.74it/s]

Processing regions:  74%|███████████████████████████████████████████████████████████████████████████████▏                           | 704/951 [00:44<00:15, 15.80it/s]

Processing regions:  74%|███████████████████████████████████████████████████████████████████████████████▍                           | 706/951 [00:44<00:15, 15.84it/s]

Processing regions:  74%|███████████████████████████████████████████████████████████████████████████████▋                           | 708/951 [00:44<00:15, 15.85it/s]

Processing regions:  75%|███████████████████████████████████████████████████████████████████████████████▉                           | 710/951 [00:44<00:15, 15.87it/s]

Processing regions:  75%|████████████████████████████████████████████████████████████████████████████████                           | 712/951 [00:45<00:15, 15.84it/s]

Processing regions:  75%|████████████████████████████████████████████████████████████████████████████████▎                          | 714/951 [00:45<00:14, 15.83it/s]

Processing regions:  75%|████████████████████████████████████████████████████████████████████████████████▌                          | 716/951 [00:45<00:14, 15.76it/s]

Processing regions:  75%|████████████████████████████████████████████████████████████████████████████████▊                          | 718/951 [00:45<00:14, 15.62it/s]

Processing regions:  76%|█████████████████████████████████████████████████████████████████████████████████                          | 720/951 [00:45<00:14, 15.66it/s]

Processing regions:  76%|█████████████████████████████████████████████████████████████████████████████████▏                         | 722/951 [00:45<00:14, 15.77it/s]

Processing regions:  76%|█████████████████████████████████████████████████████████████████████████████████▍                         | 724/951 [00:45<00:14, 15.72it/s]

Processing regions:  76%|█████████████████████████████████████████████████████████████████████████████████▋                         | 726/951 [00:45<00:14, 15.81it/s]

Processing regions:  77%|█████████████████████████████████████████████████████████████████████████████████▉                         | 728/951 [00:46<00:14, 15.81it/s]

Processing regions:  77%|██████████████████████████████████████████████████████████████████████████████████▏                        | 730/951 [00:46<00:13, 15.88it/s]

Processing regions:  77%|██████████████████████████████████████████████████████████████████████████████████▎                        | 732/951 [00:46<00:13, 15.88it/s]

Processing regions:  77%|██████████████████████████████████████████████████████████████████████████████████▌                        | 734/951 [00:46<00:13, 15.76it/s]

Processing regions:  77%|██████████████████████████████████████████████████████████████████████████████████▊                        | 736/951 [00:46<00:13, 15.67it/s]

Processing regions:  78%|███████████████████████████████████████████████████████████████████████████████████                        | 738/951 [00:46<00:13, 15.39it/s]

Processing regions:  78%|███████████████████████████████████████████████████████████████████████████████████▎                       | 740/951 [00:46<00:13, 15.38it/s]

Processing regions:  78%|███████████████████████████████████████████████████████████████████████████████████▍                       | 742/951 [00:46<00:13, 15.50it/s]

Processing regions:  78%|███████████████████████████████████████████████████████████████████████████████████▋                       | 744/951 [00:47<00:13, 15.62it/s]

Processing regions:  78%|███████████████████████████████████████████████████████████████████████████████████▉                       | 746/951 [00:47<00:13, 15.75it/s]

Processing regions:  79%|████████████████████████████████████████████████████████████████████████████████████▏                      | 748/951 [00:47<00:12, 15.68it/s]

Processing regions:  79%|████████████████████████████████████████████████████████████████████████████████████▍                      | 750/951 [00:47<00:12, 15.72it/s]

Processing regions:  79%|████████████████████████████████████████████████████████████████████████████████████▌                      | 752/951 [00:47<00:12, 15.79it/s]

Processing regions:  79%|████████████████████████████████████████████████████████████████████████████████████▊                      | 754/951 [00:47<00:12, 15.86it/s]

Processing regions:  79%|█████████████████████████████████████████████████████████████████████████████████████                      | 756/951 [00:47<00:12, 15.81it/s]

Processing regions:  80%|█████████████████████████████████████████████████████████████████████████████████████▎                     | 758/951 [00:47<00:12, 15.73it/s]

Processing regions:  80%|█████████████████████████████████████████████████████████████████████████████████████▌                     | 760/951 [00:48<00:12, 15.77it/s]

Processing regions:  80%|█████████████████████████████████████████████████████████████████████████████████████▋                     | 762/951 [00:48<00:11, 15.84it/s]

Processing regions:  80%|█████████████████████████████████████████████████████████████████████████████████████▉                     | 764/951 [00:48<00:11, 15.84it/s]

Processing regions:  81%|██████████████████████████████████████████████████████████████████████████████████████▏                    | 766/951 [00:48<00:11, 15.77it/s]

Processing regions:  81%|██████████████████████████████████████████████████████████████████████████████████████▍                    | 768/951 [00:48<00:11, 15.77it/s]

Processing regions:  81%|██████████████████████████████████████████████████████████████████████████████████████▋                    | 770/951 [00:48<00:11, 15.85it/s]

Processing regions:  81%|██████████████████████████████████████████████████████████████████████████████████████▊                    | 772/951 [00:48<00:11, 15.90it/s]

Processing regions:  81%|███████████████████████████████████████████████████████████████████████████████████████                    | 774/951 [00:48<00:11, 15.82it/s]

Processing regions:  82%|███████████████████████████████████████████████████████████████████████████████████████▎                   | 776/951 [00:49<00:11, 15.83it/s]

Processing regions:  82%|███████████████████████████████████████████████████████████████████████████████████████▌                   | 778/951 [00:49<00:10, 15.80it/s]

Processing regions:  82%|███████████████████████████████████████████████████████████████████████████████████████▊                   | 780/951 [00:49<00:10, 15.77it/s]

Processing regions:  82%|███████████████████████████████████████████████████████████████████████████████████████▉                   | 782/951 [00:49<00:10, 15.67it/s]

Processing regions:  82%|████████████████████████████████████████████████████████████████████████████████████████▏                  | 784/951 [00:49<00:10, 15.71it/s]

Processing regions:  83%|████████████████████████████████████████████████████████████████████████████████████████▍                  | 786/951 [00:49<00:10, 15.66it/s]

Processing regions:  83%|████████████████████████████████████████████████████████████████████████████████████████▋                  | 788/951 [00:49<00:10, 15.74it/s]

Processing regions:  83%|████████████████████████████████████████████████████████████████████████████████████████▉                  | 790/951 [00:50<00:10, 15.79it/s]

Processing regions:  83%|█████████████████████████████████████████████████████████████████████████████████████████                  | 792/951 [00:50<00:10, 15.61it/s]

Processing regions:  83%|█████████████████████████████████████████████████████████████████████████████████████████▎                 | 794/951 [00:50<00:10, 15.40it/s]

Processing regions:  84%|█████████████████████████████████████████████████████████████████████████████████████████▌                 | 796/951 [00:50<00:10, 15.25it/s]

Processing regions:  84%|█████████████████████████████████████████████████████████████████████████████████████████▊                 | 798/951 [00:50<00:10, 15.25it/s]

Processing regions:  84%|██████████████████████████████████████████████████████████████████████████████████████████                 | 800/951 [00:50<00:09, 15.17it/s]

Processing regions:  84%|██████████████████████████████████████████████████████████████████████████████████████████▏                | 802/951 [00:50<00:09, 15.03it/s]

Processing regions:  85%|██████████████████████████████████████████████████████████████████████████████████████████▍                | 804/951 [00:50<00:09, 14.98it/s]

Processing regions:  85%|██████████████████████████████████████████████████████████████████████████████████████████▋                | 806/951 [00:51<00:09, 14.90it/s]

Processing regions:  85%|██████████████████████████████████████████████████████████████████████████████████████████▉                | 808/951 [00:51<00:09, 14.96it/s]

Processing regions:  85%|███████████████████████████████████████████████████████████████████████████████████████████▏               | 810/951 [00:51<00:09, 14.97it/s]

Processing regions:  85%|███████████████████████████████████████████████████████████████████████████████████████████▎               | 812/951 [00:51<00:09, 15.03it/s]

Processing regions:  86%|███████████████████████████████████████████████████████████████████████████████████████████▌               | 814/951 [00:51<00:08, 15.36it/s]

Processing regions:  86%|███████████████████████████████████████████████████████████████████████████████████████████▊               | 816/951 [00:51<00:08, 15.57it/s]

Processing regions:  86%|████████████████████████████████████████████████████████████████████████████████████████████               | 818/951 [00:51<00:08, 15.46it/s]

Processing regions:  86%|████████████████████████████████████████████████████████████████████████████████████████████▎              | 820/951 [00:51<00:08, 15.44it/s]

Processing regions:  86%|████████████████████████████████████████████████████████████████████████████████████████████▍              | 822/951 [00:52<00:08, 14.74it/s]

Processing regions:  87%|████████████████████████████████████████████████████████████████████████████████████████████▋              | 824/951 [00:52<00:08, 15.15it/s]

Processing regions:  87%|████████████████████████████████████████████████████████████████████████████████████████████▉              | 826/951 [00:52<00:08, 15.28it/s]

Processing regions:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▏             | 828/951 [00:52<00:08, 15.33it/s]

Processing regions:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▍             | 830/951 [00:52<00:07, 15.37it/s]

Processing regions:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▌             | 832/951 [00:52<00:07, 15.57it/s]

Processing regions:  88%|█████████████████████████████████████████████████████████████████████████████████████████████▊             | 834/951 [00:52<00:07, 15.64it/s]

Processing regions:  88%|██████████████████████████████████████████████████████████████████████████████████████████████             | 836/951 [00:53<00:07, 15.82it/s]

Processing regions:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▎            | 838/951 [00:53<00:07, 15.91it/s]

Processing regions:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▌            | 840/951 [00:53<00:06, 16.04it/s]

Processing regions:  89%|██████████████████████████████████████████████████████████████████████████████████████████████▋            | 842/951 [00:53<00:06, 15.92it/s]

Processing regions:  89%|██████████████████████████████████████████████████████████████████████████████████████████████▉            | 844/951 [00:53<00:06, 15.75it/s]

Processing regions:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▏           | 846/951 [00:53<00:06, 15.90it/s]

Processing regions:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▍           | 848/951 [00:53<00:06, 16.04it/s]

Processing regions:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▋           | 850/951 [00:53<00:06, 16.06it/s]

Processing regions:  90%|███████████████████████████████████████████████████████████████████████████████████████████████▊           | 852/951 [00:54<00:06, 16.04it/s]

Processing regions:  90%|████████████████████████████████████████████████████████████████████████████████████████████████           | 854/951 [00:54<00:06, 16.03it/s]

Processing regions:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▎          | 856/951 [00:54<00:05, 16.05it/s]

Processing regions:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▌          | 858/951 [00:54<00:05, 15.95it/s]

Processing regions:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▊          | 860/951 [00:54<00:05, 15.84it/s]

Processing regions:  91%|████████████████████████████████████████████████████████████████████████████████████████████████▉          | 862/951 [00:54<00:05, 15.92it/s]

Processing regions:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▏         | 864/951 [00:54<00:05, 15.84it/s]

Processing regions:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▍         | 866/951 [00:54<00:05, 15.81it/s]

Processing regions:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▋         | 868/951 [00:55<00:05, 15.77it/s]

Processing regions:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▉         | 870/951 [00:55<00:05, 15.85it/s]

Processing regions:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████         | 872/951 [00:55<00:05, 15.64it/s]

Processing regions:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▎        | 874/951 [00:55<00:04, 15.57it/s]

Processing regions:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▌        | 876/951 [00:55<00:04, 15.63it/s]

Processing regions:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▊        | 878/951 [00:55<00:04, 15.74it/s]

Processing regions:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████        | 880/951 [00:55<00:04, 15.74it/s]

Processing regions:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▏       | 882/951 [00:55<00:04, 15.75it/s]

Processing regions:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▍       | 884/951 [00:56<00:04, 15.75it/s]

Processing regions:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▋       | 886/951 [00:56<00:04, 15.83it/s]

Processing regions:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▉       | 888/951 [00:56<00:03, 15.76it/s]

Processing regions:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 890/951 [00:56<00:03, 15.69it/s]

Processing regions:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 892/951 [00:56<00:03, 15.68it/s]

Processing regions:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 894/951 [00:56<00:03, 15.67it/s]

Processing regions:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 896/951 [00:56<00:03, 15.70it/s]

Processing regions:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████      | 898/951 [00:56<00:03, 15.81it/s]

Processing regions:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 900/951 [00:57<00:03, 15.78it/s]

Processing regions:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 902/951 [00:57<00:03, 15.88it/s]

Processing regions:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 904/951 [00:57<00:02, 15.94it/s]

Processing regions:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 906/951 [00:57<00:02, 15.77it/s]

Processing regions:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 908/951 [00:57<00:02, 15.82it/s]

Processing regions:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 910/951 [00:57<00:02, 15.96it/s]

Processing regions:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 912/951 [00:57<00:02, 15.86it/s]

Processing regions:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 914/951 [00:57<00:02, 15.91it/s]

Processing regions:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████    | 916/951 [00:58<00:02, 15.92it/s]

Processing regions:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 918/951 [00:58<00:02, 15.97it/s]

Processing regions:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 920/951 [00:58<00:01, 15.96it/s]

Processing regions:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 922/951 [00:58<00:01, 15.88it/s]

Processing regions:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 924/951 [00:58<00:01, 15.72it/s]

Processing regions:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 926/951 [00:58<00:01, 15.80it/s]

Processing regions:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍  | 928/951 [00:58<00:01, 15.72it/s]

Processing regions:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 930/951 [00:58<00:01, 15.74it/s]

Processing regions:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 932/951 [00:59<00:01, 15.73it/s]

Processing regions:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████  | 934/951 [00:59<00:01, 15.74it/s]

Processing regions:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 936/951 [00:59<00:00, 15.74it/s]

Processing regions:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 938/951 [00:59<00:00, 15.61it/s]

Processing regions:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 940/951 [00:59<00:00, 15.67it/s]

Processing regions:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 942/951 [00:59<00:00, 15.64it/s]

Processing regions:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 944/951 [00:59<00:00, 15.73it/s]

Processing regions:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 946/951 [00:59<00:00, 15.68it/s]

Processing regions: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 948/951 [01:00<00:00, 15.78it/s]

Processing regions: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 950/951 [01:00<00:00, 15.74it/s]

Processing regions: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 951/951 [01:00<00:00, 15.77it/s]

,region_id,npix_region,npix_edge_ring,F_Halpha_sum,F_Halpha_e_sum,SNR_Halpha_sum,Halpha_b_edge,F_Hbeta_sum,F_Hbeta_e_sum,SNR_Hbeta_sum,...,SNR_[SII]6731_sum,[SII]6731_b_edge,F_[NII]6583_sum,F_[NII]6583_e_sum,SNR_[NII]6583_sum,[NII]6583_b_edge,F_[OII]3727_sum,F_[OII]3727_e_sum,SNR_[OII]3727_sum,[OII]3727_b_edge
0,1,179,55,3.858374e-15,7.468326e-17,51.663175,1.659721e-17,1.558797e-15,5.766601e-17,27.031466,...,11.779853,2.975737e-18,5.273124e-16,5.095991e-17,10.347592,4.162168e-18,5.186984e-15,3.518229e-16,14.743170,3.561309e-17
1,2,78,35,3.262498e-15,4.487835e-17,72.696481,3.805376e-17,1.012764e-15,3.117466e-17,32.486789,...,18.144496,6.528019e-18,5.829729e-16,3.035203e-17,19.207047,7.306013e-18,3.858612e-15,2.097617e-16,18.395217,4.161963e-17
2,3,121,43,4.524758e-15,5.662034e-17,79.914003,3.372933e-17,1.261133e-15,3.527540e-17,35.751058,...,13.148577,4.069801e-18,7.116577e-16,3.790824e-17,18.773164,6.611195e-18,5.532205e-15,2.748928e-16,20.124953,4.348820e-17
3,4,1234,134,1.086479e-13,2.382547e-16,456.015862,3.520497e-17,3.460606e-14,2.811621e-16,123.082253,...,47.765509,5.135782e-18,1.346335e-14,1.628935e-16,82.651228,6.703744e-18,9.758179e-14,1.056096e-15,92.398640,4.283672e-17
4,5,102,38,2.373380e-15,4.305881e-17,55.119508,2.015897e-17,7.151262e-16,2.920303e-17,24.488086,...,16.726764,4.864538e-18,5.680846e-16,3.118099e-17,18.218942,5.054407e-18,4.549972e-15,2.252569e-16,20.199034,3.933224e-17

In [10]:
# Any regions with empty masks?
print("Regions with npix_region == 0:", (flux_catalog_df["npix_region"] == 0).sum())

# Any maps with NaN b_edge because the ring had no valid pixels?
for name in maps:
    n_nan = flux_catalog_df[f"{name}_b_edge"].isna().sum()
    print(f"{name}: NaN edge backgrounds = {n_nan}")

# # Show some SNR stats
# for name in maps:
#     print(name, "SNR_bgsub median:", np.nanmedian(flux_catalog_df[f"{name}_SNR_bgsub"]))

Regions with npix_region == 0: 0
Halpha: NaN edge backgrounds = 0
Hbeta: NaN edge backgrounds = 0
[OIII]5007: NaN edge backgrounds = 0
[SII]6716: NaN edge backgrounds = 0
[SII]6731: NaN edge backgrounds = 0
[NII]6583: NaN edge backgrounds = 0
[OII]3727: NaN edge backgrounds = 0

In [11]:
# Reset indices to guarantee alignment by row order
flux_df  = flux_catalog_df.reset_index(drop=True)
peaks_df2 = peaks_df.reset_index(drop=True)
boundary_df2 = boundary_metric_df.reset_index(drop=True)

# Concatenate column-wise
merged_df = pd.concat([flux_df, peaks_df2, boundary_df2, int_flux_df], axis=1)

# Remove duplicate column names (keep first occurrence)
merged_df = merged_df.loc[:, ~merged_df.columns.duplicated()]

merged_df.head()

,region_id,npix_region,npix_edge_ring,F_Halpha_sum,F_Halpha_e_sum,SNR_Halpha_sum,Halpha_b_edge,F_Hbeta_sum,F_Hbeta_e_sum,SNR_Hbeta_sum,...,radius_p16_pc,radius_p50_pc,radius_p84_pc,radius_areaeq_px,radius_areaeq_pc,boundary_method,area_px_after_carve,radius_areaeq_px_after_carve,radius_areaeq_pc_after_carve,id_int
0,1.0,179.0,55.0,3.858374e-15,7.468326e-17,51.663175,1.659721e-17,1.558797e-15,5.766601e-17,27.031466,...,5.111735,8.437418,14.151279,7.548342,9.947589,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,179.0,7.548342,9.947589,0
1,2.0,78.0,35.0,3.262498e-15,4.487835e-17,72.696481,3.805376e-17,1.012764e-15,3.117466e-17,32.486789,...,4.012951,6.001676,8.671066,4.982787,6.566571,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,78.0,4.982787,6.566571,1
2,3.0,121.0,43.0,4.524758e-15,5.662034e-17,79.914003,3.372933e-17,1.261133e-15,3.527540e-17,35.751058,...,6.305603,7.907105,10.542807,6.206085,8.178695,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,121.0,6.206085,8.178695,2
3,4.0,1234.0,134.0,1.086479e-13,2.382547e-16,456.015862,3.520497e-17,3.460606e-14,2.811621e-16,123.082253,...,7.907105,28.020087,35.596000,19.819041,26.118541,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,1234.0,19.819041,26.118541,3
4,5.0,102.0,38.0,2.373380e-15,4.305881e-17,55.119508,2.015897e-17,7.151262e-16,2.920303e-17,24.488086,...,5.271403,7.907105,9.448363,5.698035,7.509161,ANG_MAD+SLOPE+NEIGH+SG+CLAMP,102.0,5.698035,7.509161,4

In [12]:
for col in merged_df.columns:
    print(col)

region_id
npix_region
npix_edge_ring
F_Halpha_sum
F_Halpha_e_sum
SNR_Halpha_sum
Halpha_b_edge
F_Hbeta_sum
F_Hbeta_e_sum
SNR_Hbeta_sum
Hbeta_b_edge
F_[OIII]5007_sum
F_[OIII]5007_e_sum
SNR_[OIII]5007_sum
[OIII]5007_b_edge
F_[SII]6716_sum
F_[SII]6716_e_sum
SNR_[SII]6716_sum
[SII]6716_b_edge
F_[SII]6731_sum
F_[SII]6731_e_sum
SNR_[SII]6731_sum
[SII]6731_b_edge
F_[NII]6583_sum
F_[NII]6583_e_sum
SNR_[NII]6583_sum
[NII]6583_b_edge
F_[OII]3727_sum
F_[OII]3727_e_sum
SNR_[OII]3727_sum
[OII]3727_b_edge
field
y
x
removed_by_saddle
removed_by_edge
kind
center_x_px
center_y_px
zoi_center_label
bg_local
sigma_local
radius_p16_px
radius_p50_px
radius_p84_px
radius_p16_pc
radius_p50_pc
radius_p84_pc
radius_areaeq_px
radius_areaeq_pc
boundary_method
area_px_after_carve
radius_areaeq_px_after_carve
radius_areaeq_pc_after_carve
id_int

<span id="papermill-error-cell" style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">Execution using papermill encountered an exception here and stopped:</span>

In [13]:
# === Extinction (E(B-V), A_V) + dereddening for BOTH raw and bgsub fluxes, plus RA/Dec, R_gal, and BPT classes ===

import numpy as np
import pandas as pd

from astropy.wcs import WCS
from astropy.coordinates import SkyCoord, SkyOffsetFrame
import astropy.units as u

# -----------------------------
# 0) User-tunable parameters
# -----------------------------
INTRINSIC_HA_HB = 2.86
R_V = 3.1

# M33 geometry (EDIT if you use different values)
M33_CENTER = SkyCoord("01h33m50.9s", "+30d39m36.8s", frame="icrs")
M33_INCL = np.deg2rad(56.0)   # radians
M33_PA   = np.deg2rad(23.0)   # radians (E of N)
M33_D_KPC = 840.0             # distance in kpc

ASSUME_1_BASED_PIXELS = False  # set True if peaks x/y are 1-based (DS9 style)

# Integrated error column suffix
ERR_SUFFIX = "_e"

# Lines and wavelengths (Angstrom)
LINE_WAVES = {
    "Hbeta":       4861.0,
    "[OIII]5007": 5007.0,
    "Halpha":       6563.0,
    "[NII]6583":  6584.0,
    "[SII]6716":  6716.0,
    "[SII]6731":  6731.0,
    "[OII]3727":  3727.0,
}

# -----------------------------
# 1) CCM89 extinction curve: k(lambda) = A(lambda) / E(B-V)
# -----------------------------
def ccm89_k_lambda(wave_angstrom, R_V=3.1):
    wave_micron = wave_angstrom * 1e-4  # Å -> μm
    x = 1.0 / wave_micron               # inverse microns

    # Optical/NIR: 1.1 <= x <= 3.3
    y = x - 1.82
    a = (1
         + 0.17699 * y
         - 0.50447 * y**2
         - 0.02427 * y**3
         + 0.72085 * y**4
         + 0.01979 * y**5
         - 0.77530 * y**6
         + 0.32999 * y**7)
    b = (1.41338 * y
         + 2.28305 * y**2
         + 1.07233 * y**3
         - 5.38434 * y**4
         - 0.62251 * y**5
         + 5.30260 * y**6
         - 2.09002 * y**7)
    return a * R_V + b

k_Ha = ccm89_k_lambda(6563.0, R_V=R_V)
k_Hb = ccm89_k_lambda(4861.0, R_V=R_V)
delta_k = k_Hb - k_Ha
ln10 = np.log(10.0)

# -----------------------------
# 2) Helper: compute EBV/AV + deredden for a given flux suffix
#    This runs twice: once for _F_raw and once for _F_bgsub
# -----------------------------
def add_extinction_and_deredden(df, flux_suffix, prefix):
    """
    Computes E(B-V), A_V from Ha/Hb using:
      Ha = df[f"Halpha{flux_suffix}"], Hb = df[f"Hbeta{flux_suffix}"]
    Uses integrated uncertainties:
      eHa = df[f"Halpha{ERR_SUFFIX}"], eHb = df[f"Hbeta{ERR_SUFFIX}"]

    Outputs (examples for prefix='raw'):
      raw_Ha_Hb_obs, raw_E_BV, raw_A_V, raw_Halpha_F_dered, raw_Halpha_sigma_F_dered, ...
      raw_log_NII_Ha, raw_log_OIII_Hb, raw_BPT_class
    """
    # --- Balmer decrement ---
    Ha  = df[f"F_Halpha{flux_suffix}"].to_numpy(dtype=float)
    Hb  = df[f"F_Hbeta{flux_suffix}"].to_numpy(dtype=float)
    eHa = df[f"F_Halpha{ERR_SUFFIX}{flux_suffix}"].to_numpy(dtype=float)
    eHb = df[f"F_Hbeta{ERR_SUFFIX}{flux_suffix}"].to_numpy(dtype=float)

    good = np.isfinite(Ha) & np.isfinite(Hb) & np.isfinite(eHa) & np.isfinite(eHb) & (Ha > 0) & (Hb > 0) & (eHa >= 0) & (eHb >= 0)

    ratio = np.full(len(df), np.nan, dtype=float)
    ratio_err = np.full(len(df), np.nan, dtype=float)

    ratio[good] = Ha[good] / Hb[good]
    ratio_err[good] = ratio[good] * np.sqrt((eHa[good]/Ha[good])**2 + (eHb[good]/Hb[good])**2)

    with np.errstate(divide="ignore", invalid="ignore"):
        ebv = (2.5 / delta_k) * np.log10(ratio / INTRINSIC_HA_HB)

    # Clip negative extinction to 0 (common practical choice)
    ebv = np.where(np.isfinite(ebv), ebv, np.nan)
    ebv = np.clip(ebv, 0, None)

    # Uncertainty propagation: dE/dR = (2.5/delta_k)/(ln10 * R)
    A = (2.5 / delta_k)
    with np.errstate(divide="ignore", invalid="ignore"):
        dE_dR = A / (ln10 * ratio)
        ebv_err = np.abs(dE_dR) * ratio_err

    Av = R_V * ebv
    Av_err = R_V * ebv_err

    df[f"{prefix}_Ha_Hb_obs"] = ratio
    df[f"{prefix}_Ha_Hb_obs_err"] = ratio_err
    df[f"{prefix}_E_BV"] = ebv
    df[f"{prefix}_E_BV_err"] = ebv_err
    df[f"{prefix}_A_V"] = Av
    df[f"{prefix}_A_V_err"] = Av_err

    # --- Deredden all lines ---
    E = ebv
    eE = ebv_err

    for line, wave in LINE_WAVES.items():
        
        Fcol = f"F_{line}{flux_suffix}"
        ecol = f"F_{line}{ERR_SUFFIX}{flux_suffix}"
        if (Fcol not in df.columns) or (ecol not in df.columns):
            continue

        F = df[Fcol].to_numpy(dtype=float)
        eF = df[ecol].to_numpy(dtype=float)

        k = ccm89_k_lambda(wave, R_V=R_V)
        C = 10.0 ** (0.4 * E * k)
        F_dered = F * C

        # sigma(F_dered)^2 = (C*sigma_F)^2 + (F * dC/dE * sigma_E)^2
        dC_dE = C * (0.4 * ln10 * k)
        eF_dered = np.sqrt((C * eF)**2 + (F * dC_dE * eE)**2)

        df[f"F_{line}_{prefix}_dered"] = F_dered
        df[f"F_{line}_e_{prefix}_dered"] = eF_dered

    # --- BPT classification using DEREDDENED fluxes for this prefix ---
    nii  = df.get(f"F_[NII]6583_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    nii_err = df.get(f"F_[NII]6583_e_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    ha0  = df.get(f"F_Halpha_{prefix}_dered",      pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    ha0_err = df.get(f"F_Halpha_e_{prefix}_dered",      pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    oiii = df.get(f"F_[OIII]5007_{prefix}_dered",pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    oiii_err = df.get(f"F_[OIII]5007_e_{prefix}_dered",pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    hb0  = df.get(f"F_Hbeta_{prefix}_dered",      pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    hb_err = df.get(f"F_Hbeta_e_{prefix}_dered",      pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    sii = df.get(f"F_[SII]6716_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float) + \
          df.get(f"F_[SII]6731_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)
    sii_err = np.sqrt(df.get(f"F_[SII]6716_e_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)**2 +
                      df.get(f"F_[SII]6731_e_{prefix}_dered", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)**2)
    good_bpt = np.isfinite(nii) & np.isfinite(ha0) & np.isfinite(oiii) & np.isfinite(hb0) & (nii > 0) & (ha0 > 0) & (oiii > 0) & (hb0 > 0)
    print(f"{prefix}: {np.sum(good_bpt)} valid points for BPT classification")
    
    log_NII_Ha = np.full(len(df), np.nan, dtype=float)
    log_OIII_Hb = np.full(len(df), np.nan, dtype=float)
    log_SII_Ha = np.full(len(df), np.nan, dtype=float)
    log_NII_Ha[good_bpt] = np.log10(nii[good_bpt] / ha0[good_bpt])
    log_OIII_Hb[good_bpt] = np.log10(oiii[good_bpt] / hb0[good_bpt])
    log_SII_Ha[good_bpt] = np.log10(sii[good_bpt] / ha0[good_bpt])
    
    # #also add error in ratios for plotting
    log_NII_Ha_err = np.full(len(df), np.nan, dtype=float)
    log_OIII_Hb_err = np.full(len(df), np.nan, dtype=float)
    log_SII_Ha_err = np.full(len(df), np.nan, dtype=float)
    log_NII_Ha_err[good_bpt] = np.sqrt((nii_err[good_bpt] / nii[good_bpt])**2 + (ha0_err[good_bpt] / ha0[good_bpt])**2) / np.log(10)
    log_OIII_Hb_err[good_bpt] = np.sqrt((oiii_err[good_bpt] / oiii[good_bpt])**2 + (hb_err[good_bpt] / hb0[good_bpt])**2) / np.log(10)
    log_SII_Ha_err[good_bpt] = np.sqrt((sii_err[good_bpt] / sii[good_bpt])**2 + (ha0_err[good_bpt] / ha0[good_bpt])**2) / np.log(10)

    xB = log_NII_Ha
    yB = log_OIII_Hb

    kewley_y = 0.61 / (xB - 0.47) + 1.19
    kauff_y  = 0.61 / (xB - 0.05) + 1.30

    bpt_class = np.full(len(df), "Unclassified", dtype=object)
    finite = np.isfinite(xB) & np.isfinite(yB)
    bpt_class[finite & (yB < kauff_y)] = "Star-forming"
    bpt_class[finite & (yB >= kauff_y) & (yB < kewley_y)] = "Composite"
    bpt_class[finite & (yB >= kewley_y)] = "AGN/Shock"

    df[f"log_NII_Ha_{prefix}_dered"] = log_NII_Ha
    df[f"log_NII_Ha_err_{prefix}_dered"] = log_NII_Ha_err
    df[f"log_OIII_Hb_{prefix}_dered"] = log_OIII_Hb
    df[f"log_OIII_Hb_err_{prefix}_dered"] = log_OIII_Hb_err
    df[f"log_SII_Ha_{prefix}_dered"] = log_SII_Ha
    df[f"log_SII_Ha_err_{prefix}_dered"] = log_SII_Ha_err
    df[f"BPT_class_{prefix}_dered"] = bpt_class

    return df

# -----------------------------
# 3) Run on BOTH raw and integrated fluxes
# -----------------------------
df = merged_df  # work on your merged catalog
df = add_extinction_and_deredden(df, flux_suffix="_sum",   prefix="sum")
df = add_extinction_and_deredden(df, flux_suffix="_int", prefix="int")

# -----------------------------
# 4) Add RA/Dec from WCS using peaks_df x,y (row-aligned)
# -----------------------------
w = WCS(ha_flux_header)

x = peaks_df["x"].to_numpy(dtype=float)
y = peaks_df["y"].to_numpy(dtype=float)
if ASSUME_1_BASED_PIXELS:
    x = x - 1.0
    y = y - 1.0

ra_deg, dec_deg = w.pixel_to_world_values(x, y)
df["RA_deg"] = ra_deg
df["Dec_deg"] = dec_deg

# -----------------------------
# 5) Galactocentric radius (deprojected) in kpc
# -----------------------------
coords = SkyCoord(ra=df["RA_deg"].to_numpy() * u.deg,
                  dec=df["Dec_deg"].to_numpy() * u.deg,
                  frame="icrs")

offset_frame = SkyOffsetFrame(origin=M33_CENTER)
off = coords.transform_to(offset_frame)

x_east_kpc  = off.lon.to(u.radian).value * M33_D_KPC
y_north_kpc = off.lat.to(u.radian).value * M33_D_KPC

sinPA, cosPA = np.sin(M33_PA), np.cos(M33_PA)
x_major = x_east_kpc * sinPA + y_north_kpc * cosPA
y_minor = x_east_kpc * cosPA - y_north_kpc * sinPA

y_minor_deproj = y_minor / np.cos(M33_INCL)
df["R_gal_kpc"] = np.sqrt(x_major**2 + y_minor_deproj**2)

# Write back
merged_df = df

#print all the new column names:
for col in merged_df.columns:
    print(col)

sum: 934 valid points for BPT classification

/var/folders/90/nb83zn5j00bc53x6bcv0jcwm0000gn/T/ipykernel_84840/1160896080.py:167: RuntimeWarning: invalid value encountered in log10
  log_SII_Ha[good_bpt] = np.log10(sii[good_bpt] / ha0[good_bpt])

KeyError: 'F_Halpha_int'

In [ ]:
DIST_MPC = 0.84  # M33 distance in Mpc (commonly ~0.84–0.85)

# ---- Flux -> luminosity conversion ----
# L = 4*pi*D^2*F, with D in cm if F is erg/s/cm^2
PC_CM = 3.085677581e18
D_cm = DIST_MPC * 1e6 * PC_CM
four_pi_D2 = 4.0 * np.pi * (D_cm**2)

# ---- Halpha flux columns that already exist in your catalog ----
# observed:
F_ha_raw   = merged_df["F_Halpha_sum"].to_numpy(dtype=float)
F_ha_int = merged_df["F_Halpha_int"].to_numpy(dtype=float)

# dereddened (created by the earlier cell):
F_ha_raw_dered   = merged_df["F_Halpha_sum_dered"].to_numpy(dtype=float)
F_ha_int_dered = merged_df["F_Halpha_int_dered"].to_numpy(dtype=float)

# ---- Add luminosity columns (erg/s if flux is erg/s/cm^2) ----
merged_df["L_Ha_sum"] = four_pi_D2 * F_ha_raw
merged_df["L_Ha_int"] = four_pi_D2 * F_ha_int
merged_df["L_Ha_sum_dered"] = four_pi_D2 * F_ha_raw_dered
merged_df["L_Ha_int_dered"] = four_pi_D2 * F_ha_int_dered

#add a column for log luminosity as well:
merged_df["log_L_Ha_sum"] = np.log10(merged_df["L_Ha_sum"])
merged_df["log_L_Ha_int"] = np.log10(merged_df["L_Ha_int"])
merged_df["log_L_Ha_sum_dered"] = np.log10(merged_df["L_Ha_sum_dered"])
merged_df["log_L_Ha_int_dered"] = np.log10(merged_df["L_Ha_int_dered"])

print("Added:", ["L_Ha_sum", "L_Ha_sum_dered"])

In [ ]:
outdir = "CATALOGS/flux_catalogs/"
os.makedirs(outdir, exist_ok=True)

outfile = os.path.join(outdir, f"flux_catalog_{field}.csv")
merged_df.to_csv(outfile, index=False)

print("Saved:", outfile)
print("Rows:", len(merged_df), "Cols:", len(merged_df.columns))

In [ ]:
#make a folder to save plots
figure_dir = "plots/individual_field_flux_plots"
os.makedirs(figure_dir, exist_ok=True)

In [ ]:
# Compute BPT points

prefix = 'int'
x_raw, y_raw = merged_df[f'log_NII_Ha_{prefix}_dered'].to_numpy(dtype=float), merged_df[f'log_OIII_Hb_{prefix}_dered'].to_numpy(dtype=float)
# x_bg,  y_bg  = bpt_xy(merged_df, use_bgsub=True)

# Demarcation curves (classic BPT)
x_curve = np.linspace(-2.0, 0.6, 600)
kewley = 0.61 / (x_curve - 0.47) + 1.19      # Kewley+2001
kauff  = 0.61 / (x_curve - 0.05) + 1.30      # Kauffmann+2003

# ---- Plot: overlay raw vs corrected in one figure ----
plt.figure(figsize=(7.5, 6.5))

classes = ["Star-forming", "Composite", "AGN/Shock", "Unclassified"]
colors = ['blue', 'green', 'red', 'grey']
for cls in classes:
    mask = (merged_df[f'BPT_class_{prefix}_dered'] == cls)
    plt.scatter(x_raw[mask], y_raw[mask], s=18, alpha=0.5, label=cls, color=colors[classes.index(cls)])
# #color by BPT class
# plt.scatter(x_raw[merged_df['raw_BPT_class'] == 'star-forming'], 
#             y_raw[merged_df['raw_BPT_class'] == 'star-forming'], s=18, alpha=0.5, label="Star-forming")
# # plt.scatter(x_bg,  y_bg,  s=18, alpha=0.5, label="Background-subtracted (edge threshold)")

plt.plot(x_curve, kewley, linestyle="--", label="Kewley+01", color = 'k')
plt.plot(x_curve, kauff,  linestyle="-.", label="Kauffmann+03", color = 'k')

plt.xlabel(r'$\log_{10}([NII]6583 / H\alpha)$')
plt.ylabel(r'$\log_{10}([OIII]5007 / H\beta)$')
plt.title(f"{field}, {prefix} \nStar-forming:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Star-forming'])}  Composite:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Composite'])}  AGN/Shock:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'AGN/Shock'])}  Unclassified:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Unclassified'])}")

plt.xlim(-2, 0.4)
plt.ylim(-2.5, 2)
plt.grid(alpha=0.3)
plt.legend(frameon=True)
plt.tight_layout()
plt.savefig(os.path.join(figure_dir, f"BPT_{field}_{prefix}.png"), dpi=150)
plt.show()

In [ ]:
# Compute BPT points

prefix = 'sum'
x_raw, y_raw = merged_df[f'log_NII_Ha_{prefix}_dered'].to_numpy(dtype=float), merged_df[f'log_OIII_Hb_{prefix}_dered'].to_numpy(dtype=float)
# x_bg,  y_bg  = bpt_xy(merged_df, use_bgsub=True)

# Demarcation curves (classic BPT)
x_curve = np.linspace(-2.0, 0.6, 600)
kewley = 0.61 / (x_curve - 0.47) + 1.19      # Kewley+2001
kauff  = 0.61 / (x_curve - 0.05) + 1.30      # Kauffmann+2003

# ---- Plot: overlay raw vs corrected in one figure ----
plt.figure(figsize=(7.5, 6.5))

classes = ["Star-forming", "Composite", "AGN/Shock", "Unclassified"]
colors = ['blue', 'green', 'red', 'grey']
for cls in classes:
    mask = (merged_df[f'BPT_class_{prefix}_dered'] == cls)
    plt.scatter(x_raw[mask], y_raw[mask], s=18, alpha=0.5, label=cls, color=colors[classes.index(cls)])
# #color by BPT class
# plt.scatter(x_raw[merged_df['raw_BPT_class'] == 'star-forming'], 
#             y_raw[merged_df['raw_BPT_class'] == 'star-forming'], s=18, alpha=0.5, label="Star-forming")
# # plt.scatter(x_bg,  y_bg,  s=18, alpha=0.5, label="Background-subtracted (edge threshold)")

plt.plot(x_curve, kewley, linestyle="--", label="Kewley+01", color = 'k')
plt.plot(x_curve, kauff,  linestyle="-.", label="Kauffmann+03", color = 'k')

plt.xlabel(r'$\log_{10}([NII]6583 / H\alpha)$')
plt.ylabel(r'$\log_{10}([OIII]5007 / H\beta)$')
plt.title(f"{field}, {prefix} \nStar-forming:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Star-forming'])}  Composite:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Composite'])}  AGN/Shock:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'AGN/Shock'])}  Unclassified:{len(merged_df[merged_df[f'BPT_class_{prefix}_dered'] == 'Unclassified'])}")

plt.xlim(-2, 0.4)
plt.ylim(-2.5, 2)
plt.grid(alpha=0.3)
plt.legend(frameon=True)
plt.tight_layout()
plt.savefig(os.path.join(figure_dir, f"BPT_{field}_{prefix}.png"), dpi=150)
plt.show()

In [ ]:
def plot_field_overlay_halpha_peaks_zoi_boundaries(
    catalog_df,
    ha_fits_path,
    zoi_label_map,
    boundary_label_map,
    field_name=None,
    x_col="x",
    y_col="y",
    region_label_col="zoi_center_label",
    region_id_col="region_id",
    xlim=None,
    ylim=None,
    show_peaks=True,
    show_zoi=True,
    show_boundaries=True,
    peaks_kwargs=None,
    zoi_color="cyan",
    boundary_color="magenta",
    zoi_lw=0.8,
    boundary_lw=1.1,
    alpha_zoi=0.65,
    alpha_boundary=0.9,
    # NEW: LogNorm controls
    ha_percentiles=(5, 99),         # global vmin/vmax percentiles (positive pixels only)
    use_local_lognorm=False,        # if True and xlim/ylim provided -> compute per-view norm
    local_percentiles=(3.0, 99.7),  # per-view percentiles (positive pixels only)
    min_pos_pixels=20,              # minimum positive pixels required to trust local percentiles
    eps_pos=None,                   # epsilon floor for vmin (defaults to nextafter(0,1))
    savepath=None,
    line = 'Halpha'
):
    """
    Overplot peaks + ZOI outlines + boundary outlines on the Halpha map, using LogNorm scaling.

    Parameters
    ----------
    catalog_df : pandas.DataFrame
        Must include x_col/y_col; should include region_label_col (integer ZOI label at center).
    ha_fits_path : str
        Path to Halpha FITS.
    zoi_label_map : 2D array
        Integer-labeled ZOI map (0 outside).
    boundary_label_map : 2D array
        Integer-labeled boundary map (0 outside).
    field_name : str
        Optional display name.
    xlim, ylim : (min,max) or None
        Plot limits in pixel coordinates.
    ha_percentiles : (lo, hi)
        Percentiles used for global LogNorm vmin/vmax (positive finite pixels only).
    use_local_lognorm : bool
        If True and xlim/ylim are given, compute per-view LogNorm using local_percentiles,
        falling back to global if too few positive pixels.
    """

    import numpy as np
    import matplotlib.pyplot as plt
    from astropy.io import fits
    from matplotlib.colors import LogNorm

    # Lazy import so this cell works even if skimage isn't installed elsewhere
    try:
        from skimage.segmentation import find_boundaries  # noqa: F401  (kept as in your original)
    except Exception as e:
        raise ImportError(
            "This plotting function requires scikit-image. "
            "Install with: pip install scikit-image"
        ) from e

    if eps_pos is None:
        eps_pos = np.nextafter(0, 1)

    # --- Field name ---
    if field_name is None:
        field_name = (
            str(catalog_df.get("field", ["Field"]).iloc[0])
            if hasattr(catalog_df, "iloc")
            else "Field"
        )

    # --- Load Halpha map ---
    ha = fits.getdata(ha_fits_path)
    ha = np.where(np.isfinite(ha), ha, np.nan)

    # --- Compute GLOBAL LogNorm vmin/vmax from positive finite pixels ---
    valid_pos = ha[np.isfinite(ha) & (ha > 0)]
    if valid_pos.size == 0:
        raise ValueError("Hα map has no positive finite values for LogNorm.")

    vmin_global = np.nanpercentile(valid_pos, ha_percentiles[0])
    vmax_global = np.nanpercentile(valid_pos, ha_percentiles[1])

    # Fallback if percentiles are degenerate
    if (not np.isfinite(vmin_global)) or (not np.isfinite(vmax_global)) or (vmax_global <= vmin_global):
        vmin_global, vmax_global = np.nanmin(valid_pos), np.nanmax(valid_pos)
        if (not np.isfinite(vmin_global)) or (not np.isfinite(vmax_global)) or (vmax_global <= vmin_global):
            raise ValueError("Failed to compute valid global vmin/vmax for Hα.")

    vmin_global = max(vmin_global, eps_pos)

    def _local_lognorm(arr2d):
        """Compute a per-view LogNorm using positive finite pixels, fallback to global."""
        pos = arr2d[np.isfinite(arr2d) & (arr2d > 0)]
        vmin_loc, vmax_loc = vmin_global, vmax_global

        if pos.size >= min_pos_pixels:
            lo = np.nanpercentile(pos, local_percentiles[0])
            hi = np.nanpercentile(pos, local_percentiles[1])
            if np.isfinite(lo) and np.isfinite(hi) and hi > lo:
                vmin_loc, vmax_loc = lo, hi

        vmin_loc = max(vmin_loc, eps_pos)
        if (not np.isfinite(vmax_loc)) or (vmax_loc <= vmin_loc):
            vmax_loc = vmin_loc * 1.01
        return LogNorm(vmin=vmin_loc, vmax=vmax_loc)

    # Decide norm: global or local-per-view
    norm = LogNorm(vmin=vmin_global, vmax=vmax_global)
    if use_local_lognorm and (xlim is not None) and (ylim is not None):
        # Clip indices safely and compute norm on that view
        x0, x1 = sorted([int(np.floor(xlim[0])), int(np.ceil(xlim[1]))])
        y0, y1 = sorted([int(np.floor(ylim[0])), int(np.ceil(ylim[1]))])
        x0 = max(0, x0); y0 = max(0, y0)
        x1 = min(ha.shape[1], x1); y1 = min(ha.shape[0], y1)
        view = ha[y0:y1, x0:x1]
        if view.size > 0:
            norm = _local_lognorm(view)

    # --- Ensure integer maps ---
    zoi_int = np.rint(np.nan_to_num(zoi_label_map, nan=0)).astype(np.int32)
    bnd_int = np.rint(np.nan_to_num(boundary_label_map, nan=0)).astype(np.int32)

    # --- Figure ---
    fig, ax = plt.subplots(figsize=(10, 10 * ha.shape[0] / ha.shape[1]))

    # Make NaNs white
    cmap_gray = plt.get_cmap("gray").copy()
    cmap_gray.set_bad(color="white")

    # IMPORTANT CHANGE: show ha (linear) with LogNorm (not log10(ha))
    im = ax.imshow(ha, origin="lower", cmap=cmap_gray, norm=norm)

    # --- Overlay outlines ---
    labels_from_catalog = None
    if hasattr(catalog_df, "columns") and (region_label_col in catalog_df.columns):
        labels_from_catalog = sorted({
            int(v) for v in catalog_df[region_label_col].values
            if np.isfinite(v) and int(v) > 0
        })

    if labels_from_catalog and len(labels_from_catalog) > 0:
        labels = labels_from_catalog
    else:
        labels = sorted([int(v) for v in np.unique(bnd_int) if v > 0])

    # NOTE: your original code contours the entire label maps at 0.5, which is fine.
    if show_zoi and np.isfinite(zoi_int).any():
        edge = np.nan_to_num(zoi_int, nan=0.0)
        ax.contour(edge, levels=[0.5], colors=[zoi_color], linewidths=zoi_lw,
                   origin="lower", zorder=1, alpha=alpha_zoi)
    if show_boundaries and np.isfinite(bnd_int).any():
        edge = np.nan_to_num(bnd_int, nan=0.0)
        ax.contour(edge, levels=[0.5], colors=[boundary_color], linewidths=boundary_lw,
                   origin="lower", zorder=1, alpha=alpha_boundary)

    # --- Plot peak centers ---
    if show_peaks:
        if peaks_kwargs is None:
            peaks_kwargs = dict(marker="+", s=18, linewidths=0.8, alpha=0.85)
        xs = catalog_df[x_col].astype(float).values
        ys = catalog_df[y_col].astype(float).values
        ax.scatter(xs, ys, color="k", **peaks_kwargs, label="Peaks")

    # --- Colorbar ---
    cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label(r"Flux (LogNorm)")

    # --- Aesthetics ---
    ax.set_title(f"{line} with Peaks, ZOI (cyan), Boundaries (magenta)")
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_facecolor("white")
    fig.patch.set_facecolor("white")

    # Limits
    if xlim is not None:
        ax.set_xlim(*xlim)
    if ylim is not None:
        ax.set_ylim(*ylim)

    if show_peaks:
        ax.legend(loc="upper right", frameon=True)

    plt.tight_layout()

    if savepath:
        plt.savefig(savepath, bbox_inches="tight", dpi=300, facecolor="white")
        print(f"[done] Saved overlay plot: {savepath}")

    plt.show()
    plt.close(fig)
    return fig, ax

In [ ]:
"""
Runs the full-field overlay plot using the variables created earlier in the notebook.
"""
# Example usage (matches your earlier variables):
# - combined: your peak catalog dataframe
# - halpha_fits: Halpha FITS path
# - zoi_label: ZOI label map (2D)
# - boundary_label: final boundary label map (2D)

# Optional: zoom limits (set to None to show full frame)
xlim = (50, 2000)
ylim = (50, 2000)

contzoi_fits = f"ZOI_maps/ZOI_map_{max_zoi}pc/ContZoI_map_{field}.fits"
contzoi_label = fits.getdata(contzoi_fits)
cont_map_fits = f"Boundary_maps/Boundary_map_100pc/ContDomain_map_{field}.fits"
cont_map = fits.getdata(cont_map_fits)

plot_maps_dir = f"plots/individual_field_flux_plots/{field}"
os.makedirs(plot_maps_dir, exist_ok=True)
folder = f"../M33-Maps-Calibrated/M33-{field}/"
for line in ["ha", "hb", "oiii5007", "sii6716", "sii6731", "nii6584", "oii3727"]:
    line_fits = f"{folder}M33{field}-{line}flux.fits"
    line_data = fits.getdata(line_fits)
    line_data = np.where(np.isfinite(line_data), line_data, np.nan)
    plot_overlay_path = f"{plot_maps_dir}/M33_{field}_{line}_overlay.png"
    print(f"Creating overlay plot for {line} with peaks, ZOI, and boundaries; saving to: {plot_overlay_path}")
    plot_field_overlay_halpha_peaks_zoi_boundaries(
        catalog_df=merged_df,
        ha_fits_path=line_fits,
        zoi_label_map=contzoi_label,
        boundary_label_map=cont_map,
        field_name=f"M33 {field}",
        x_col="x",
        y_col="y",
        region_label_col="zoi_center_label",
        xlim=xlim,
        ylim=ylim,
        show_peaks=True,
        show_zoi=True,
        show_boundaries=True,
        savepath=plot_overlay_path,
        line = line
    )